const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const script=fs.readFileSync(path.join(__dirname,'../rpys-print-center-v413.js'),'utf8');
function fixture(){const dom=new JSDOM('<select id="month"><option value="2026-10">Ekim 2026</option></select><section id="saymanlik"><button id="normal">Yazdır</button></section><section id="yazdir"><div id="r377v4"><div data-pack="0"><button class="r377print" data-rpys383print="say"><span>Paketi Yazdır</span></button></div></div></section>',{url:'https://example.com',runScripts:'outside-only'});const w=dom.window;
 w.eval(`var db={assign:{a:25},printCenter:{doc:'say1'},sayRoster:{}},original=db,_allAssignCache={a:1},_peopleCache=[1],_assignCache={a:2},_calcCache={a:3};var cacheRefs=[_allAssignCache,_peopleCache,_assignCache,_calcCache];var failRender=false;
 function ym(){return document.getElementById('month').value}
 function stablePrintHeader(t){return '<h2>'+t+' '+ym()+'</h2>'}function stableSignatures(){return ''}
 function stableDutyDoc(t){db.sayRoster[ym()]='generated';if(failRender)throw Error('renderer failed');return stablePrintHeader(t)+'<table><tr><td>Örnek '+t+'</td></tr></table>'}
 function stableSayDoc(n,t){return stableDutyDoc(t)}function sayNamesForPage(n){return ['Örnek '+n]}
 function centerLeaveHtml(){return stableDutyDoc('İzin')}
 function totals(){return [{p:{name:'Örnek 1'},pol:70,ac:100,total:170,muk:154,diff:16},{p:{name:'Örnek 2'},pol:100,ac:0,total:100,muk:154,diff:-54}]}
 function puantajValue(r,k){return r[k]}function assignmentsMonth(){return [{person:{id:1},col:{unit:'BT',hours:23}},{person:{id:1},col:{unit:'BT',hours:16}}]}`);
 w.alert=m=>{w.error=m};w.eval(script);return {dom,w,d:w.document,api:w.rpysBulkPrint413};}
function pack(rows){return {name:'Örnek Paket',rows}}
test('mixed documents, months, copies and two-part lists preserve workspace identity and caches',()=>{const {dom,w,api}=fixture();try{const before=JSON.stringify(w.db),result=api.build(pack([{doc:'say1',period:'this',copies:2},{doc:'nobet',period:'prev',copies:1},{doc:'birim',period:'fixed',fixed:'2025-12',copies:1}]));assert.equal(result.parts.length,5);assert.deepEqual(Array.from(result.parts,p=>p.month),['2026-10','2026-10','2026-09','2026-09','2025-12']);assert.match(result.parts[2].body,/pol 2026-09/);assert.match(result.parts[3].body,/acil 2026-09/);assert.match(result.parts[4].body,/>39</);assert.equal(w.db,w.original);assert.equal(JSON.stringify(w.db),before);assert.equal(w.document.getElementById('month').value,'2026-10');assert.equal(w.document.querySelectorAll('option').length,1);assert.equal(w._calcCache,w.cacheRefs[3]);}finally{dom.window.close()}});
test('failure restores live data, selected month and cache references',()=>{const {dom,w,api}=fixture();try{w.failRender=true;assert.throws(()=>api.build(pack([{doc:'nobet',period:'prev',copies:1}])),/renderer failed/);assert.equal(w.db,w.original);assert.equal(w.document.getElementById('month').value,'2026-10');assert.deepEqual(Object.keys(w.db.sayRoster),[]);assert.equal(w._assignCache,w.cacheRefs[2]);}finally{dom.window.close()}});
test('window routing defeats payroll capture, prints only isolated iframe and leaves normal buttons native',()=>{const {dom,w,d}=fixture();try{let wrong=0;d.addEventListener('click',e=>{wrong++;e.stopImmediatePropagation()},true);w.localStorage.setItem('rpys_bulk_print_377',JSON.stringify([pack([{doc:'nobet',period:'this',copies:1}])]));d.querySelector('.r377print span').click();assert.equal(wrong,0);assert.equal(w.error,undefined);const frame=d.querySelector('#rpysBulkPreview413 iframe');assert.ok(frame);assert.equal(frame.contentDocument.querySelectorAll('.sheet').length,2);let printed=0;frame.contentWindow.focus=()=>{};frame.contentWindow.print=()=>printed++;d.querySelector('[data-bulk-print]').click();assert.equal(printed,1);assert.equal(wrong,0);d.querySelector('[data-bulk-close]').click();assert.equal(d.querySelector('#rpysBulkPreview413'),null);d.getElementById('normal').click();assert.equal(wrong,1);}finally{dom.window.close()}});
test('validation, year rollover and all document types',()=>{const {dom,api}=fixture();try{assert.equal(api.period({period:'prev2'},'2026-01'),'2025-11');assert.throws(()=>api.build(pack([{doc:'say1',period:'fixed',copies:1}])));assert.throws(()=>api.build(pack([{doc:'say1',period:'this',copies:51}])));const result=api.build(pack(['say1','say2','mesai','nobet','puantaj','izin','birim','fazla'].map(doc=>({doc,period:'this',copies:1}))));assert.equal(result.parts.length,10);assert.ok(!result.parts.at(-1).body.includes('Örnek 2'));assert.match(api.html(result),/break-before:page/);}finally{dom.window.close()}});

