// Fictional machine-generated fixtures only. No personnel records.
const test=require('node:test'),assert=require('node:assert/strict');
const Q=require('../yea-suite/history-query.js'),P=require('../yea-suite/history-parser.js');
const r=(extra={})=>({person:'TEST PERSON A',date:'2024-02-01',unit:'BT',hours:23,shift:'08:00-07:00',importId:'fixture-a',fileName:'fixture.xlsx',sheet:'Test',row:3,col:2,...extra});
test('exact repeats deduplicate and retain both sources',()=>{const out=Q.run([r(),r({fileName:'fixture-2.xlsx'})],{}, {},P);assert.equal(out.totals.totalCount,1);assert.equal(out.duplicates,1);assert.equal(out.records[0].sources.length,2);});
test('separate same-day non-overlapping shifts remain separate',()=>{const out=Q.run([r({shift:'08:00-16:00',hours:8}),r({shift:'16:00-23:00',hours:7})],{}, {},P);assert.equal(out.totals.totalCount,2);assert.equal(out.totals.workedDays,1);assert.equal(out.totals.totalHours,15);});
test('conflicts are excluded until reviewed, other policies explicit',()=>{const records=[r(),r({hours:24})];assert.equal(Q.run(records,{}, {},P).totals.totalCount,0);assert.equal(Q.run(records,{}, {},P).issues.length,2);assert.equal(Q.run(records,{}, {policy:'largest'},P).totals.totalHours,24);assert.equal(Q.run(records,{}, {policy:'all'},P).totals.totalHours,47);});
test('unit classification controls counts without modifying source',()=>{const records=[r()];assert.equal(Q.run(records,{'BT':'day'}, {},P).totals.dayCount,1);assert.equal(Q.run(records,{'BT':'exclude'}, {},P).totals.totalCount,0);assert.equal(records[0].category,undefined);});
test('date, month, year, person, text and hour filters combine',()=>{const records=[r(),r({date:'2023-02-01'}),r({person:'TEST PERSON B'})];assert.equal(Q.run(records,{}, {start:'2024-01-01',end:'2024-12-31',year:'2024',month:'2',person:'test person a',text:'bt',min:20,max:24},P).totals.totalCount,1);});
test('missing hours never invented and weekends selectable',()=>{const records=[r({date:'2024-02-03',hours:0})];const out=Q.run(records,{}, {weekday:'weekend',hours:'unknown'},P);assert.equal(out.totals.unknownHours,1);assert.equal(out.totals.totalHours,0);assert.equal(Q.run(records,{}, {weekday:'weekday'},P).totals.totalCount,0);});
test('year comparison clamps leap day',()=>{assert.deepEqual(Q.previousYear({year:'2024',start:'2024-02-29',end:'2024-03-31'}),{year:'2023',start:'2023-02-28',end:'2023-03-31'});});
test('invalid dates excluded and reported',()=>{const out=Q.run([r({date:'2024-02-30'})],{}, {},P);assert.equal(out.invalid,1);assert.equal(out.totals.totalCount,0);});
test('all grouping totals reconcile',()=>{const records=[r(),r({date:'2025-02-01',unit:'DEXA',hours:7,shift:'08:00-15:00'})];for(const group of ['person','month','year','unit','personMonth']){const out=Q.run(records,{}, {group},P);assert.equal(out.groups.reduce((s,x)=>s+x.totalHours,0),out.totals.totalHours);assert.equal(out.totals.totalHours,30);}});
test('source filter happens before duplicate resolution',()=>{assert.equal(Q.run([r(),r({importId:'fixture-b',hours:24})],{}, {source:'fixture-a'},P).totals.totalHours,23);});
test('CSV escapes spreadsheet formula injection and preserves numeric negatives',()=>{const csv=Q.csv([['=TEST()', '+TEST','@TEST',-2,'a"b']]);assert.ok(csv.includes("'=TEST()"));assert.ok(csv.includes('"-2"'));assert.ok(csv.includes('"a""b"'));});
test('working days distinct across same-day units',()=>{const out=Q.run([r(),r({unit:'DEXA',hours:7})],{}, {},P);assert.equal(out.totals.totalCount,2);assert.equal(out.totals.workedDays,1);});
