'use strict';
(() => {
  const $=s=>document.querySelector(s),E=window.YeaArcadeEngine,W=window.YeaWorld3D,KEY='yea_arcade_progress_v1';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const meta={castle:['Kale Atışı','FİZİK','Nişan al. Kuleleri devir.'],arrows:['Ok Yolu','BULMACA','Önü açık okları sırayla çıkar.'],wood:['Ahşap Atölyesi','ATÖLYE','Dönen ahşaba kendi formunu ver.'],hole:['Yutan Halka','TOPLAMA','Oyuncakları topla, büyü.'],territory:['Bölge Akışı','STRATEJİ','Haritayı kendi rengine boya.'],blocks:['Renkli Rota','BULMACA','Blokları renkli kapılara kaydır.']};
  const help={castle:'Kaledeki bir taşa dokunarak nişan al, ardından Atış yap. Taşlar ağırlık ve çarpışmayla devrilir. Kalenin en az %80’ini dağıt. Zayıflayan kulelerin altına nişan almak işe yarar. Kamera düğmesiyle farklı açıdan bakabilirsin.',arrows:'Bir oka dokun. Önünde başka bir ok yoksa tahtadan çıkar. Kapalı yola dokunmak bir hak götürür. Üç hakkın var. İpucu ve Geri al kullanılabilir.',wood:'Ahşabın sağ kenarında parmağını aşağı ve yukarı sürükle. Beyaz hedef çizgisine kadar yavaşça yaklaş. Parça gerçekten döner ve kestiğin yerde incelir. En az %80 uyumda bir renk seçip Bitir. Fazla kesilen ahşap geri gelmez; Baştan ile tekrar dene.',hole:'Parmağını oyun alanında sürükleyerek deliği hareket ettir. Önce küçük nesneleri içine al. Topladıkça delik büyür ve daha büyük oyuncakları toplayabilir. Süre bitmeden hepsini topla.',territory:'Mavi bir bölgeden hedef bölgeye sürükle veya iki bölgeye sırayla dokun. Güçler zamanla artar. Göndereceğin oranı aşağıdan seçebilirsin. Bütün haritayı mavi yap. Kırmızı rakip de yeni bölgelere ilerler.',blocks:'Bir bloğu parmağınla tutup yatay veya dikey kaydır. Bloğun harfi ve rengiyle aynı kapıya hizala, kapıdan dışarı kaydır. Diğer bloklar yolunu kapatabilir. Geri al ile son hamleni düzeltebilirsin.'};
  let progress,storageOK=true;
  function normalize(raw){const out={version:1,games:{}};for(const g of E.catalog){const p=raw?.games?.[g.id]||{};out.games[g.id]={unlocked:E.clamp(Math.floor(Number(p.unlocked)||1),1,g.levels),best:E.clamp(Math.floor(Number(p.best)||0),0,100000),plays:E.clamp(Math.floor(Number(p.plays)||0),0,100000),wins:E.clamp(Math.floor(Number(p.wins)||0),0,100000)};}return out;}
  try{progress=normalize(JSON.parse(localStorage.getItem(KEY)||'null'));}catch{progress=normalize(null);storageOK=false;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageOK=true;return true;}catch{storageOK=false;$('#storage-message').textContent='Cihaz kaydı kullanılamıyor. Ayrılmadan önce ilerlemeni yedekle.';return false;}}
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2500);}
  let active=null,level=1,model=null,world=null,renderer=null,paused=false,settled=false,raf=0,last=0,hudAt=0,endAt=0,drag=null,selected=null,hint=-1,cameraStep=0,ratio=.6;
  const canvas=document.createElement('canvas');canvas.tabIndex=0;canvas.setAttribute('role','img');
  let brush={x:394,y:260,down:false},target={x:0,y:2,z:1};const keys=new Set(),thumbs={},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  let sound=false,audioContext=null;
  function sfx(kind='tap'){if(!sound||!audioContext)return;try{audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime;o.connect(g);g.connect(audioContext.destination);o.type=kind==='fire'?'triangle':'sine';const hz=kind==='win'?620:kind==='fire'?120:420;o.frequency.setValueAtTime(hz,t);o.frequency.exponentialRampToValueAtTime(kind==='win'?1200:hz*.5,t+.22);g.gain.setValueAtTime(kind==='fire'?.1:.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.start(t);o.stop(t+.25);}catch{}}
  function makeModel(id,l){return id==='castle'?new window.YeaCastle3D(l):new(E.catalog.find(g=>g.id===id).Model)(l);}
  function renderLobby(){
    $('#game-list').innerHTML=E.catalog.map(g=>{const p=progress.games[g.id],m=meta[g.id];return `<article class="game-card"><button class="game-open" data-start="${g.id}" aria-label="${m[0]} oyna"><span class="game-art">${thumbs[g.id]?`<img src="${thumbs[g.id]}" alt="${m[0]} üç boyutlu oyun sahnesi" width="400" height="300">`:''}<span class="genre">${m[1]}</span></span><span class="game-card-body"><b>${m[0]}</b><span class="game-desc">${m[2]}</span></span></button><div class="level-row"><label><select data-level="${g.id}" aria-label="${m[0]} bölüm seç">${Array.from({length:p.unlocked},(_,i)=>`<option value="${i+1}"${i+1===p.unlocked?' selected':''}>Bölüm ${i+1}${i+1===p.unlocked?' · Devam':''}</option>`).join('')}</select></label><button class="play-small" data-start="${g.id}" aria-label="${m[0]} başlat">›</button></div></article>`;}).join('');
  }
  function lobby(){cancelAnimationFrame(raf);world?.dispose();world=null;active=null;model=null;keys.clear();brush.down=false;drag=null;$('#lobby').hidden=false;$('#play').hidden=true;$('#overlay').hidden=true;document.body.classList.remove('playing');renderLobby();window.scrollTo(0,0);}
  function thumbnails(){if(!renderer)return;renderer.setSize(400,300,false);for(const g of E.catalog){const m=makeModel(g.id,1),w=new W.World(renderer,g.id,m,true);if(g.id==='wood')m.profile=m.target.map(r=>r+8);w.camera.aspect=4/3;w.camera.updateProjectionMatrix();w.update(.016,{target,brush});w.render();thumbs[g.id]=canvas.toDataURL('image/webp',.82);w.dispose();}renderer.setSize(520,520,false);$('#loading').hidden=true;renderLobby();}
  function start(id,l){
    if(!renderer){toast('3D görüntüleyici açılamadı. Sayfayı Safari veya Chrome’da aç.');return;}
    const g=E.catalog.find(x=>x.id===id);if(!g)return;cancelAnimationFrame(raf);world?.dispose();level=E.clamp(Number(l)||progress.games[id].unlocked,1,progress.games[id].unlocked);model=makeModel(id,level);active=g;paused=false;settled=false;endAt=0;hint=-1;selected=id==='blocks'?model.pieces[0].id:null;drag=null;keys.clear();brush={x:394,y:260,down:false};target={x:0,y:1.4,z:1.7};cameraStep=0;ratio=.6;
    $('#lobby').hidden=true;$('#play').hidden=false;$('#overlay').hidden=true;document.body.classList.add('playing');$('#game-title').textContent=meta[id][0];$('#level-label').textContent=`Bölüm ${level} / ${g.levels}`;$('#stage').replaceChildren(canvas);canvas.setAttribute('aria-label',meta[id][0]+'. '+help[id]);$('#game-message').textContent='';$('#instruction').textContent=({castle:'Kaledeki bir taşa dokun, sonra atış yap.',arrows:'Önü açık oka dokun. Doğru sırayı bul.',wood:'Sağ kenardan kes. Beyaz hedef çizgisine yaklaş.',hole:'Parmağını sürükle. Küçük oyuncaklarla başla.',territory:'Mavi bölgeden hedef bölgeye sürükle.',blocks:'Bloğu tut ve aynı renkli kapıya doğru kaydır.'})[id];$('#undo').hidden=!['arrows','blocks'].includes(id);$('#controls').innerHTML='';$('#camera').hidden=id==='arrows';
    renderer.setSize(520,520,false);world=new W.World(renderer,id,model);controls(id);world.update(.016,{brush,target,selected});world.render();progress.games[id].plays++;save();updateHud();if(location.hash!=='#'+id)history.pushState(null,'','#'+id);last=performance.now();hudAt=0;raf=requestAnimationFrame(frame);window.scrollTo(0,0);
  }
  function controls(id){
    const c=$('#controls');
    if(id==='castle'){c.innerHTML='<button id="fire" class="primary">Atış yap</button>';$('#fire').onclick=()=>{if(canPlay()&&model.fire(target)){sfx('fire');updateHud();}};}
    if(id==='wood'){c.innerHTML='<div class="stains"><button data-stain="0" aria-pressed="true">Doğal</button><button data-stain="1" aria-pressed="false">Ceviz</button><button data-stain="2" aria-pressed="false">Mavi</button></div><button id="finish" class="primary">Bitir</button>';c.querySelectorAll('[data-stain]').forEach(b=>b.onclick=()=>{if(!canPlay())return;model.stain=+b.dataset.stain;c.querySelectorAll('[data-stain]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sfx();});$('#finish').onclick=()=>{if(canPlay()&&!model.finish())toast(`Uyum %${model.accuracy()}. Bitirmek için en az %80 gerekiyor.`);};}
    if(id==='arrows'){c.innerHTML='<button id="hint" class="primary">İpucu</button><label>Ok<select id="arrow-select" aria-label="Satır ve sütunla ok seç"></select></label><button id="arrow-tap">Çıkar</button>';$('#hint').onclick=()=>{if(canPlay()){hint=model.hint();syncArrows();toast('Sarı okun yolu açık.');}};$('#arrow-tap').onclick=()=>tapArrow(+$('#arrow-select').value);syncArrows();}
    if(id==='territory'){c.innerHTML='<label>Gönderilecek güç<select id="ratio"><option value=".25">%25</option><option value=".6" selected>%60</option><option value="1">%100</option></select></label><label>Bölge<select id="node-select">'+model.nodes.map(n=>`<option value="${n.id}">${n.id+1}</option>`).join('')+'</select></label><button id="node-tap">Seç / gönder</button>';$('#ratio').onchange=e=>ratio=+e.target.value;$('#node-tap').onclick=()=>{if(canPlay())selectNode(+$('#node-select').value);};}
    if(id==='blocks'){c.innerHTML='<label>Blok<select id="block-select"></select></label><button id="gate">Kapıyı göster</button><div class="block-controls"><button data-dir="3" aria-label="Sola">←</button><button data-dir="0" aria-label="Yukarı">↑</button><button data-dir="2" aria-label="Aşağı">↓</button><button data-dir="1" aria-label="Sağa">→</button></div>';$('#block-select').onchange=e=>selected=e.target.value;$('#gate').onclick=()=>{const p=model.pieces.find(x=>x.id===selected);if(p)toast(`${p.id} kapısı: ${['üst','sağ','alt','sol'][p.exit]} kenar, ${p.lane+1}. ${p.exit%2?'satır':'sütun'}.`);};c.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>moveBlock(+b.dataset.dir));syncBlocks();}
  }
  function canPlay(){return active&&model?.status==='playing'&&!paused;}
  function syncArrows(){const a=$('#arrow-select');if(!a)return;a.innerHTML=model.cells.map((d,i)=>d==null?'':`<option value="${i}">${Math.floor(i/model.n)+1}, ${i%model.n+1} ${E.GLYPHS[d]}</option>`).join('');if(hint>=0)a.value=hint;}
  function syncBlocks(){const s=$('#block-select');s.innerHTML=model.pieces.filter(p=>!p.out).map(p=>`<option value="${p.id}">${p.name} · ${p.id}</option>`).join('');s.value=selected||'';}
  function tapArrow(i){if(!canPlay()||model.cells[i]==null)return;hint=-1;if(model.tap(i)){sfx();}else{toast('Yol kapalı. Önündeki okları çıkar.');sfx('fire');}syncArrows();updateHud();}
  function moveBlock(dir){if(!canPlay()||!selected)return;const current=selected;if(model.move(current,dir)){sfx();if(model.pieces.find(p=>p.id===current).out){selected=model.pieces.find(p=>!p.out)?.id||null;toast('Doğru kapı!');}syncBlocks();updateHud();}}
  function selectNode(id){if(!canPlay())return;const n=model.nodes[id];if(selected!=null&&selected!==id&&model.send(selected,id,ratio)){selected=null;sfx();return;}selected=n?.owner===1?id:null;if(selected==null)toast('Önce mavi bölgelerinden birini seç.');}
  function updateHud(){if(!active)return;let h=[];switch(active.id){case'castle':h=[['Atış',model.shots],['Yıkım','%'+Math.round(model.hits/model.total*100)],['Hedef','%80']];$('#fire').disabled=!!model.cooldown||!canPlay();$('#fire').textContent=model.cooldown>0?'Taşlar yerleşiyor…':'Atış yap';break;case'wood':h=[['Uyum','%'+model.accuracy()],['Hedef','%80'],['Bölüm',level]];break;case'hole':h=[['Toplanan',`${model.collected}/${model.total}`],['Süre',Math.ceil(model.time)+' sn'],['Boyut',(model.hole.r/17).toFixed(1)+'×']];break;case'blocks':h=[['Çıkış',`${model.pieces.filter(p=>p.out).length}/${model.pieces.length}`],['Hamle',model.moves],['Blok',selected||'—']];break;case'arrows':h=[['Kalan',model.cells.filter(d=>d!=null).length],['Hak','●'.repeat(model.lives)||'0'],['Hamle',model.moves]];break;case'territory':h=[['Mavi',model.nodes.filter(n=>n.owner===1).length],['Kırmızı',model.nodes.filter(n=>n.owner===2).length],['Süre',Math.floor(model.time)+' sn']];break;}$('#hud').innerHTML=h.map(([a,b])=>`<span>${a}<b>${esc(b)}</b></span>`).join('');$('#undo').disabled=!model.history?.length||model.status==='won';}
  canvas.addEventListener('pointerdown',e=>{if(!canPlay())return;e.preventDefault();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);const p=world.coordinates(e.clientX,e.clientY);drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:p.x,py:p.y,hit:p.hit,moved:false,source:null};
    if(active.id==='castle'&&p.hit?.block!=null){const b=model.blocks[p.hit.block];target={x:b.body.position.x,y:b.body.position.y,z:b.body.position.z};sfx();}
    if(active.id==='hole')model.target={x:p.x,y:p.y};
    if(active.id==='wood')setBrush(p);
    if(active.id==='blocks'&&p.hit?.piece){selected=p.hit.piece;syncBlocks();}
    if(active.id==='territory'&&p.hit?.node!=null&&model.nodes[p.hit.node].owner===1)drag.source=p.hit.node;
  });
  function setBrush(p){brush={x:260+Math.abs(p.plane.x)*44,y:55+(3.8-p.plane.y)/7.6*410,down:true};}
  canvas.addEventListener('pointermove',e=>{if(!canPlay()||!drag||e.pointerId!==drag.id)return;e.preventDefault();const p=world.coordinates(e.clientX,e.clientY);if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(active.id==='hole')model.target={x:p.x,y:p.y};if(active.id==='wood')setBrush(p);if(active.id==='territory'&&drag.moved&&drag.source!=null)selected=drag.source;
    if(active.id==='blocks'){const dx=p.x-drag.px,dy=p.y-drag.py;if(Math.max(Math.abs(dx),Math.abs(dy))>44){const dir=Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0;moveBlock(dir);drag.px=p.x;drag.py=p.y;}}
  });
  function release(e){if(!drag||drag.id!==e.pointerId)return;if(canPlay()){const p=world.coordinates(e.clientX,e.clientY);if(active.id==='arrows'&&!drag.moved&&p.hit?.arrow!=null)tapArrow(p.hit.arrow);if(active.id==='territory'&&p.hit?.node!=null){if(drag.moved&&drag.source!=null)selected=drag.source;selectNode(p.hit.node);}}brush.down=false;drag=null;}
  canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>{brush.down=false;drag=null;});canvas.addEventListener('lostpointercapture',()=>{brush.down=false;drag=null;});
  function frame(now){if(!active||paused||!world)return;const dt=Math.min(.033,Math.max(0,(now-last)/1000));last=now;
    if(canPlay()){const dx=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),dy=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);if(active.id==='hole'&&(dx||dy))model.target={x:model.hole.x+dx*45,y:model.hole.y+dy*45};if(active.id==='wood'){brush.x=E.clamp(brush.x+dx*100*dt,284,410);brush.y=E.clamp(brush.y+dy*140*dt,55,465);brush.down=brush.down||keys.has(' ');if(brush.down&&brush.y>=55&&brush.y<=465)model.cut((brush.y-55)/410*(model.rows-1),Math.abs(brush.x-260),dt);}model.update?.(dt);}
    world.update(dt,{brush,target,selected,hint});world.render();if(now-hudAt>130){updateHud();hudAt=now;}if(model.status!=='playing'&&!settled){if(!endAt)endAt=now;if(now-endAt>650)finish();}if(!paused)raf=requestAnimationFrame(frame);
  }
  function overlay(title,text,symbol,actions){paused=true;keys.clear();brush.down=false;drag=null;cancelAnimationFrame(raf);$('#result-title').textContent=title;$('#result-text').textContent=text;$('#result-symbol').textContent=symbol;$('#result-actions').replaceChildren();for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=fn;$('#result-actions').append(b);}$('#overlay').hidden=false;$('#result-actions button')?.focus();}
  function resume(){if(!active)return;paused=false;$('#overlay').hidden=true;keys.clear();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame);canvas.focus({preventScroll:true});}
  function pause(showHelp=false){if(!canPlay())return;overlay(showHelp?'Nasıl oynanır?':'Oyun duraklatıldı',showHelp?help[active.id]:'Hazır olduğunda kaldığın yerden devam et.','Ⅱ',[['Devam et',resume],['Oyun listesi',goLobby]]);}
  function finish(){settled=true;const won=model.status==='won',id=active.id,l=level,p=progress.games[id],actions=[];let message;
    if(won){p.wins++;p.best=Math.max(p.best,model.score());p.unlocked=Math.min(active.levels,Math.max(p.unlocked,level+1));save();sfx('win');message=model.score().toLocaleString('tr-TR')+' puan. '+(level===active.levels?'Tüm bölümleri bitirdin!':'Sıradaki bölüm açıldı.');if(!storageOK)message+=' Cihaz kaydı başarısız; ilerlemeni yedekle.';if(level<active.levels)actions.push(['Sonraki bölüm',()=>start(id,l+1)]);}else{message=active.id==='castle'?'Atışlar bitti. Kulelerin alt taşlarına nişan almayı dene.':active.id==='hole'?'Süre bitti. Küçük oyuncaklarla başlayıp halkayı büyüt.':active.id==='territory'?'Mavi bölgeler tükendi. Yakın bölgelerden güç kazanmayı dene.':'Haklar bitti. Son hamleyi geri alabilirsin.';if(model.history?.length)actions.push(['Geri al',undo]);}
    actions.push(['Tekrar oyna',()=>start(id,l)],['Oyun listesi',goLobby]);overlay(won?'Bölüm tamamlandı!':'Bir daha deneyelim',message,won?'✦':'↻',actions);
  }
  function undo(){if(!model?.undo||model.status==='won'||!model.undo())return;settled=false;endAt=0;hint=-1;if(active.id==='blocks'){selected=model.pieces.find(p=>!p.out)?.id;syncBlocks();}else syncArrows();updateHud();resume();}
  function goLobby(){history.pushState(null,'',location.pathname);lobby();}
  $('#game-list').onclick=e=>{const b=e.target.closest('[data-start]');if(b)start(b.dataset.start,$(`[data-level="${b.dataset.start}"]`).value);};
  $('#back').onclick=()=>{if(canPlay())overlay('Oyundan çıkılsın mı?','Bu bölüm baştan başlar. Tamamladığın bölümler ve rekorların korunur.','↶',[['Devam et',resume],['Listeye dön',goLobby]]);else goLobby();};$('#pause').onclick=()=>pause();$('#help').onclick=()=>pause(true);$('#undo').onclick=undo;
  $('#restart').onclick=()=>{if(!active)return;const id=active.id,l=level;overlay('Bölüm yeniden başlasın mı?','Yalnız bu bölümdeki hamleler sıfırlanır.','↻',[['Yeniden başla',()=>start(id,l)],['Vazgeç',resume]]);};
  $('#camera').onclick=()=>{if(!world||paused)return;cameraStep=(cameraStep+1)%3;if(active.id==='castle')world.camera.position.set([11,0,-11][cameraStep],[9.4,9,9.4][cameraStep],[17,21,17][cameraStep]);else if(active.id==='wood')world.camera.position.set([0,4,-4][cameraStep],1.8,16);else world.camera.position.set([0,4,-4][cameraStep],17,11);world.camera.lookAt(active.id==='wood'?new THREE.Vector3():world.focus);};
  $('#quality').onclick=()=>{if(!renderer)return;renderer.shadowMap.enabled=!renderer.shadowMap.enabled;$('#quality').textContent=renderer.shadowMap.enabled?'Gölge açık':'Gölge kapalı';$('#quality').setAttribute('aria-pressed',String(renderer.shadowMap.enabled));renderer.setPixelRatio(renderer.shadowMap.enabled?Math.min(devicePixelRatio||1,1.7):1);world?.scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});};
  $('#sound').onclick=()=>{sound=!sound;if(sound){try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{sound=false;}}$('#sound').textContent=sound?'Ses açık':'Ses kapalı';$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').setAttribute('aria-label',sound?'Oyun sesini kapat':'Oyun sesini aç');sfx();};
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});addEventListener('blur',()=>{keys.clear();brush.down=false;pause();});
  addEventListener('keydown',e=>{if($('#overlay').hidden===false&&e.key==='Tab'){const buttons=[...$('#result-actions').querySelectorAll('button')],first=buttons[0],lastButton=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){lastButton.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===lastButton){first.focus();e.preventDefault();}return;}if(!active||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){e.preventDefault();if(paused&&model.status==='playing')resume();else pause();return;}if(!canPlay())return;const dir=({ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3})[e.key];if(dir!=null||['w','a','s','d',' '].includes(e.key.toLowerCase())){e.preventDefault();keys.add(e.key.toLowerCase());if(active.id==='blocks'&&dir!=null&&!e.repeat)moveBlock(dir);if(active.id==='castle'&&e.key===' '&&!e.repeat)$('#fire').click();}});
  addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' '&&!drag)brush.down=false;});addEventListener('popstate',()=>{const id=location.hash.slice(1);if(E.catalog.some(g=>g.id===id))start(id);else lobby();});
  $('#export-progress').onclick=()=>{const json=JSON.stringify(progress,null,2);if(window.YeaNative?.exportProgress){window.YeaNative.exportProgress(json);return;}const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='YEA_Oyun_Ilerleme_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
  $('#import-progress').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>100000)throw new Error('Yedek çok büyük.');const raw=JSON.parse(await f.text());if(raw.version!==1||!raw.games||typeof raw.games!=='object')throw new Error('Geçerli bir oyun yedeği değil.');const next=normalize(raw);for(const g of E.catalog)for(const field of ['unlocked','best','plays','wins'])progress.games[g.id][field]=Math.max(progress.games[g.id][field],next.games[g.id][field]);save();renderLobby();toast(storageOK?'İlerlemeler birleştirildi.':'Yedek bu oturumda açıldı; cihaz kaydı başarısız.');}catch(err){toast('Yedek açılamadı: '+err.message);}};
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();toast('3D görüntü durakladı. Görüntü geri geldiğinde devam et.');});canvas.addEventListener('webglcontextrestored',()=>{if(active){const id=active.id,l=level;start(id,l);toast('Görüntü yeniden açıldı; bölüm baştan başladı.');}});
  lobby();if(!window.THREE||!window.CANNON||!W){$('#loading').textContent='3D motoru yüklenemedi. İnternete bağlanıp sayfayı yeniden aç; gerekirse Safari veya Chrome’da dene.';$('#game-list').querySelectorAll('button').forEach(b=>b.disabled=true);return;}try{renderer=W.createRenderer(canvas);}catch(err){$('#loading').textContent='3D oyun alanı açılamadı. Güncel Safari veya Chrome’da açıp tekrar dene.';$('#game-list').querySelectorAll('button').forEach(b=>b.disabled=true);console.error(err);return;}
  setTimeout(()=>{try{thumbnails();const id=location.hash.slice(1);if(E.catalog.some(g=>g.id===id))start(id);}catch(err){$('#loading').textContent='Oyun önizlemeleri hazırlanamadı. Aşağıdaki oyunu seçerek açabilirsin.';console.error(err);}},0);
  if(!storageOK)$('#storage-message').textContent='İlerleme kaydı kullanılamıyor. Ayrılmadan önce yedek al.';
})();
