'use strict';
(() => {
  const $=s=>document.querySelector(s),E=window.YeaArcadeEngine,W=window.YeaWorld3D,S=window.YeaStudio,KEY='yea_arcade_progress_v1';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const meta={castle:['Kale Atışı','FİZİK','Nişan al. Kuleleri devir.'],arrows:['Ok Yolu','BULMACA','Önü açık okları sırayla çıkar.'],wood:['Ahşap Atölyesi','YAKIN PLAN','Parçanın başında şekillendir ve cilala.'],hole:['Yutan Halka','ARKADAN TAKİP','Halkanın arkasından meydanı keşfet.'],territory:['Bölge Akışı','STRATEJİ','Haritayı kendi rengine boya.'],blocks:['Renkli Rota','BULMACA','Blokları renkli kapılara kaydır.']};
  const help={castle:'Kaledeki bir taşa dokunarak nişan al, ardından Atış yap. Taşlar ağırlık ve çarpışmayla devrilir. Kalenin en az %80’ini dağıt. Zayıflayan kulelerin altına nişan almak işe yarar. Kamera düğmesiyle farklı açıdan bakabilirsin.',arrows:'Bir oka dokun. Önünde başka bir ok yoksa tahtadan çıkar. Kapalı yola dokunmak bir hak götürür. Üç hakkın var. İpucu ve Geri al kullanılabilir.',wood:'Bu, sanal bir tasarım atölyesi. Şekil aşamasında kenardan içeri ve yukarı-aşağı sürükleyerek sağ üstteki hedef forma yaklaş. Yeşil halkalar hedefe ulaştığın bölgelerde belirir. Hedef koruması fazla inceltmeyi önler; istersen kapatabilirsin. %90 uyumda pürüzsüzleştirmeye geç. Yakın planda ahşabın iki yanında da çalışabilirsin. Bütün yüzeyini tara, sonra renk seçip cilala. Cila yalnız gezindiğin bölgede parlayacaktır. Her aşamanın ilerlemesi ayrı hesaplanır. Klavyede oklar veya WASD ile imleci taşı, boşluk tuşunu basılı tutarak uygula.',hole:'Kamera halkanın arkasından gelir ve dönüşlerde yumuşakça döner. Parmağını ileri sürükle; yönünü değiştirmek için çubuğu yönlendir. Parmağını bırakıp tekrar dokunduğunda kontrol yeni kamera açısına göre başlar. Altın işaret yakınındaki toplanabilir nesneyi gösterir. İstersen kontrolü Dokun olarak değiştir. Portakallar ve toplarla başla; saksı, kasa, tabure, araba ve ağaçlara doğru büyü. Nesneler tamamen düştükten sonra sayılır. Peş peşe toplamak çarpanı artırır; sekizli seri 3 saniye kazandırır. İlk hareketten önce Süresiz keşif seçebilirsin. Klavyede oklar veya WASD kullan.',territory:'Mavi bir bölgeden hedef bölgeye sürükle veya iki bölgeye sırayla dokun. Güçler zamanla artar. Göndereceğin oranı aşağıdan seçebilirsin. Bütün haritayı mavi yap. Kırmızı rakip de yeni bölgelere ilerler.',blocks:'Bir bloğu parmağınla tutup yatay veya dikey kaydır. Bloğun harfi ve rengiyle aynı kapıya hizala, kapıdan dışarı kaydır. Diğer bloklar yolunu kapatabilir. Geri al ile son hamleni düzeltebilirsin.'};
  let progress,storageOK=true;
  function normalize(raw){const out={version:1,games:{}};for(const g of E.catalog){const p=raw?.games?.[g.id]||{};out.games[g.id]={unlocked:E.clamp(Math.floor(Number(p.unlocked)||1),1,g.levels),best:E.clamp(Math.floor(Number(p.best)||0),0,100000),plays:E.clamp(Math.floor(Number(p.plays)||0),0,100000),wins:E.clamp(Math.floor(Number(p.wins)||0),0,100000)};}return out;}
  try{progress=normalize(JSON.parse(localStorage.getItem(KEY)||'null'));}catch{progress=normalize(null);storageOK=false;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageOK=true;return true;}catch{storageOK=false;$('#storage-message').textContent='Cihaz kaydı kullanılamıyor. Ayrılmadan önce ilerlemeni yedekle.';return false;}}
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2500);}
  let active=null,level=1,model=null,world=null,renderer=null,paused=false,settled=false,raf=0,last=0,hudAt=0,endAt=0,drag=null,selected=null,hint=-1,cameraStep=0,ratio=.6;
  const canvas=document.createElement('canvas');canvas.tabIndex=0;canvas.setAttribute('role','img');
  let brush={x:394,y:260,down:false},target={x:0,y:2,z:1};const keys=new Set(),thumbs={},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const audio=window.YeaGameAudio?new window.YeaGameAudio.Player(window):null;let cameraDrag=false;
  function sfx(kind='tap'){audio?.effect(kind);}
  function unlockAudio(){audio?.unlock().then(ok=>{if(!ok&&audio.music)$('#audio-status').textContent='Sesi açmak için Müzik düğmesine dokun.';else $('#audio-status').textContent='Oynarken çalar.';});}
  function syncAudio(){if(!audio)return;$('#sound').textContent=audio.music?'♫ Müzik açık':'♫ Müzik kapalı';$('#sound').setAttribute('aria-pressed',String(audio.music));$('#sound').setAttribute('aria-label',audio.music?'Müziği kapat':'Müziği aç');$('#audio-volume').value=Math.round(audio.volume/.7*100);$('#volume-value').textContent=Math.round(audio.volume/.7*100)+'%';$('#audio-effects').checked=audio.effects;}
  function setCameraDrag(on){cameraDrag=on;stopStroke();$('#orbit').setAttribute('aria-pressed',String(on));$('#orbit').textContent=on?'▶ Oyuna dön':'3B Çevir';$('#camera-hint').hidden=!on;if(!on)world?.returnToPlay?.();if(active?.id==='hole'){$('#orbit').textContent=on?'▶ Takibe dön':'Serbest bakış';$('#camera-hint').textContent='Parmağınla etrafa bak. Oynamak için Takibe dön.';}else $('#camera-hint').textContent='Parmağınla sahneyi çevir. Devam etmek için Oyuna dön.';}
  function makeModel(id,l){return id==='wood'?new S.WoodStudio(l):id==='hole'?new S.HoleWorld(l):id==='castle'?new window.YeaCastle3D(l):new(E.catalog.find(g=>g.id===id).Model)(l);}
  function makeWorld(id,m,preview=false){return new (['hole','wood'].includes(id)?window.YeaImmersiveWorld:window.YeaArcadeWorldV4)(renderer,id,m,preview);}
  let steering='joystick',lastCollected=0,keyboardSteering='';
  function resizeStage(){if(!active||!world)return;const tall=['wood','hole'].includes(active.id);renderer.setSize(520,tall?650:520,false);world.camera.aspect=tall?4/5:1;world.camera.updateProjectionMatrix();}
  function steerHole(x,y){const v=world.steer?.(x,y)||{x,y};model.target={x:model.hole.x+v.x*32,y:model.hole.y+v.y*32};}
  function stopStroke(){brush.down=false;model?.endStroke?.();world?.endSteering?.();keyboardSteering='';if(active?.id==='hole'&&steering==='joystick'&&model)model.target={x:model.hole.x,y:model.hole.y};drag=null;$('#joystick').hidden=true;}
  function blueprint(){const r=model.target,points=r.map((n,i)=>`${50+n*.29},${7+i/(r.length-1)*76}`).concat(r.slice().reverse().map((n,i)=>`${50-n*.29},${83-i/(r.length-1)*76}`)).join(' ');return `<svg viewBox="0 0 100 90" aria-label="Hedef form" role="img"><path d="M50 0V90" stroke="#ffffff35" stroke-dasharray="2 3"/><polygon points="${points}" fill="#cfad7c" stroke="#f7dfa9" stroke-width="1.5"/></svg>`;}
  function studioHud(){
    if(active.id==='wood'){
      const phase=model.phase,index=['shape','sand','finish','display'].indexOf(phase);$('#phase-steps').querySelectorAll('span').forEach((el,i)=>{el.dataset.state=i<index?'done':i===index?'active':'next';el.setAttribute('aria-current',String(i===index));});
      const p=model.progress();$('#studio-progress').value=p;$('#studio-percent').textContent='%'+p;$('#studio-label').textContent=({shape:'Şablona uyum',sand:'Yüzey pürüzsüzlüğü',finish:'Cila kaplaması',display:'Tasarım tamamlandı'})[phase];
      $('#wood-shape').hidden=phase!=='shape';$('#wood-stains').hidden=phase!=='finish';$('#finish').hidden=phase==='display';$('#finish').disabled=p<model.required()||!canPlay();$('#finish').textContent=({shape:'Pürüzsüzleştirmeye geç →',sand:'Renk ve cilaya geç →',finish:'Eserini sergile ✦',display:'Tamamlandı'})[phase];
      $('#scene-note').textContent=phase==='display'?'Elinden çıkan tasarım':model.name;
      $('#instruction').textContent=({shape:model.assist?'Parçanın kenarından içeri doğru sürükle. Koruma açıkken hedef formun altına inmez.':'Serbest form açık. Fazla inceltilen kısım geri gelmez.',sand:'Ahşabın yüzeyinde yukarı-aşağı gezin. Tüm parçayı pürüzsüzleştir.',finish:'Bir renk seç. Parmağınla yüzeyi tarayarak cilayı uygula.',display:'Eserin sergileniyor. Yeni tasarım birazdan açılacak.'})[phase];
    }else if(active.id==='hole'){
      $('#studio-progress').value=model.collected/model.total*100;$('#studio-percent').textContent=model.collected+' / '+model.total;$('#studio-label').textContent=model.theme.name;$('#scene-note').textContent=model.combo>1?model.combo+'’li seri · '+Math.min(4,1+Math.floor(model.combo/5))+'× puan':model.started?(world.targetHint?.()||'Küçükten büyüğe topla'):'Sürükle · arkandan takip et';$('#relaxed').disabled=model.started;$('#scene-badge').textContent=model.relaxed?'SÜRESİZ KEŞİF':'ARKADAN TAKİP';
    }
  }
  function renderLobby(){
    $('#game-list').innerHTML=E.catalog.map(g=>{const p=progress.games[g.id],m=meta[g.id];return `<article class="game-card"><button class="game-open" data-start="${g.id}" aria-label="${m[0]} oyna"><span class="game-art">${thumbs[g.id]?`<img src="${thumbs[g.id]}" alt="${m[0]} üç boyutlu oyun sahnesi" width="400" height="300">`:''}<span class="genre">${m[1]}</span></span><span class="game-card-body"><b>${m[0]}</b><span class="game-desc">${m[2]}</span></span></button><div class="level-row"><label><select data-level="${g.id}" aria-label="${m[0]} bölüm seç">${Array.from({length:p.unlocked},(_,i)=>`<option value="${i+1}"${i+1===p.unlocked?' selected':''}>Bölüm ${i+1}${i+1===p.unlocked?' · Devam':''}</option>`).join('')}</select></label><button class="play-small" data-start="${g.id}" aria-label="${m[0]} başlat">›</button></div></article>`;}).join('');
  }
  function lobby(){audio?.pause();cancelAnimationFrame(raf);world?.dispose();world=null;active=null;model=null;keys.clear();brush.down=false;drag=null;$('#lobby').hidden=false;$('#play').hidden=true;$('#overlay').hidden=true;document.body.classList.remove('playing');$('#studio-panel').hidden=true;$('#scene-label').hidden=true;$('#joystick').hidden=true;$('#camera-hint').hidden=true;renderLobby();window.scrollTo(0,0);}
  function thumbnails(){if(!renderer)return;renderer.setSize(400,300,false);for(const g of E.catalog){const m=makeModel(g.id,1),w=makeWorld(g.id,m,true);if(g.id==='wood')m.profile=m.target.map(r=>r+8);w.camera.aspect=4/3;w.camera.updateProjectionMatrix();w.update(.016,{target,brush});w.render();thumbs[g.id]=canvas.toDataURL('image/webp',.82);w.dispose();}renderer.setSize(520,520,false);$('#loading').hidden=true;renderLobby();}
  function start(id,l){
    if(!renderer){toast('3D görüntüleyici açılamadı. Sayfayı Safari veya Chrome’da aç.');return;}
    const g=E.catalog.find(x=>x.id===id);if(!g)return;cancelAnimationFrame(raf);world?.dispose();level=E.clamp(Number(l)||progress.games[id].unlocked,1,progress.games[id].unlocked);model=makeModel(id,level);active=g;paused=false;settled=false;endAt=0;hint=-1;selected=id==='blocks'?model.pieces[0].id:null;drag=null;keys.clear();brush={x:394,y:260,down:false};target={x:0,y:1.4,z:1.7};cameraStep=0;ratio=.6;
    $('#lobby').hidden=true;$('#play').hidden=false;$('#overlay').hidden=true;document.body.classList.add('playing');$('#game-title').textContent=meta[id][0];$('#level-label').textContent=`Bölüm ${level} / ${g.levels}`;$('#stage').replaceChildren(canvas);canvas.setAttribute('aria-label',meta[id][0]+'. '+help[id]);$('#game-message').textContent='';$('#instruction').textContent=({castle:'Kaledeki bir taşa dokun, sonra atış yap.',arrows:'Önü açık oka dokun. Doğru sırayı bul.',wood:'Kenarları şekillendir. Sağ üstteki hedef forma yaklaş.',hole:'Sürükle ve ilerle. Kamera arkandan gelir; altın işareti takip et.',territory:'Mavi bölgeden hedef bölgeye sürükle.',blocks:'Bloğu tut ve aynı renkli kapıya doğru kaydır.'})[id];$('#undo').hidden=!['arrows','blocks'].includes(id);$('#controls').innerHTML='';$('#camera').hidden=false;
    renderer.setSize(520,520,false);world=makeWorld(id,model);resizeStage();setCameraDrag(false);$('#camera').textContent=id==='hole'?'Arkadan ▾':'Açı ↻';audio?.play(id);lastCollected=0;$('#play').dataset.game=id;$('#studio-panel').hidden=!['wood','hole'].includes(id);$('#design-preview').hidden=id!=='wood';$('#scene-label').hidden=!['wood','hole'].includes(id);$('#joystick').hidden=true;controls(id);world.update(.016,{brush,target,selected});world.render();progress.games[id].plays++;save();updateHud();if(location.hash!=='#'+id)history.pushState(null,'','#'+id);last=performance.now();hudAt=0;raf=requestAnimationFrame(frame);window.scrollTo(0,0);
  }
  function controls(id){
    const c=$('#controls');
    if(id==='castle'){c.innerHTML='<button id="fire" class="primary">Atış yap</button>';$('#fire').onclick=()=>{if(canPlay()&&model.fire(target)){sfx('fire');updateHud();}};}
    if(id==='wood'){
      $('#phase-steps').hidden=false;$('#phase-steps').innerHTML='<span>1 · Form</span><span>2 · Yüzey</span><span>3 · Cila</span>';$('#design-preview').hidden=false;$('#design-preview').innerHTML=blueprint();$('#scene-badge').textContent='AHŞAP STÜDYOSU';
      c.innerHTML='<div id="wood-shape" class="studio-options"><button id="assist" aria-pressed="true">Hedef koruması açık</button><button id="precision" aria-pressed="false">Geniş fırça</button></div><div id="wood-stains" class="stains" hidden>'+['Doğal','Ceviz','Bal','Petrol','Gece'].map((n,i)=>'<button data-stain="'+i+'" aria-pressed="'+(i===0)+'">'+n+'</button>').join('')+'</div><button id="finish" class="primary"></button>';
      $('#assist').onclick=()=>{if(!canPlay())return;model.assist=!model.assist;$('#assist').setAttribute('aria-pressed',String(model.assist));$('#assist').textContent=model.assist?'Hedef koruması açık':'Serbest form';if(!model.assist)toast('Serbest form: Fazla inceltilen kısım geri gelmez.');};
      $('#precision').onclick=()=>{if(!canPlay())return;model.precision=!model.precision;$('#precision').setAttribute('aria-pressed',String(model.precision));$('#precision').textContent=model.precision?'İnce fırça':'Geniş fırça';};
      c.querySelectorAll('[data-stain]').forEach(b=>b.onclick=()=>{if(!canPlay())return;model.stain=+b.dataset.stain;c.querySelectorAll('[data-stain]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sfx();});
      $('#finish').onclick=()=>{if(canPlay()&&model.advance()){stopStroke();sfx('win');studioHud();}};studioHud();
    }
    if(id==='hole'){
      $('#phase-steps').hidden=true;$('#design-preview').hidden=true;c.innerHTML='<div class="studio-options"><label class="check-option"><input id="relaxed" type="checkbox"> Süresiz keşif</label><label>Kontrol <select id="steering"><option value="joystick">Joystick</option><option value="touch">Dokun</option></select></label></div>';
      $('#steering').value=steering;$('#steering').onchange=e=>{stopStroke();steering=e.target.value;};$('#relaxed').onchange=e=>model.setRelaxed(e.target.checked);studioHud();
    }
    if(id==='arrows'){c.innerHTML='<button id="hint" class="primary">İpucu</button><label>Ok<select id="arrow-select" aria-label="Satır ve sütunla ok seç"></select></label><button id="arrow-tap">Çıkar</button>';$('#hint').onclick=()=>{if(canPlay()){hint=model.hint();syncArrows();toast('Sarı okun yolu açık.');}};$('#arrow-tap').onclick=()=>tapArrow(+$('#arrow-select').value);syncArrows();}
    if(id==='territory'){c.innerHTML='<label>Gönderilecek güç<select id="ratio"><option value=".25">%25</option><option value=".6" selected>%60</option><option value="1">%100</option></select></label><label>Bölge<select id="node-select">'+model.nodes.map(n=>`<option value="${n.id}">${n.id+1}</option>`).join('')+'</select></label><button id="node-tap">Seç / gönder</button>';$('#ratio').onchange=e=>ratio=+e.target.value;$('#node-tap').onclick=()=>{if(canPlay())selectNode(+$('#node-select').value);};}
    if(id==='blocks'){c.innerHTML='<label>Blok<select id="block-select"></select></label><button id="gate">Kapıyı göster</button><div class="block-controls"><button data-dir="3" aria-label="Sola">←</button><button data-dir="0" aria-label="Yukarı">↑</button><button data-dir="2" aria-label="Aşağı">↓</button><button data-dir="1" aria-label="Sağa">→</button></div>';$('#block-select').onchange=e=>selected=e.target.value;$('#gate').onclick=()=>{const p=model.pieces.find(x=>x.id===selected);if(p)toast(`${p.id} kapısı: ${['üst','sağ','alt','sol'][p.exit]} kenar, ${p.lane+1}. ${p.exit%2?'satır':'sütun'}.`);};c.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>moveBlock(+b.dataset.dir));syncBlocks();}
  }
  function canPlay(){return active&&model?.status==='playing'&&!paused;}
  function syncArrows(){const a=$('#arrow-select');if(!a)return;a.innerHTML=model.cells.map((d,i)=>d==null?'':`<option value="${i}">${Math.floor(i/model.n)+1}, ${i%model.n+1} ${E.GLYPHS[d]}</option>`).join('');if(hint>=0)a.value=hint;}
  function syncBlocks(){const s=$('#block-select');s.innerHTML=model.pieces.filter(p=>!p.out).map(p=>`<option value="${p.id}">${p.name} · ${p.id}</option>`).join('');s.value=selected||'';}
  function tapArrow(i){if(!canPlay()||model.cells[i]==null)return;hint=-1;if(model.tap(i)){sfx();}else{toast('Yol kapalı. Önündeki okları çıkar.');sfx('fire');}syncArrows();updateHud();}
  function moveBlock(dir){if(!canPlay()||!selected)return;const current=selected;if(model.move(current,dir)){sfx();if(model.pieces.find(p=>p.id===current).out){selected=model.pieces.find(p=>!p.out)?.id||null;toast('Doğru kapı!');}syncBlocks();updateHud();}}
  function selectNode(id){if(!canPlay())return;const n=model.nodes[id];if(selected!=null&&selected!==id&&model.send(selected,id,ratio)){selected=null;sfx();return;}selected=n?.owner===1?id:null;if(selected==null)toast('Önce mavi bölgelerinden birini seç.');}
  function updateHud(){if(!active)return;let h=[];switch(active.id){case'castle':h=[['Atış',model.shots],['Yıkım','%'+Math.round(model.hits/model.total*100)],['Hedef','%80']];$('#fire').disabled=!!model.cooldown||!canPlay();$('#fire').textContent=model.cooldown>0?'Taşlar yerleşiyor…':'Atış yap';break;case'wood':h=[['Form','%'+model.accuracy()],['Yüzey','%'+model.smoothness()],['Cila','%'+model.coverage()]];studioHud();break;case'hole':h=[['Toplanan',`${model.collected}/${model.total}`],['Süre',model.relaxed?'∞':Math.ceil(model.time)+' sn'],['Çap',(model.hole.r/18).toFixed(1)+'×']];studioHud();break;case'blocks':h=[['Çıkış',`${model.pieces.filter(p=>p.out).length}/${model.pieces.length}`],['Hamle',model.moves],['Blok',selected||'—']];break;case'arrows':h=[['Kalan',model.cells.filter(d=>d!=null).length],['Hak','●'.repeat(model.lives)||'0'],['Hamle',model.moves]];break;case'territory':h=[['Mavi',model.nodes.filter(n=>n.owner===1).length],['Kırmızı',model.nodes.filter(n=>n.owner===2).length],['Süre',Math.floor(model.time)+' sn']];break;}$('#hud').innerHTML=h.map(([a,b])=>`<span>${a}<b>${esc(b)}</b></span>`).join('');$('#undo').disabled=!model.history?.length||model.status==='won';}
  canvas.addEventListener('pointerdown',e=>{if(!canPlay()||drag)return;e.preventDefault();unlockAudio();window.YeaGameInput.capture(canvas,e);const p=world.coordinates(e.clientX,e.clientY);drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:p.x,py:p.y,hit:p.hit,moved:false,source:null};if(cameraDrag){drag.camera=true;drag.lastX=e.clientX;drag.lastY=e.clientY;return;}
    if(active.id==='castle'&&p.hit?.block!=null){const b=model.blocks[p.hit.block];target={x:b.body.position.x,y:b.body.position.y,z:b.body.position.z};sfx();}
    if(active.id==='hole'){if(steering==='touch'){if(p.validGround!==false)model.target={x:p.x,y:p.y};}else{world.beginSteering?.();drag.ax=drag.ay=0;const r=canvas.getBoundingClientRect();$('#joystick').hidden=false;$('#joystick').style.left=(e.clientX-r.left)+'px';$('#joystick').style.top=(e.clientY-r.top)+'px';$('#joystick-knob').style.transform='translate(-50%,-50%)';}}
    if(active.id==='wood')setBrush(p,e);
    if(active.id==='blocks'&&p.hit?.piece){selected=p.hit.piece;syncBlocks();}
    if(active.id==='territory'&&p.hit?.node!=null&&model.nodes[p.hit.node].owner===1)drag.source=p.hit.node;
  });
  function setBrush(p,event){const near=event&&world.brushCoordinates?.(event.clientX,event.clientY);brush=near||{x:260+Math.abs(p.plane.x)*44,y:55+(3.8-p.plane.y)/7.6*410,down:true};}
  canvas.addEventListener('pointermove',e=>{if(!canPlay()||!drag||e.pointerId!==drag.id)return;e.preventDefault();if(drag.camera){world.rotateCamera(e.clientX-drag.lastX,e.clientY-drag.lastY);drag.lastX=e.clientX;drag.lastY=e.clientY;return;}const p=world.coordinates(e.clientX,e.clientY);if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(active.id==='hole'){if(steering==='touch'){if(p.validGround!==false)model.target={x:p.x,y:p.y};}else{const dx=e.clientX-drag.x,dy=e.clientY-drag.y,d=Math.max(1,Math.hypot(dx,dy)/30);drag.ax=E.clamp(dx/52,-1,1);drag.ay=E.clamp(dy/52,-1,1);if(Math.hypot(drag.ax,drag.ay)<.1)drag.ax=drag.ay=0;$('#joystick-knob').style.transform='translate(calc(-50% + '+dx/d+'px),calc(-50% + '+dy/d+'px))';}}if(active.id==='wood')setBrush(p,e);if(active.id==='territory'&&drag.moved&&drag.source!=null)selected=drag.source;
    if(active.id==='blocks'){const dx=p.x-drag.px,dy=p.y-drag.py;if(Math.max(Math.abs(dx),Math.abs(dy))>44){const dir=Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0;moveBlock(dir);drag.px=p.x;drag.py=p.y;}}
  });
  function release(e){if(!drag||drag.id!==e.pointerId)return;if(drag.camera){stopStroke();return;}if(canPlay()){const p=world.coordinates(e.clientX,e.clientY);if(active.id==='arrows'&&!drag.moved&&p.hit?.arrow!=null)tapArrow(p.hit.arrow);if(active.id==='territory'&&p.hit?.node!=null){if(drag.moved&&drag.source!=null)selected=drag.source;selectNode(p.hit.node);}}stopStroke();}
  canvas.addEventListener('pointerup',release);addEventListener('pointerup',release);const cancelPointer=e=>{if(drag?.id===e.pointerId)stopStroke();};canvas.addEventListener('pointercancel',cancelPointer);addEventListener('pointercancel',cancelPointer);canvas.addEventListener('lostpointercapture',cancelPointer);canvas.addEventListener('contextmenu',e=>e.preventDefault());
  function frame(now){if(!active||paused||!world)return;const dt=Math.min(.033,Math.max(0,(now-last)/1000));last=now;
    if(canPlay()){let dx=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),dy=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);if(cameraDrag){if(dx||dy)world.rotateCamera(dx*140*dt,dy*140*dt);dx=dy=0;}if(active.id==='hole'&&steering==='joystick'&&drag&&!drag.camera)steerHole(drag.ax,drag.ay);if(active.id==='hole'&&(dx||dy)){const signature=dx+','+dy;if(signature!==keyboardSteering){world.beginSteering?.();keyboardSteering=signature;}steerHole(dx,dy);}if(active.id==='wood'){if(dx||dy){brush.x=E.clamp(brush.x+dx*100*dt,284,410);brush.y=E.clamp(brush.y+dy*140*dt,55,465);delete brush.point;}brush.down=brush.down||keys.has(' ');if(brush.down&&brush.y>=55&&brush.y<=465)model.cut((brush.y-55)/410*(model.rows-1),Math.abs(brush.x-260),dt);else model.endStroke();}model.update?.(dt);if(active.id==='hole'&&model.collected>lastCollected){sfx('collect');lastCollected=model.collected;}}
    world.update(dt,{brush,target,selected,hint});world.render();if(now-hudAt>130){updateHud();hudAt=now;}if(model.status!=='playing'&&!settled){if(!endAt)endAt=now;if(now-endAt>650)finish();}if(!paused)raf=requestAnimationFrame(frame);
  }
  function overlay(title,text,symbol,actions){audio?.pause();paused=true;keys.clear();stopStroke();cancelAnimationFrame(raf);$('#result-title').textContent=title;$('#result-text').textContent=text;$('#result-symbol').textContent=symbol;$('#result-actions').replaceChildren();for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=fn;$('#result-actions').append(b);}$('#overlay').hidden=false;$('#result-actions button')?.focus();}
  function resume(event){if(!active)return;audio?.play(active.id);unlockAudio();paused=false;$('#overlay').hidden=true;keys.clear();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame);if(!event||event.detail===0)canvas.focus({preventScroll:true});}
  function pause(showHelp=false){if(!canPlay())return;overlay(showHelp?'Nasıl oynanır?':'Oyun duraklatıldı',showHelp?help[active.id]:'Hazır olduğunda kaldığın yerden devam et.','Ⅱ',[['Devam et',resume],['Oyun listesi',goLobby]]);}
  function finish(){settled=true;const won=model.status==='won',id=active.id,l=level,p=progress.games[id],actions=[];let message;
    if(won){p.wins++;p.best=Math.max(p.best,model.score());p.unlocked=Math.min(active.levels,Math.max(p.unlocked,level+1));save();sfx('win');message=(id==='wood'?'★'.repeat(model.stars())+' · '+model.name+'. ':id==='hole'?'En iyi seri: '+model.bestCombo+'. ':'')+model.score().toLocaleString('tr-TR')+' puan. '+(level===active.levels?'Tüm bölümleri bitirdin!':'Sıradaki bölüm açıldı.');if(!storageOK)message+=' Cihaz kaydı başarısız; ilerlemeni yedekle.';if(level<active.levels)actions.push(['Sonraki bölüm',()=>start(id,l+1)]);}else{message=active.id==='castle'?'Atışlar bitti. Kulelerin alt taşlarına nişan almayı dene.':active.id==='hole'?'Süre bitti. Küçük oyuncaklarla başlayıp halkayı büyüt.':active.id==='territory'?'Mavi bölgeler tükendi. Yakın bölgelerden güç kazanmayı dene.':'Haklar bitti. Son hamleyi geri alabilirsin.';if(model.history?.length)actions.push(['Geri al',undo]);}
    actions.push(['Tekrar oyna',()=>start(id,l)],['Oyun listesi',goLobby]);overlay(won?'Bölüm tamamlandı!':'Bir daha deneyelim',message,won?'✦':'↻',actions);
  }
  function undo(){if(!model?.undo||model.status==='won'||!model.undo())return;settled=false;endAt=0;hint=-1;if(active.id==='blocks'){selected=model.pieces.find(p=>!p.out)?.id;syncBlocks();}else syncArrows();updateHud();resume();}
  function goLobby(){history.pushState(null,'',location.pathname);lobby();}
  $('#game-list').onclick=e=>{const b=e.target.closest('[data-start]');if(b){unlockAudio();start(b.dataset.start,$(`[data-level="${b.dataset.start}"]`).value);if(e.detail===0)canvas.focus({preventScroll:true});}};
  $('#back').onclick=()=>{if(canPlay())overlay('Oyundan çıkılsın mı?','Bu bölüm baştan başlar. Tamamladığın bölümler ve rekorların korunur.','↶',[['Devam et',resume],['Listeye dön',goLobby]]);else goLobby();};$('#pause').onclick=()=>pause();$('#help').onclick=()=>pause(true);$('#undo').onclick=undo;
  $('#restart').onclick=()=>{if(!active)return;const id=active.id,l=level;overlay('Bölüm yeniden başlasın mı?','Yalnız bu bölümdeki hamleler sıfırlanır.','↻',[['Yeniden başla',()=>start(id,l)],['Vazgeç',resume]]);};
  $('#camera').onclick=()=>{if(!world||paused)return;cameraStep=(cameraStep+1)%3;world.setCamera(cameraStep);if(['hole','wood'].includes(active.id))setCameraDrag(false);if(active.id==='hole')$('#camera').textContent=['Arkadan ▾','Yakın takip ▾','Geniş takip ▾'][cameraStep];};$('#orbit').onclick=()=>{if(world&&!paused)setCameraDrag(!cameraDrag);};
  $('#quality').onclick=()=>{if(!renderer)return;renderer.shadowMap.enabled=!renderer.shadowMap.enabled;$('#quality').textContent=renderer.shadowMap.enabled?'Gölge açık':'Gölge kapalı';$('#quality').setAttribute('aria-pressed',String(renderer.shadowMap.enabled));renderer.setPixelRatio(renderer.shadowMap.enabled?Math.min(devicePixelRatio||1,1.7):1);world?.scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});};
  $('#sound').onclick=()=>{if(!audio)return;audio.setMusic(!audio.music);if(audio.music){if(canPlay())audio.play(active.id);unlockAudio();}syncAudio();};$('#audio-volume').oninput=e=>{audio?.setVolume(+e.target.value/100*.7);syncAudio();};$('#audio-effects').onchange=e=>{audio?.setEffects(e.target.checked);unlockAudio();sfx();};syncAudio();
  window.YeaGameInput.bindLifecycle(window,document,{background:()=>{keys.clear();stopStroke();pause();audio?.pause(true);},clearKeyboard:()=>{keys.clear();if(!drag){brush.down=false;model?.endStroke?.();}}});
  addEventListener('keydown',e=>{if($('#overlay').hidden===false&&e.key==='Tab'){const buttons=[...$('#result-actions').querySelectorAll('button')],first=buttons[0],lastButton=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){lastButton.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===lastButton){first.focus();e.preventDefault();}return;}if(!active)return;if(e.key==='Escape'){e.preventDefault();if(paused&&model.status==='playing')resume();else pause();return;}if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)||!canPlay())return;const dir=({ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3})[e.key];if(dir!=null||['w','a','s','d',' '].includes(e.key.toLowerCase())){e.preventDefault();if(audio?.context?.state!=='running')unlockAudio();keys.add(e.key.toLowerCase());if(!cameraDrag&&active.id==='blocks'&&dir!=null&&!e.repeat)moveBlock(dir);if(!cameraDrag&&active.id==='castle'&&e.key===' '&&!e.repeat)$('#fire').click();}});
  addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' '&&!drag){brush.down=false;model?.endStroke?.();}if(active?.id==='hole'&&!drag&&!keys.size){model.target={x:model.hole.x,y:model.hole.y};world.endSteering?.();keyboardSteering='';}});addEventListener('popstate',()=>{const id=location.hash.slice(1);if(E.catalog.some(g=>g.id===id))start(id);else lobby();});
  $('#export-progress').onclick=()=>{const json=JSON.stringify(progress,null,2);if(window.YeaNative?.exportProgress){window.YeaNative.exportProgress(json);return;}const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='YEA_Oyun_Ilerleme_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
  $('#import-progress').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>100000)throw new Error('Yedek çok büyük.');const raw=JSON.parse(await f.text());if(raw.version!==1||!raw.games||typeof raw.games!=='object')throw new Error('Geçerli bir oyun yedeği değil.');const next=normalize(raw);for(const g of E.catalog)for(const field of ['unlocked','best','plays','wins'])progress.games[g.id][field]=Math.max(progress.games[g.id][field],next.games[g.id][field]);save();renderLobby();toast(storageOK?'İlerlemeler birleştirildi.':'Yedek bu oturumda açıldı; cihaz kaydı başarısız.');}catch(err){toast('Yedek açılamadı: '+err.message);}};
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();toast('3D görüntü durakladı. Görüntü geri geldiğinde devam et.');});canvas.addEventListener('webglcontextrestored',()=>{if(active){const id=active.id,l=level;start(id,l);toast('Görüntü yeniden açıldı; bölüm baştan başladı.');}});
  lobby();if(!window.THREE||!window.CANNON||!W||!S||!window.YeaStudioWorld||!window.YeaArcadeWorldV4||!window.YeaGameInput||!window.YeaImmersiveWorld||!window.YeaChase){$('#loading').textContent='3D motoru yüklenemedi. İnternete bağlanıp sayfayı yeniden aç; gerekirse Safari veya Chrome’da dene.';$('#game-list').querySelectorAll('button').forEach(b=>b.disabled=true);return;}try{renderer=W.createRenderer(canvas);}catch(err){$('#loading').textContent='3D oyun alanı açılamadı. Güncel Safari veya Chrome’da açıp tekrar dene.';$('#game-list').querySelectorAll('button').forEach(b=>b.disabled=true);console.error(err);return;}
  setTimeout(()=>{try{thumbnails();const id=location.hash.slice(1);if(E.catalog.some(g=>g.id===id))start(id);}catch(err){$('#loading').textContent='Oyun önizlemeleri hazırlanamadı. Aşağıdaki oyunu seçerek açabilirsin.';console.error(err);}},0);
  if(!storageOK)$('#storage-message').textContent='İlerleme kaydı kullanılamıyor. Ayrılmadan önce yedek al.';
})();
