(()=>{'use strict';
const M=window.RPYSDesktopModel,E=M.escape,$=s=>document.querySelector(s),KEY='rpys_desktop_demo_v408';let data=M.seed(),wins=new Map(),z=10,toastTimer;
try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);data=M.validate(x);}}catch{notify('Demo kaydı okunamadı; örnek veriler açıldı.');}
const themes=[['ocean','Okyanus','#e9f1f6','#006e73'],['midnight','Gece','#172438','#82e0d3'],['graphite','Grafit','#2c2e34','#c6b4ff'],['ivory','Fildişi','#fffdf6','#805411'],['forest','Orman','#e5eee7','#23663d'],['contrast','Yüksek kontrast','#000','#ffeb00']];
function notify(s){const el=$('#toast');el.textContent=s;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3600);}
function save(message){if(message)data.audit.unshift({at:new Date().toISOString(),text:message});data.audit=data.audit.slice(0,100);try{localStorage.setItem(KEY,JSON.stringify(data));$('#saveState').textContent='● Demo kaydedildi';return true;}catch{$('#saveState').textContent='⚠ Kayıt yapılamadı';notify('Tarayıcıya kayıt yapılamadı. Dosyalar bölümünden yedek indir.');return false;}}
function change(message){save(message);for(const w of wins.values())render(w);}
function applyTheme(){document.body.dataset.theme=themes.some(t=>t[0]===data.theme)?data.theme:'ocean';}
function drawDesktop(){ $('#welcomeCount').textContent=M.catalog.length+' modül';$('#shortcuts').innerHTML=M.catalog.filter(m=>data.pins.includes(m.id)).map(m=>`<div class="shortcut"><button class="launch" data-open="${m.id}"><span class="app-icon">${m.icon}</span><span>${E(m.title)}</span><small>${m.view==='preview'?'Yerleşim önizlemesi':'Çalışır demo'}</small></button><button class="unpin" data-unpin="${m.id}" title="Masaüstünden kaldır" aria-label="${E(m.title)} kısayolunu kaldır">×</button></div>`).join('');drawStart();}
function drawStart(){const q=$('#appSearch').value.toLocaleLowerCase('tr');$('#startApps').innerHTML=M.catalog.filter(m=>m.title.toLocaleLowerCase('tr').includes(q)).map(m=>`<button data-open="${m.id}">${m.icon} ${E(m.title)}${m.view==='preview'?' · Önizleme':''}</button>`).join('');}
function start(show){$('#startMenu').hidden=!show;$('#startButton').setAttribute('aria-expanded',show);if(show)$('#appSearch').focus();}
function tasks(){$('#tasks').innerHTML=[...wins.values()].map(w=>`<button data-task="${w.m.id}" class="${!w.el.hidden?'active':''}" title="${E(w.m.title)}">${w.m.icon} ${E(w.m.title)}</button>`).join('');}
function focus(w){for(const v of wins.values())v.el.classList.remove('focused');w.el.hidden=false;w.el.style.zIndex=++z;w.el.classList.add('focused');tasks();fitAreas(w);}
function open(id){start(false);if(wins.has(id)){focus(wins.get(id));return;}const m=M.catalog.find(m=>m.id===id);if(!m)return;const el=document.createElement('section');el.className='window';el.setAttribute('aria-label',m.title);const offset=wins.size%5*24;el.style.left=Math.min(35+offset,Math.max(4,innerWidth-360))+'px';el.style.top=88+offset+'px';el.style.width=Math.min(980,innerWidth-60)+'px';el.style.height=Math.min(660,innerHeight-170)+'px';el.innerHTML=`<header class="window-head"><span>${m.icon}</span><strong>${E(m.title)}</strong><small>ÖRNEK VERİ</small><button data-win="min" aria-label="Pencereyi küçült">−</button><button data-win="max" aria-label="Pencereyi büyüt veya geri al">□</button><button data-win="close" aria-label="Pencereyi kapat">×</button></header><div class="window-body"></div>`;$('#windows').append(el);const w={m,el,body:el.querySelector('.window-body'),filters:{},fit:new Set()};wins.set(id,w);el.addEventListener('pointerdown',()=>focus(w));el.addEventListener('click',e=>onClick(w,e));el.addEventListener('change',e=>onChange(w,e));drag(w);w.ro=new ResizeObserver(()=>fitAreas(w));w.ro.observe(el);render(w);focus(w);}
function drag(w){const head=w.el.querySelector('.window-head');let p;head.addEventListener('pointerdown',e=>{if(e.target.closest('button')||innerWidth<701||w.el.classList.contains('max'))return;p={x:e.clientX,y:e.clientY,left:w.el.offsetLeft,top:w.el.offsetTop};head.setPointerCapture(e.pointerId);});head.addEventListener('pointermove',e=>{if(!p)return;w.el.style.left=Math.max(0,Math.min(innerWidth-150,p.left+e.clientX-p.x))+'px';w.el.style.top=Math.max(73,Math.min(innerHeight-110,p.top+e.clientY-p.y))+'px';});head.addEventListener('pointerup',()=>p=null);head.addEventListener('pointercancel',()=>p=null);}
function tile(){const a=[...wins.values()].filter(w=>!w.el.hidden);if(innerWidth<701){notify('Telefonda modüller arasında alt çubuktan geçebilirsin.');return;}const cols=a.length>3?3:Math.max(1,a.length),rows=Math.ceil(a.length/cols),width=(innerWidth-24)/cols,height=(innerHeight-150)/Math.max(1,rows);a.forEach((w,i)=>{w.el.classList.remove('max');Object.assign(w.el.style,{left:8+(i%cols)*width+'px',top:80+Math.floor(i/cols)*height+'px',width:width-8+'px',height:height-8+'px'});});}
function area(w,id,title,html){const key=w.m.id+':'+id,closed=!!data.collapsed[key];return `<section class="area" data-area="${id}"><header class="area-head"><button data-collapse="${id}" aria-expanded="${!closed}" title="Tabloyu aç / kapat">${closed?'▸':'▾'}</button><strong>${E(title)}</strong><div class="zoom-controls"><button data-zoom="minus" data-section="${id}" aria-label="Tabloyu küçült">−</button><span class="zoom-value">${data.zoom[key]||100}%</span><button data-zoom="plus" data-section="${id}" aria-label="Tabloyu büyüt">+</button><button data-zoom="reset" data-section="${id}" title="Gerçek boyut">100%</button><button data-zoom="fit" data-section="${id}">⌕ Sığdır</button></div></header><div class="area-scroll" ${closed?'hidden':''}><div class="scale-space"><div class="scale-content">${html}</div></div></div></section>`;}
function fitAreas(w){if(w.el.hidden)return;w.body.querySelectorAll('.area').forEach(a=>{const sc=a.querySelector('.area-scroll');if(sc.hidden)return;const id=a.dataset.area,key=w.m.id+':'+id,c=a.querySelector('.scale-content'),space=a.querySelector('.scale-space');let value=Math.min(200,Math.max(40,+data.zoom[key]||100));if(w.fit.has(id))value=Math.max(40,Math.min(100,Math.floor((sc.clientWidth-20)/c.offsetWidth*100)));c.style.transform=`scale(${value/100})`;space.style.width=c.offsetWidth*value/100+'px';space.style.height=c.offsetHeight*value/100+'px';a.querySelector('.zoom-value').textContent=value+'%';});}
function table(headers,rows,foot=''){return `<table><thead><tr>${headers.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${rows.join('')}</tbody>${foot?'<tfoot>'+foot+'</tfoot>':''}</table>`;}
const td=values=>'<tr>'+values.map(v=>'<td>'+v+'</td>').join('')+'</tr>';
function render(w){const scroll=w.body.scrollTop;const old={};w.body.querySelectorAll('.area').forEach(a=>{old[a.dataset.area]=[a.querySelector('.area-scroll').scrollLeft,a.querySelector('.area-scroll').scrollTop];});let html=`<div class="window-intro"><div><h2>${E(w.m.title)}</h2><p>Ekim 2026 · Bağımsız demo · Gerçek personel verisi içermez</p></div></div>`;
switch(w.m.view){case'schedule':html+=`<div class="notice">Başlıklardaki ← → ile vardiya sırasını değiştir. Hücre değişikliği ilk işlemde kaydedilir. Örnek koruma: 16 saat ve üzeri görevden sonraki gün yeni görev engellenir. Otomatik dağıtım motoru bu demoya bağlı değildir.</div>`;html+=area(w,'main','Aylık nöbet tablosu',table(['Gün',...data.shifts.map((s,i)=>`<div class="shift-head">${E(s.unit)}<small>${E(s.time)}</small><button data-shift="${s.id}" data-dir="-1" ${i===0?'disabled':''}>←</button> <button data-shift="${s.id}" data-dir="1" ${i===data.shifts.length-1?'disabled':''}>→</button></div>`)],Array.from({length:31},(_,i)=>{const d=i+1;return td([d+'.10.2026',...data.shifts.map(s=>`<select data-assignment="${d}|${s.id}" aria-label="${d} Ekim ${E(s.unit)} ${E(s.time)}"><option value="">— Boş —</option>${data.people.filter(p=>p.active||data.assignments[d+'|'+s.id]===p.id).map(p=>`<option value="${p.id}" ${data.assignments[d+'|'+s.id]===p.id?'selected':''}>${E(p.name)}</option>`).join('')}</select>`)]);})));break;
case'payroll':{const ids=[...new Set([...(data.payrollOrder||[]),...data.people.map(p=>p.id)])];let total=0;html+='<div class="notice">↑ ↓ personel sırasını değiştirir. Toplam saat elle düzenlenebilir; “↶” otomatik hesaba döndürür. Bu örnek toplam düzenlemesi nöbet hücrelerini değiştirmez.</div>';html+=area(w,'main','Saymanlık ve çalışma saatleri',table(['Sıra','Personel','Gündüz','Nöbet','Poliklinik saat','Acil saat','Toplam saat','Mükellef','Fark'],ids.map((id,i)=>{const p=data.people.find(p=>p.id===id);if(!p)return '';const t=M.totals(data,id),v=data.payrollOverrides[id]??t.hours;total+=v;return td([`<button class="order-btn" data-person="${id}" data-dir="-1" ${i===0?'disabled':''}>↑</button> <button class="order-btn" data-person="${id}" data-dir="1" ${i===ids.length-1?'disabled':''}>↓</button>`,E(p.name),t.day,t.night,t.pol,t.acil,`<input type="number" min="0" max="744" step="0.5" value="${v}" data-hours="${id}" aria-label="${E(p.name)} toplam saat"><button data-reset="${id}" title="Otomatik toplamı geri getir">↶</button>${id in data.payrollOverrides?'<span class="manual">Elle düzenlendi</span>':''}`,p.required,v-p.required]);}),td(['','TOPLAM','','','','',total,data.people.reduce((s,p)=>s+p.required,0),total-data.people.reduce((s,p)=>s+p.required,0)])));break;}
case'overview':{const hours=data.people.reduce((s,p)=>s+M.totals(data,p.id).hours,0);html+=`<div class="cards"><div class="metric"><small>Örnek personel</small><strong>${data.people.length}</strong></div><div class="metric"><small>Atanan görev</small><strong>${Object.keys(data.assignments).length}</strong></div><div class="metric"><small>Planlanan saat</small><strong>${hours}</strong></div></div>`;html+=area(w,'summary','Personel bazında çalışma',`<div style="min-width:480px">${data.people.map(p=>{const t=M.totals(data,p.id);return `<div class="bar-row"><span>${E(p.name)}</span><div class="bar"><i style="width:${Math.min(100,t.hours/400*100)}%"></i></div><b>${t.hours} s</b></div>`;}).join('')}</div>`);break;}
case'people':html+=area(w,'main','Personel kayıtları',table(['Personel','Durum','Mükellef saat'],data.people.map(p=>td([E(p.name),p.active?'Aktif':'Pasif',p.required]))));break;
case'shifts':html+=area(w,'main','Vardiya sırası',table(['Sıra','Birim','Saat','Süre','Tür'],data.shifts.map((s,i)=>td([`<button data-shift="${s.id}" data-dir="-1" ${!i?'disabled':''}>↑</button> <button data-shift="${s.id}" data-dir="1" ${i===data.shifts.length-1?'disabled':''}>↓</button>`,E(s.unit),E(s.time),s.hours,s.kind==='day'?'Gündüz':'Nöbet']))));break;
case'query':{const f=w.filters;html+=`<div class="filters"><select data-filter="person" aria-label="Personel filtresi"><option value="">Tüm personel</option>${data.people.map(p=>`<option value="${p.id}" ${f.person===p.id?'selected':''}>${E(p.name)}</option>`).join('')}</select><select data-filter="unit" aria-label="Birim filtresi"><option value="">Tüm birimler</option>${[...new Set(data.shifts.map(s=>s.unit))].map(u=>`<option ${f.unit===u?'selected':''}>${E(u)}</option>`).join('')}</select><select data-filter="kind" aria-label="Görev türü"><option value="">Gündüz + Nöbet</option><option value="day" ${f.kind==='day'?'selected':''}>Gündüz</option><option value="night" ${f.kind==='night'?'selected':''}>Nöbet</option></select><button data-csv>CSV indir</button></div>`;const rows=queryRows(f);html+=`<p>${rows.length} görev · ${rows.reduce((s,r)=>s+r.hours,0)} saat</p>`;html+=area(w,'main','Sorgu sonucu',table(['Tarih','Personel','Birim','Vardiya','Tür','Saat'],rows.map(r=>td([r.date,E(r.name),E(r.unit),E(r.time),r.kind==='day'?'Gündüz':'Nöbet',r.hours]))));break;}
case'units':html+=area(w,'main','Birimler',table(['Birim','Vardiya sayısı'],[...new Set(data.shifts.map(s=>s.unit))].map(u=>td([E(u),data.shifts.filter(s=>s.unit===u).length]))));break;
case'files':html+=area(w,'main','Demo dosyaları',`<div style="max-width:650px;white-space:normal"><p>Bu bölüm yalnızca bağımsız demonun kayıtlarını içerir. Canlı RPYS yedekleri ve imzalı belgeler buraya bağlı değildir.</p><div class="actions"><button data-export>⤓ Demo yedeği indir</button><button data-import>⇧ Demo yedeğini yükle</button><button data-csv>Tüm görevleri CSV indir</button></div><p>JSON yedeğinde demo atamaları, toplam saat düzeltmeleri, tema ve sıralamalar bulunur. Yükleme bu tarayıcıdaki demo kayıtlarının yerine geçer.</p></div>`);break;
case'themes':html+=`<div class="theme-grid">${themes.map(t=>`<button class="theme-card ${data.theme===t[0]?'selected':''}" data-theme="${t[0]}"><div class="theme-preview" style="background:${t[2]};color:${t[3]}"><i></i><i></i><i></i></div><strong>${t[1]}</strong></button>`).join('')}</div><p>Seçimin tüm demo pencerelerine uygulanır ve bu tarayıcıda saklanır.</p>`;break;
case'desktop':html+=`<p>Kısayolu kaldırmak modülü silmez. Tüm modüller Başlat menüsünde kalır.</p><div class="pin-grid">${M.catalog.map(m=>`<label><input type="checkbox" data-pin="${m.id}" ${data.pins.includes(m.id)?'checked':''}> ${E(m.title)}</label>`).join('')}</div>`;break;
case'audit':html+=area(w,'main','Demo işlem geçmişi',table(['Zaman','İşlem'],data.audit.map(a=>td([E(new Date(a.at).toLocaleString('tr-TR')),E(a.text)]))));break;
default:html+=area(w,'preview',w.m.title,`<div style="width:550px;white-space:normal;padding:20px"><div class="preview-symbol">${w.m.icon}</div><h2>Modül yerleşim önizlemesi</h2><p>Bu pencere masaüstü düzenini denemen içindir. ${E(w.m.title)} işlevleri ve canlı RPYS kayıtları henüz bu demoya bağlanmadı.</p><p>Çalışır örnekler: Nöbet Listesi, Saymanlık, Sorgu Merkezi, Vardiyalar, Dosyalar ve Tema.</p><button data-open="nobet">Nöbet örneğini aç</button></div>`);
}w.body.innerHTML=html;w.body.scrollTop=scroll;fitAreas(w);w.body.querySelectorAll('.area').forEach(a=>{const pos=old[a.dataset.area];if(pos){a.querySelector('.area-scroll').scrollLeft=pos[0];a.querySelector('.area-scroll').scrollTop=pos[1];}});}
function queryRows(f={}){return Object.entries(data.assignments).map(([key,pid])=>{const [day,sid]=key.split('|'),s=data.shifts.find(s=>s.id===sid),p=data.people.find(p=>p.id===pid);return {day:+day,date:day+'.10.2026',pid,name:p.name,...s};}).filter(r=>(!f.person||r.pid===f.person)&&(!f.unit||r.unit===f.unit)&&(!f.kind||r.kind===f.kind)).sort((a,b)=>a.day-b.day);}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function onClick(w,e){const b=e.target.closest('button');if(!b)return;if(b.dataset.win){if(b.dataset.win==='close'){w.ro.disconnect();w.el.remove();wins.delete(w.m.id);}else if(b.dataset.win==='min')w.el.hidden=true;else w.el.classList.toggle('max');tasks();fitAreas(w);return;}
if(b.hasAttribute('data-collapse')){const id=b.dataset.collapse,key=w.m.id+':'+id;data.collapsed[key]=!data.collapsed[key];save();render(w);}if(b.dataset.zoom){const id=b.dataset.section,key=w.m.id+':'+id,a=w.body.querySelector(`[data-area="${id}"]`),value=parseInt(a.querySelector('.zoom-value').textContent);w.fit.delete(id);if(b.dataset.zoom==='fit')w.fit.add(id);else data.zoom[key]=b.dataset.zoom==='reset'?100:Math.max(40,Math.min(200,value+(b.dataset.zoom==='plus'?10:-10)));save();fitAreas(w);}
if(b.dataset.shift){data.shifts=M.reorder(data.shifts,b.dataset.shift,+b.dataset.dir);change('Vardiya sırası değiştirildi.');}
if(b.dataset.person){const ids=[...new Set([...(data.payrollOrder||[]),...data.people.map(p=>p.id)])];data.payrollOrder=M.reorder(ids,b.dataset.person,+b.dataset.dir);change('Saymanlık personel sırası değiştirildi.');}
if(b.dataset.reset){delete data.payrollOverrides[b.dataset.reset];change('Toplam saat otomatik hesaba döndürüldü.');}
if(b.dataset.theme){data.theme=b.dataset.theme;applyTheme();save('Tema değiştirildi.');render(w);}
if(b.hasAttribute('data-export'))download('rpys-masaustu-demo-yedek.json',JSON.stringify(data,null,2),'application/json');
if(b.hasAttribute('data-import'))$('#restoreFile').click();
if(b.hasAttribute('data-csv')){const rows=queryRows(w.filters),cell=x=>'"'+String(x).replace(/"/g,'""')+'"';download('rpys-demo-gorevler.csv','\ufeff'+[['Tarih','Personel','Birim','Vardiya','Tür','Saat'],...rows.map(r=>[r.date,r.name,r.unit,r.time,r.kind==='day'?'Gündüz':'Nöbet',r.hours])].map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}}
function onChange(w,e){const t=e.target;if(t.dataset.assignment){const [d,s]=t.dataset.assignment.split('|'),error=M.canAssign(data,+d,s,t.value);if(error){notify(error);render(w);return;}if(t.value)data.assignments[t.dataset.assignment]=t.value;else delete data.assignments[t.dataset.assignment];change(d+' Ekim hücresi güncellendi.');}
if(t.dataset.hours){const value=+t.value;if(t.value===''||!Number.isFinite(value)||value<0||value>744){notify('0–744 arasında saat gir.');render(w);return;}data.payrollOverrides[t.dataset.hours]=value;change('Saymanlık toplam saati güncellendi.');}
if(t.dataset.filter){w.filters[t.dataset.filter]=t.value;render(w);}if(t.dataset.pin){data.pins=t.checked?[...new Set([...data.pins,t.dataset.pin])]:data.pins.filter(id=>id!==t.dataset.pin);save();drawDesktop();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open)open(b.dataset.open);if(b.dataset.unpin){data.pins=data.pins.filter(id=>id!==b.dataset.unpin);save();drawDesktop();notify('Kısayol kaldırıldı. Modül Başlat menüsünde duruyor.');}if(b.dataset.task)focus(wins.get(b.dataset.task));});
$('#startButton').onclick=()=>start($('#startMenu').hidden);$('#closeStart').onclick=()=>start(false);$('#appSearch').oninput=drawStart;$('#themeButton').onclick=()=>open('tema');$('#manageDesktop').onclick=()=>open('menu');$('#filesButton').onclick=()=>open('dosyalar');$('#tileButton').onclick=tile;$('#quickWorkspace').onclick=()=>{open('nobet');open('saymanlik');tile();};$('#showDesktop').onclick=()=>{wins.forEach(w=>w.el.hidden=true);tasks();};document.addEventListener('keydown',e=>{if(e.key==='Escape')start(false);});
$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('Yedek dosyası çok büyük.');const next=M.validate(JSON.parse(await f.text()));if(!confirm('Demo kayıtları bu yedekle değiştirilsin mi? Canlı RPYS etkilenmez.'))return;data=next;applyTheme();drawDesktop();change('Demo yedeği geri yüklendi.');notify('Demo yedeği yüklendi.');}catch(err){notify(err.message);}finally{e.target.value='';}};
function clock(){$('#clock').textContent=new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'});}clock();setInterval(clock,60000);applyTheme();drawDesktop();window.addEventListener('resize',()=>wins.forEach(fitAreas));
})();
