(function(root){
'use strict';
const catalog=[
['dashboard','Genel Bakış','◈','Yönetim','overview'],['nobet','Nöbet Listesi','▦','Planlama','schedule'],['saymanlik','Saymanlık SAY1/SAY2','₺','Hesaplama','payroll'],['personel','Personel','♙','Yönetim','people'],['sorgu','Sorgu Merkezi','⌕','Hesaplama','query'],['vardiyalar','Vardiyalar','◷','Planlama','shifts'],['dosyalar','Dosyalar ve Yedekler','▤','Yönetim','files'],['tema','Tema ve Görünüm','◐','Masaüstü','themes'],
['sorumlu','Sorumlu Paneli','◇','Yönetim'],['gecmis','İşlem Geçmişi','↶','Yönetim','audit'],['yedek','Yedekleme / Geri Al','⤓','Yönetim','files'],['adalet','Adalet Merkezi','⚖','Hesaplama'],['cakisma','Çakışma Merkezi','!','Planlama'],['takvim','Aylık Takvim','▦','Planlama'],['asistan','RPYS Asistanı','✧','Yönetim'],['goruntuler','Liste Görüntüleri','▣','Belgeler'],['birimler','Birimler','⊞','Yönetim','units'],['netistat','Net İstatistikler','▥','Hesaplama','query'],['fiilihizmet','Fiilî Hizmet','☢','Hesaplama'],['simulasyon','Simülasyon / Tahmin','⌁','Planlama'],['siralamalar','Sıralamalar','≡','Hesaplama','query'],['karne','Personel Karnesi','♙','Hesaplama','query'],['izin','İzin / Rapor','☂','Planlama'],['yillikizin','Yıllık İzin Planı','▦','Planlama'],['excel','Excel İçe Aktar','⇧','Belgeler'],['dogrulama','Geçmiş Veri Doğrulama','✓','Hesaplama'],['kullanicilar','Kullanıcı Yönetimi','♧','Yönetim'],['yonetim','Yönetim Merkezi','◈','Yönetim'],['grafikler','Grafik Merkezi','▥','Hesaplama','query'],['tahmin','Tahmin Merkezi','⌁','Hesaplama'],['denetim','Denetim Modu','✓','Yönetim'],['planlama','Planlama Takvimi','▦','Planlama'],['rapor','Rapor Merkezi','▤','Belgeler','query'],['kalite','Veri Kalite Merkezi','✓','Yönetim'],['saglik','Sistem Sağlığı','♡','Yönetim'],['sua','ŞUA Puan ve Hakediş','☢','Hesaplama'],['yazdir','Yazdırma Merkezi','▤','Belgeler'],['motor','Akıllı Nöbet Motoru','⚙','Planlama'],['ayarplan','Planlama Ayarları','⚙','Planlama'],['final','Final Kontrol Merkezi','✓','Planlama'],['ayar','Genel Ayarlar','⚙','Yönetim'],['menu','Menü Düzeni','⊞','Masaüstü','desktop'],['sds','SDS / STD','▤','Belgeler']
].map(([id,title,icon,group,view])=>({id,title,icon,group,view:view||'preview'}));
const clone=x=>JSON.parse(JSON.stringify(x));
function seed(){
 const people=Array.from({length:12},(_,i)=>({id:'p'+(i+1),name:'Örnek Tekniker '+String(i+1).padStart(2,'0'),active:true,required:154}));
 const shifts=[{id:'pol1',unit:'Poliklinik Röntgen',time:'08:00–15:00',hours:7,kind:'day',cat:'pol'},{id:'pol2',unit:'Poliklinik Röntgen',time:'10:00–17:00',hours:7,kind:'day',cat:'pol'},{id:'bt',unit:'BT',time:'08:00–ertesi 07:00',hours:23,kind:'night',cat:'acil'},{id:'acil',unit:'Acil Röntgen',time:'10:00–ertesi 08:00',hours:22,kind:'night',cat:'acil'},{id:'skg',unit:'Skopi',time:'08:00–16:00',hours:8,kind:'day',cat:'acil'},{id:'skn',unit:'Skopi',time:'08:00–ertesi 08:00',hours:24,kind:'night',cat:'acil'}];
 const assignments={};for(let d=1;d<=31;d++){shifts.forEach((s,i)=>assignments[d+'|'+s.id]='p'+(((d%2)*6+i)%12+1));}
 return {schema:1,month:'2026-10',people,shifts,assignments,payrollOverrides:{},pins:catalog.map(m=>m.id),theme:'ocean',zoom:{},collapsed:{},audit:[],notes:{}};
}
function reorder(items,id,direction){const out=items.slice(),i=out.findIndex(x=>(typeof x==='string'?x:x.id)===id),j=i+direction;if(i>=0&&j>=0&&j<out.length)[out[i],out[j]]=[out[j],out[i]];return out;}
function totals(data,pid){let day=0,night=0,pol=0,acil=0;for(const [key,id] of Object.entries(data.assignments)){if(id!==pid)continue;const s=data.shifts.find(s=>s.id===key.split('|')[1]);if(!s)continue;s.kind==='night'?night++:day++;s.cat==='pol'?pol+=s.hours:acil+=s.hours;}return {day,night,pol,acil,hours:pol+acil};}
function dayHours(data,pid,day,exclude){return data.shifts.reduce((sum,s)=>sum+(day+'|'+s.id!==exclude&&data.assignments[day+'|'+s.id]===pid?s.hours:0),0);}
function canAssign(data,day,shift,pid){if(!pid)return '';if(!data.people.some(p=>p.id===pid&&p.active))return 'Personel aktif değil.';if(dayHours(data,pid,day-1)>=16)return 'Önceki gün 16 saat ve üzeri çalıştı; ertesi gün atanamaz.';if(dayHours(data,pid,day,day+'|'+shift)>0)return 'Bu örnek listede aynı güne ikinci görev atanamaz.';const s=data.shifts.find(s=>s.id===shift);if(s?.hours>=16&&dayHours(data,pid,day+1)>0)return 'Ertesi gün görevi var; 16 saat ve üzeri görev atanamaz.';return '';}
function validate(x){if(!x||x.schema!==1||x.month!=='2026-10'||!Array.isArray(x.people)||!x.people.length||x.people.length>100||!Array.isArray(x.shifts)||!x.shifts.length||x.shifts.length>40)throw Error('Geçerli bir masaüstü demo yedeği seç.');
 const p=new Set(),s=new Set();for(const a of x.people){if(!/^p\d+$/.test(a.id)||p.has(a.id)||typeof a.name!=='string'||a.name.length>100||!Number.isFinite(a.required)||a.required<0)throw Error('Personel kaydı geçersiz.');p.add(a.id);}
 for(const a of x.shifts){if(!/^[a-z0-9]+$/i.test(a.id)||s.has(a.id)||typeof a.unit!=='string'||typeof a.time!=='string'||!Number.isFinite(a.hours)||a.hours<0||a.hours>24||!['day','night'].includes(a.kind)||!['pol','acil'].includes(a.cat))throw Error('Vardiya kaydı geçersiz.');s.add(a.id);}
 if(!x.assignments||typeof x.assignments!=='object'||Array.isArray(x.assignments))throw Error('Liste kaydı geçersiz.');for(const [k,v]of Object.entries(x.assignments)){const [day,id]=k.split('|');if(!/^\d{1,2}\|[a-z0-9]+$/i.test(k)||+day<1||+day>31||!s.has(id)||!p.has(v))throw Error('Atama kaydı geçersiz.');}
 const base=seed(),out={schema:1,month:x.month,people:clone(x.people),shifts:clone(x.shifts),assignments:clone(x.assignments),pins:Array.isArray(x.pins)?[...new Set(x.pins.filter(id=>catalog.some(m=>m.id===id)))]:base.pins,theme:['ocean','midnight','graphite','ivory','forest','contrast'].includes(x.theme)?x.theme:'ocean',zoom:{},collapsed:{},payrollOverrides:{},audit:[],notes:{},payrollOrder:[]};
 for(const [id,v]of Object.entries(x.payrollOverrides||{}))if(p.has(id)&&Number.isFinite(v)&&v>=0&&v<=744)out.payrollOverrides[id]=v;
 out.payrollOrder=[...new Set([...(Array.isArray(x.payrollOrder)?x.payrollOrder.filter(id=>p.has(id)):[]),...p])];
 for(const [key,v]of Object.entries(x.zoom||{}))if(/^[a-z]+:[a-z]+$/.test(key)&&Number.isFinite(v)&&v>=40&&v<=200)out.zoom[key]=v;
 for(const [key,v]of Object.entries(x.collapsed||{}))if(/^[a-z]+:[a-z]+$/.test(key)&&typeof v==='boolean')out.collapsed[key]=v;
 out.audit=Array.isArray(x.audit)?x.audit.filter(a=>a&&typeof a.at==='string'&&typeof a.text==='string').slice(0,100):[];return out;
}

function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const api={catalog,seed,clone,reorder,totals,canAssign,validate,escape};if(typeof module!=='undefined')module.exports=api;else root.RPYSDesktopModel=api;
})(typeof window!=='undefined'?window:globalThis);
