'use strict';
(()=>{
const $=s=>document.querySelector(s),Q=window.YeaHistoryQuery,P=window.YeaHistoryParser,B=window.YeaHistoryBridge;
if(!Q||!P||!B)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:2});
const page=$('[data-page="history"]');let report=null,order={key:'totalHours',dir:-1},pageNo=0,detailPage=0;
const cols=[['label','Grup'],['dayCount','Gündüz'],['nightCount','Nöbet'],['totalCount','Görev'],['workedDays','Çalışılan gün'],['dayHours','Gündüz saat'],['nightHours','Nöbet saat'],['totalHours','Toplam saat'],['unknownHours','Saati eksik']];
function options(arr){return arr.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');}
function select(id,label,arr){return `<label>${label}<select id="${id}">${options(arr)}</select></label>`;}
function input(id,label,type='text'){return `<label>${label}<input id="${id}" type="${type}" ${type==='number'?'min="0" max="48" step="0.5"':''}></label>`;}
const themeOptions=[['system','Cihaz teması'],['dark','Koyu lacivert'],['light','Açık'],['contrast','Yüksek kontrast']];
const themeBar=document.createElement('div');themeBar.className='hpThemeBar';themeBar.innerHTML=select('hpTheme','Görünüm',themeOptions);$('#authView')?.prepend(themeBar);
const inTheme=document.createElement('div');inTheme.className='hpThemeBar';inTheme.innerHTML=select('hpAppTheme','Tema',themeOptions);page.prepend(inTheme);
const media=matchMedia('(prefers-color-scheme: dark)');let selectedTheme='system';try{selectedTheme=localStorage.getItem('yea_accessible_theme_v1')||'system';}catch{}
function applyTheme(value){if(!themeOptions.some(x=>x[0]===value))value='system';selectedTheme=value;document.documentElement.dataset.yeaTheme=value==='system'?(media.matches?'dark':'light'):value;['#hpTheme','#hpAppTheme'].forEach(id=>$(id).value=value);try{localStorage.setItem('yea_accessible_theme_v1',value);}catch{}}
applyTheme(selectedTheme);$('#hpTheme').onchange=e=>applyTheme(e.target.value);$('#hpAppTheme').onchange=e=>applyTheme(e.target.value);media.addEventListener('change',()=>{if(selectedTheme==='system')applyTheme('system');});
$('.v17Hero h2').textContent='Geçmiş İstatistik · Sorgu Merkezi';$('.v17Hero p').textContent='Arşivini sorgula, dönemleri karşılaştır, sonuçların kaynak hücresine kadar izle.';
const panel=$('#histPeopleBody').closest('.panel');panel.id='hpReportPanel';
panel.insertAdjacentHTML('afterbegin',`<details open class="hpQuery"><summary>Ayrıntılı sorgu</summary><div class="hpFields">${input('hpText','Serbest arama')}${input('hpStart','Başlangıç','date')}${input('hpEnd','Bitiş','date')}${select('hpUnit','Birim',[['','Tüm birimler']])}${select('hpCategory','Görev türü',[['','Gündüz + nöbet'],['day','Gündüz'],['night','Nöbet']])}${select('hpSource','Kaynak dosya',[['','Tüm dosyalar']])}${select('hpWeekday','Gün türü',[['','Tüm günler'],['weekday','Hafta içi'],['weekend','Hafta sonu']])}${input('hpMin','En az saat','number')}${input('hpMax','En fazla saat','number')}${select('hpHours','Saat bilgisi',[['','Tümü'],['known','Saati bilinen'],['unknown','Saati eksik']])}${select('hpGroup','Gruplama',[['person','Personel'],['unit','Birim'],['month','Ay'],['year','Yıl'],['personMonth','Personel × ay']])}${select('hpPolicy','Çakışan kayıtlar',[['review','İncelenene kadar sayma'],['largest','En yüksek saatli olanı say'],['all','Farklı vardiyaların hepsini say']])}</div><div class="formActions"><button id="hpReset" type="button">Filtreleri sıfırla</button><button id="hpRefresh" type="button">Arşivi yenile</button><button id="hpSaveQuery" type="button">Sorguyu kaydet</button><button id="hpPrint" type="button">PDF / Yazdır önizleme</button></div><div class="hpSaved">${input('hpQueryName','Sorgu adı')}${select('hpQueries','Kayıtlı sorgular',[['','Seçiniz']])}<button type="button" id="hpLoadQuery">Uygula</button></div><div id="hpStatus" role="status" aria-live="polite"></div></details><div id="hpKpis" class="hpKpis"></div>`);
$('#histPeopleBody').closest('table').querySelector('thead').innerHTML='<tr>'+cols.map(([k,label])=>`<th aria-sort="none"><button type="button" data-hp-sort="${k}">${label} ↕</button></th>`).join('')+'</tr>';
$('#histPeopleBody').closest('.tablewrap').insertAdjacentHTML('afterend','<div class="hpPager"><button id="hpPrev" type="button">← Önceki</button><span id="hpPaging"></span><button id="hpNext" type="button">Sonraki →</button></div>');
panel.insertAdjacentHTML('beforeend',`<details open><summary>Önceki yıl karşılaştırması</summary><p>Seçili yıl veya tarih aralığı bir yıl geriye taşınır. Eksik arşiv ayları çalışılmadığı anlamına gelmez.</p><div id="hpCompare"></div></details><details open><summary>Birim dağılımı</summary><div id="hpUnits" class="hpUnitList"></div></details><details><summary>Kaynak kayıtları ve doğrulama</summary><div id="hpQuality"></div><div class="tablewrap"><table class="v17Table"><thead><tr><th>Tarih</th><th>Personel</th><th>Birim</th><th>Vardiya</th><th>Saat</th><th>Dosya / Sayfa / Hücre</th></tr></thead><tbody id="hpDetails"></tbody></table></div><div class="hpPager"><button id="hpDetailPrev" type="button">← Önceki</button><span id="hpDetailPaging"></span><button id="hpDetailNext" type="button">Sonraki →</button></div><h3>Çakışan kayıtlar</h3><div id="hpIssues" class="tablewrap"></div></details>`);
const map={text:'hpText',start:'hpStart',end:'hpEnd',unit:'hpUnit',category:'hpCategory',source:'hpSource',weekday:'hpWeekday',min:'hpMin',max:'hpMax',hours:'hpHours',group:'hpGroup',policy:'hpPolicy',person:'histPersonFilter',year:'histYearFilter',month:'histMonthFilter'};
function filters(){return Object.fromEntries(Object.entries(map).map(([k,id])=>[k,$('#'+id).value]));}
function refreshOptions(id,values,label){const e=$('#'+id),old=e.value;e.innerHTML=options([['',label],...values]);e.value=values.some(x=>x[0]===old)?old:'';}
function queryKey(){return 'yea_history_queries_v1_'+B.snapshot().userId;}
function saved(){try{const data=JSON.parse(localStorage.getItem(queryKey())||'[]');return Array.isArray(data)?data.filter(x=>x&&typeof x.name==='string'&&x.filters&&typeof x.filters==='object'):[];}catch{return [];}}
function savedOptions(){refreshOptions('hpQueries',saved().map((x,i)=>[String(i),x.name]),'Seçiniz');}
function status(text){$('#hpStatus').textContent=text;}
function render(){
 const data=B.snapshot();refreshOptions('hpUnit',[...new Set(data.records.map(r=>P.canonicalUnit(r.unit)))].sort((a,b)=>a.localeCompare(b,'tr')).map(u=>[u,u]),'Tüm birimler');refreshOptions('hpSource',data.imports.map(i=>[i.id,i.file_name]),'Tüm dosyalar');savedOptions();
 const f=filters();if(f.start&&f.end&&f.start>f.end||f.min!==''&&f.max!==''&&+f.min>+f.max){status('Aralık hatalı: başlangıç/alt sınır, bitiş/üst sınırdan büyük olamaz.');report=null;window.__YEA_HISTORY_REPORT=null;$('#histPeopleBody').innerHTML='<tr><td colspan="9">Sorgu aralığını düzeltin.</td></tr>';['hpKpis','hpCompare','hpUnits','hpDetails','hpIssues','histMonthsBody','histReportInfo','hpPaging','hpDetailPaging'].forEach(id=>$('#'+id).innerHTML='');return;}
 status('');report=Q.run(data.records,data.rules,f,P);const t=report.totals;
 $('#hpKpis').innerHTML=[['Görev',t.totalCount],['Gündüz',t.dayCount],['Nöbet',t.nightCount],['Toplam saat',t.totalHours],['Personel',report.people],['Saati eksik',t.unknownHours]].map(([l,v])=>`<article><small>${l}</small><strong>${num(v)}</strong></article>`).join('');
 $('#histRecordCount').textContent=num(Q.prepare(data.records,data.rules,P,f.policy).records.filter(r=>r.category!=='exclude').length);
 $('#histReportInfo').textContent=`${report.groups.length} grup · ${report.records.length} görev · ${report.duplicates} birebir tekrar çıkarıldı · ${report.issues.length} çakışan kayıt · ${report.excluded} hariç · ${report.invalid} geçersiz. Saat toplamı yalnız bilinen saatleri içerir. Görev sayısı ile çalışılan takvim günü farklıdır.`;
 renderGroups();renderDetails();$('#histMonthsBody').innerHTML=report.months.map(x=>`<tr><td>${esc(x.label)}</td><td>Tüm seçili personel</td><td>${num(x.dayCount)}</td><td>${num(x.nightCount)}</td><td>${num(x.totalCount)}</td><td>${num(x.totalHours)}</td></tr>`).join('')||'<tr><td colspan="6">Bu sorguda aylık kayıt yok.</td></tr>';
 $('#hpUnits').innerHTML=report.units.sort((a,b)=>b.totalHours-a.totalHours).map(x=>`<div><b>${esc(x.label)}</b><span>${num(x.totalCount)} görev · ${num(x.totalHours)} saat</span></div>`).join('')||'Kayıt yok.';
 $('#hpQuality').textContent=`Doğrulama kapsamı: ${f.source?'seçili dosya':'tüm arşiv'}. ${report.rawCount} ham kayıt; ${report.duplicates} birebir tekrar; ${report.invalid} geçersiz tarih/kişi. ${report.issues.length} çakışan kayıt. Varsayılan sorgu çakışmaları saymaz. Dosyalarınız değiştirilmez.`;
 $('#hpIssues').innerHTML=report.issues.length?'<table class="v17Table"><thead><tr><th>Tarih</th><th>Personel</th><th>Birim</th><th>Vardiya</th><th>Saat</th><th>Kaynak</th></tr></thead><tbody>'+report.issues.slice(0,200).map(r=>`<tr>${[r.date,r.person,r.unit,r.shift,r.hours,r.fileName].map(v=>'<td>'+esc(v)+'</td>').join('')}</tr>`).join('')+'</tbody></table>'+`<p>İlk ${Math.min(200,report.issues.length)} kayıt gösteriliyor. Excel çıktısı tamamını içerir.</p>`:'Çakışma bulunmadı.';
 if(!f.year&&!f.start&&!f.end)$('#hpCompare').textContent='Karşılaştırma için yıl veya tarih aralığı seçin.';
 else{const prev=Q.run(data.records,data.rules,Q.previousYear(f),P),delta=t.totalHours-prev.totals.totalHours;$('#hpCompare').innerHTML=`<div class="hpCompare"><span>Seçili dönem: <b>${num(t.totalHours)} saat / ${num(t.totalCount)} görev</b></span><span>Önceki yıl: <b>${num(prev.totals.totalHours)} saat / ${num(prev.totals.totalCount)} görev</b></span><span>Fark: <b>${delta>=0?'+':''}${num(delta)} saat${prev.totals.totalHours?' (%'+num(delta/prev.totals.totalHours*100)+')':''}</b></span></div><p>${!prev.records.length?'Önceki dönemde veri yok; yüzde hesaplanmadı.':`Kayıt bulunan ay sayısı: ${report.months.length} / ${prev.months.length}. Karşılaştırma yalnız yüklenen verileri kapsar.`}</p>`;}
 window.__YEA_HISTORY_REPORT={groups:report.groups,months:report.months,filters:f,generatedAt:new Date().toISOString()};
}
function sorted(){return [...report.groups].sort((a,b)=>order.dir*(typeof a[order.key]==='number'?a[order.key]-b[order.key]:String(a[order.key]).localeCompare(String(b[order.key]),'tr'))||a.label.localeCompare(b.label,'tr'));}
function renderGroups(){if(!report)return;const rows=sorted(),count=Math.max(1,Math.ceil(rows.length/50));pageNo=Math.min(pageNo,count-1);$('#histPeopleBody').innerHTML=rows.slice(pageNo*50,pageNo*50+50).map(x=>'<tr>'+cols.map(([k])=>'<td>'+esc(typeof x[k]==='number'?num(x[k]):x[k])+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="9">Bu sorguda kayıt yok.</td></tr>';$('#hpPaging').textContent=`${pageNo+1} / ${count} · ${rows.length} grup`;$('#hpPrev').disabled=!pageNo;$('#hpNext').disabled=pageNo>=count-1;panel.querySelectorAll('[data-hp-sort]').forEach(b=>b.closest('th').setAttribute('aria-sort',b.dataset.hpSort===order.key?(order.dir===1?'ascending':'descending'):'none'));}
function source(r){return (r.sources||[r]).map(s=>[s.fileName,s.sheet,s.row?'Satır '+s.row:'',s.col?'Sütun '+s.col:''].filter(Boolean).join(' / ')).join(' • ');}
function renderDetails(){if(!report)return;const count=Math.max(1,Math.ceil(report.records.length/100));detailPage=Math.min(detailPage,count-1);$('#hpDetails').innerHTML=report.records.slice(detailPage*100,detailPage*100+100).map(r=>'<tr>'+[r.date,r.person,r.unit,r.shift,r.hours?num(r.hours):'Bilinmiyor',source(r)].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="6">Kayıt yok.</td></tr>';$('#hpDetailPaging').textContent=`${detailPage+1} / ${count} · ${report.records.length} kayıt`;$('#hpDetailPrev').disabled=!detailPage;$('#hpDetailNext').disabled=detailPage>=count-1;}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function exportReport(kind){if(!report)return status('Önce geçerli bir sorgu oluşturun.');const rows=[cols.map(x=>x[1]),...sorted().map(r=>cols.map(([k])=>r[k]))];if(kind==='csv'){download('YEA_Sorgu.csv',new Blob([Q.csv(rows)],{type:'text/csv;charset=utf-8'}));return;}
 if(!window.XLSX)return status('Excel bileşeni yüklenemedi. CSV kullanabilirsiniz.');const wb=XLSX.utils.book_new();const sheet=(name,data)=>{const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=data[0].map(()=>({wch:24}));XLSX.utils.book_append_sheet(wb,ws,name);};sheet('Sorgu sonucu',rows);sheet('Kaynak kayıtları',[['Tarih','Personel','Birim','Vardiya','Saat','Kaynak'],...report.records.map(r=>[r.date,r.person,r.unit,r.shift,r.hours||null,source(r)])]);sheet('Çakışmalar',[['Tarih','Personel','Birim','Vardiya','Saat','Kaynak'],...report.issues.map(r=>[r.date,r.person,r.unit,r.shift,r.hours||null,source(r)])]);sheet('Sorgu bilgisi',[['Ölçüt','Değer'],...Object.entries(filters()),['Oluşturulma',new Date().toLocaleString('tr-TR')],['Uyarı','Saati bilinmeyen kayıtlar saat toplamına eklenmez; çakışma politikası sorgu bilgisi içindedir.']]);XLSX.writeFile(wb,'YEA_Sorgu.xlsx');}
['histExportCsv','histExportXlsx'].forEach(id=>{const old=$('#'+id),b=old.cloneNode(true);old.replaceWith(b);b.addEventListener('click',()=>exportReport(id.endsWith('Csv')?'csv':'xlsx'));});
Object.values(map).forEach(id=>$('#'+id).addEventListener('change',()=>{pageNo=0;detailPage=0;render();}));let timer;$('#hpText').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{pageNo=0;detailPage=0;render();},220);});
panel.addEventListener('click',e=>{const b=e.target.closest('[data-hp-sort]');if(b){order={key:b.dataset.hpSort,dir:order.key===b.dataset.hpSort?-order.dir:1};renderGroups();}});
$('#hpPrev').onclick=()=>{pageNo--;renderGroups();};$('#hpNext').onclick=()=>{pageNo++;renderGroups();};$('#hpDetailPrev').onclick=()=>{detailPage--;renderDetails();};$('#hpDetailNext').onclick=()=>{detailPage++;renderDetails();};
$('#hpReset').onclick=()=>{Object.values(map).forEach(id=>$('#'+id).value='');$('#hpGroup').value='person';$('#hpPolicy').value='review';pageNo=detailPage=0;render();};$('#hpRefresh').onclick=()=>B.refresh();
$('#hpSaveQuery').onclick=()=>{const name=$('#hpQueryName').value.trim().slice(0,80);if(!name)return status('Sorguya bir ad yazın.');try{const items=saved().filter(x=>x.name!==name);items.push({name,filters:filters()});localStorage.setItem(queryKey(),JSON.stringify(items.slice(-30)));savedOptions();status('Sorgu bu cihazda, hesabınıza özel kaydedildi.');}catch{status('Cihaza kaydedilemedi.');}};
$('#hpLoadQuery').onclick=()=>{const item=saved()[$('#hpQueries').value];if(!item)return;Object.entries(map).forEach(([k,id])=>$('#'+id).value=item.filters[k]||'');pageNo=detailPage=0;render();};
$('#hpPrint').onclick=()=>{if(!report)return;$('#hpPrintPreview')?.remove();const box=document.createElement('dialog');box.id='hpPrintPreview';box.innerHTML=`<div class="hpPrintActions"><button id="hpPrintNow">Yazdır / PDF olarak kaydet</button><button id="hpPrintClose">Kapat</button></div><h1>YEA · Geçmiş İstatistik Raporu</h1><p>${esc(new Date().toLocaleString('tr-TR'))}</p><p>${esc(Object.entries(filters()).filter(([,v])=>v!=='').map(([k,v])=>k+': '+v).join(' · '))}</p><p>${esc($('#histReportInfo').textContent)}</p><p>Toplam: ${num(report.totals.totalCount)} görev · ${num(report.totals.totalHours)} saat. Saati bilinmeyen kayıtlar saat toplamına dahil değildir.</p><table><thead><tr>${cols.map(([,l])=>'<th>'+l+'</th>').join('')}</tr></thead><tbody>${sorted().map(r=>'<tr>'+cols.map(([k])=>'<td>'+esc(r[k])+'</td>').join('')+'</tr>').join('')}</tbody></table>`;document.body.append(box);$('#hpPrintClose').onclick=()=>box.close();$('#hpPrintNow').onclick=()=>window.print();box.showModal();};
let visible=false;
const observer=new MutationObserver(()=>{const next=!page.classList.contains('hidden')&&!$('#appView')?.classList.contains('hidden');if(next&&!visible)B.refresh();visible=next;});
observer.observe(page,{attributes:true,attributeFilter:['class']});observer.observe($('#appView'),{attributes:true,attributeFilter:['class']});
window.YeaHistoryPro={render};render();
})();
