'use strict';
const SUPA='https://bjieodqaujiqhnfxqgei.supabase.co';
const KEY='sb_publishable_W9B0WfrlpEh-MnjNEuzECw_3-a5dCPT';
const STORE='yea_suite_session_v1';
const RAD_UNITS=['Poliklinik Röntgen','Acil Röntgen','BT','Skopi','Portable','Mamografi','DEXA','USG'];
let session=null,tasks=[],drafts=[],projects=[],radiology=[],editingDraftId=null,editingProjectId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const enc=new TextEncoder();
function showMsg(where,text){const e=$(where);if(!e)return;if(!text){e.classList.add('hidden');e.textContent='';return}e.textContent=text;e.classList.remove('hidden')}
function saveSession(s){session=s;if(s)localStorage.setItem(STORE,JSON.stringify(s));else localStorage.removeItem(STORE)}
function loadSession(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtDate(v){if(!v)return 'Tarih yok';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('tr-TR',{dateStyle:'short',timeStyle:v.includes?.('T')?'short':undefined})}
function todayISO(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function currentMonth(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function monthDate(m){return m+'-01'}
function prevMonth(m){const [y,mo]=m.split('-').map(Number);const d=new Date(y,mo-2,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function bytesLabel(b){b=Number(b||0);return b<1024?b+' B':b<1024*1024?(b/1024).toFixed(1)+' KB':(b/1024/1024).toFixed(2)+' MB'}
function priorityName(p){return Number(p)===1?'Yüksek':Number(p)===3?'Düşük':'Normal'}
function projectStatusName(s){return ({active:'Aktif',paused:'Beklemede',done:'Tamamlandı',archived:'Arşiv'})[s]||s}
function categoryName(c){return ({work:'İş',personal:'Kişisel',software:'Yazılım',vehicle:'Araç',education:'Eğitim',other:'Diğer'})[c]||c}
async function authFetch(path,opts={}){return fetch(SUPA+path,{...opts,headers:{apikey:KEY,'Content-Type':'application/json',...(opts.headers||{})}})}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await authFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){saveSession(null);return false}const d=await r.json();saveSession({...d,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)});return true}
async function ensureSession(){session=loadSession();if(!session)return false;const expires=Number(session.expires_at||0);if(expires&&expires<Math.floor(Date.now()/1000)+60)return refreshSession();return true}
async function api(path,opts={}){if(!session)throw new Error('Oturum yok.');const make=()=>{const headers={apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',...(opts.headers||{})};if(!headers.Prefer&&!headers.prefer)headers.Prefer='return=representation';return fetch(SUPA+path,{...opts,headers})};let r=await make();if(r.status===401&&await refreshSession())r=await make();if(!r.ok){let m='İşlem başarısız.';try{const j=await r.json();m=j.message||j.error_description||j.error||j.hint||m}catch{}throw new Error(m)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function sign(mode){showMsg('#authMsg','');const email=$('#email').value.trim(),password=$('#password').value;if(password.length<8){showMsg('#authMsg','Şifre en az 8 karakter olmalı.');return}const path=mode==='in'?'/auth/v1/token?grant_type=password':'/auth/v1/signup';const r=await authFetch(path,{method:'POST',body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok){showMsg('#authMsg',d.error_description||d.msg||d.message||'Giriş başarısız.');return}if(mode==='up'&&!d.access_token){showMsg('#authMsg','Hesap oluşturuldu. E-posta doğrulaması açıksa gelen kutunu kontrol et.');return}saveSession({...d,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)});await enterApp()}
async function enterApp(){session=loadSession();$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');if(!$('#radViewMonth').value)$('#radViewMonth').value=currentMonth();await refreshData()}
function isOverdue(t){return t.status!=='done'&&t.due_at&&new Date(t.due_at)<new Date()}
function isToday(t){if(!t.due_at)return false;const d=new Date(t.due_at);return d.getFullYear()===new Date().getFullYear()&&d.getMonth()===new Date().getMonth()&&d.getDate()===new Date().getDate()}
function renderTasks(){const el=$('#taskList');if(!tasks.length){el.innerHTML='<div class="empty">Henüz görev yok.</div>';return}el.innerHTML=tasks.map(t=>{const overdue=isOverdue(t);const cls=Number(t.priority)===1?'high':Number(t.priority)===3?'low':'';return `<article class="taskItem"><div class="itemTop"><div><div class="itemTitle ${t.status==='done'?'done':''}">${escapeHtml(t.title)}</div><div class="itemMeta"><span class="badge ${cls}">${priorityName(t.priority)}</span>${t.due_at?`<span class="badge ${overdue?'overdue':''}">${overdue?'Gecikti • ':''}${fmtDate(t.due_at)}</span>`:''}<span>${t.status==='done'?'Tamamlandı':'Açık'}</span></div></div></div>${t.notes?`<div class="noteLine">${escapeHtml(t.notes)}</div>`:''}<div class="itemActions"><button data-task-toggle="${t.id}">${t.status==='done'?'Geri Aç':'Tamamla'}</button><button data-task-archive="${t.id}">Arşivle</button></div></article>`}).join('')}
function renderDrafts(){const el=$('#draftList');if(!drafts.length){el.innerHTML='<div class="empty">Henüz belge taslağı yok.</div>';return}el.innerHTML=drafts.map(d=>`<article class="draft"><div class="itemTop"><div><div class="itemTitle">${escapeHtml(d.title)}</div><div class="itemMeta"><span>${escapeHtml(d.document_type||'other')}</span><span>${fmtDate(d.updated_at)}</span></div></div></div><div class="itemActions"><button data-draft-edit="${d.id}">Düzenle</button><button data-draft-delete="${d.id}">Sil</button></div></article>`).join('')}
function renderProjects(){const el=$('#projectList');const visible=projects.filter(p=>p.status!=='archived');if(!visible.length){el.innerHTML='<div class="empty">Henüz proje yok.</div>';return}el.innerHTML=visible.map(p=>{const due=p.due_date?new Date(p.due_date+'T23:59:59'):null;const overdue=p.status!=='done'&&due&&due<new Date();return `<article class="projectItem"><div class="itemTop"><div><div class="itemTitle ${p.status==='done'?'done':''}">${escapeHtml(p.title)}</div><div class="itemMeta"><span class="badge ${p.status==='active'?'active':p.status==='paused'?'paused':p.status==='done'?'doneBadge':''}">${projectStatusName(p.status)}</span><span>${categoryName(p.category)}</span>${p.due_date?`<span class="badge ${overdue?'overdue':''}">${overdue?'Gecikti • ':''}${escapeHtml(p.due_date)}</span>`:''}<span>%${Number(p.progress||0)}</span></div></div></div><div class="progress"><span style="width:${Math.min(100,Math.max(0,Number(p.progress||0)))}%"></span></div>${p.next_action?`<div class="projectNext"><b>Sonraki adım:</b> ${escapeHtml(p.next_action)}</div>`:''}<div class="itemActions"><button data-project-plus="${p.id}">+10%</button><button data-project-toggle="${p.id}">${p.status==='paused'?'Devam Et':'Beklet'}</button><button data-project-done="${p.id}">Tamamla</button><button data-project-edit="${p.id}">Düzenle</button><button data-project-archive="${p.id}">Arşivle</button></div></article>`}).join('')}
function selectedRadMonth(){return $('#radViewMonth').value||currentMonth()}
function radRows(month=selectedRadMonth()){return radiology.filter(r=>String(r.period).slice(0,7)===month).sort((a,b)=>RAD_UNITS.indexOf(a.unit)-RAD_UNITS.indexOf(b.unit))}
function radTotals(month=selectedRadMonth()){const rows=radRows(month);return {rows,patients:rows.reduce((s,r)=>s+Number(r.patient_count||0),0),requests:rows.reduce((s,r)=>s+Number(r.request_count||0),0),outage:rows.reduce((s,r)=>s+Number(r.outage_days||0),0)}}
function renderRadiology(){const t=radTotals();$('#radPatients').textContent=t.patients.toLocaleString('tr-TR');$('#radRequests').textContent=t.requests.toLocaleString('tr-TR');$('#radOutage').textContent=t.outage.toLocaleString('tr-TR');$('#radFilled').textContent=t.rows.length+'/8';const prev=radTotals(prevMonth(selectedRadMonth()));let trend='Önceki ay verisi yok.';if(prev.rows.length){const reqDiff=t.requests-prev.requests;const pct=prev.requests?((reqDiff/prev.requests)*100):0;trend=`Önceki aya göre istem: ${reqDiff>=0?'+':''}${reqDiff.toLocaleString('tr-TR')} (${pct>=0?'+':''}${pct.toFixed(1)}%). Hasta: ${t.patients.toLocaleString('tr-TR')} / önceki ${prev.patients.toLocaleString('tr-TR')}.`}$('#radTrend').textContent=trend;const el=$('#radiologyList');if(!t.rows.length){el.innerHTML='<div class="empty">Bu ay için henüz radyoloji verisi yok.</div>';return}el.innerHTML=t.rows.map(r=>`<article class="radItem"><div class="radRow"><div class="itemTitle">${escapeHtml(r.unit)}</div><div class="radValue"><span class="tiny">Hasta</span><br><b>${Number(r.patient_count||0).toLocaleString('tr-TR')}</b></div><div class="radValue"><span class="tiny">İstem</span><br><b>${Number(r.request_count||0).toLocaleString('tr-TR')}</b></div><div class="radValue"><span class="tiny">Kesinti</span><br><b>${Number(r.outage_days||0).toLocaleString('tr-TR')} gün</b></div></div>${r.note?`<div class="noteLine">${escapeHtml(r.note)}</div>`:''}<div class="itemActions"><button data-rad-load="${r.id}">Forma Al</button><button data-rad-delete="${r.id}">Sil</button></div></article>`).join('')}
function renderHome(){const open=tasks.filter(t=>t.status!=='done').length;const today=tasks.filter(t=>t.status!=='done'&&isToday(t)).length;const active=projects.filter(p=>p.status==='active').length;const monthReq=radTotals(currentMonth()).requests;$('#openCount').textContent=open;$('#todayCount').textContent=today;$('#projectCount').textContent=active;$('#monthRequestCount').textContent=monthReq.toLocaleString('tr-TR')}
function renderAll(){renderTasks();renderDrafts();renderProjects();renderRadiology();renderHome()}
async function refreshData(){try{showMsg('#appMsg','');const [t,d,p,r,u]=await Promise.all([api('/rest/v1/yea_tasks?select=id,title,notes,status,due_at,priority,created_at,updated_at&status=neq.archived&order=priority.asc,due_at.asc.nullslast,created_at.desc&limit=150'),api('/rest/v1/yea_document_drafts?select=id,title,document_type,content,updated_at&order=updated_at.desc&limit=120'),api('/rest/v1/yea_projects?select=id,title,category,status,progress,next_action,due_date,created_at,updated_at&order=updated_at.desc&limit=120'),api('/rest/v1/yea_radiology_metrics?select=id,period,unit,patient_count,request_count,outage_days,note,updated_at&order=period.desc,unit.asc&limit=240'),api('/rest/v1/rpc/yea_my_usage_v2',{method:'POST',body:'{}'})]);tasks=t||[];drafts=d||[];projects=p||[];radiology=r||[];renderAll();const row=Array.isArray(u)?u[0]:u||{};$('#usageRecords').textContent=`${Number(row.task_count||0)} görev • ${Number(row.draft_count||0)} taslak • ${Number(row.project_count||0)} proje • ${Number(row.radiology_count||0)} radyoloji`;$('#usageBytes').textContent=bytesLabel(row.logical_bytes)}catch(e){showMsg('#appMsg',e.message||String(e))}}
function goto(tab){$$('[data-page]').forEach(e=>e.classList.toggle('hidden',e.dataset.page!==tab));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='radiology')renderRadiology();window.scrollTo({top:0,behavior:'smooth'})}
const templates={free:{title:'',body:''},tutanak:{title:'Tutanak',body:'TUTANAK\n\nTarih: '+todayISO()+'\nYer: \nKonu: \n\nOlay / Tespit:\n\n\nYapılan işlem:\n\n\nİşbu tutanak tarafımızca düzenlenerek imza altına alınmıştır.\n\nİmza:'},ustyazi:{title:'Üst Yazı Taslağı',body:'Konu: \n\nİLGİ: \n\nAçıklama:\n\n\nGereğini bilgilerinize arz ederim.\n'},sartname:{title:'Teknik Şartname Taslağı',body:'TEKNİK ŞARTNAME\n\n1. Amaç ve kapsam\n\n2. Teknik özellikler\n\n3. Kullanım ve uyumluluk şartları\n\n4. Teslimat / kabul kriterleri\n\n5. Garanti ve servis şartları\n'},faaliyet:{title:'Faaliyet Notu',body:'Dönem: \nBirim: \n\nYapılan faaliyetler:\n- \n\nSayısal veriler:\n- \n\nSorunlar / riskler:\n- \n\nSonraki dönem planı:\n- '}};
function resetDraftForm(){editingDraftId=null;$('#draftTitle').value='';$('#draftBody').value='';$('#draftBytes').textContent='0';$('#draftSaveBtn').textContent='Taslağı Kaydet';$('#draftCancelEdit').classList.add('hidden')}
function resetProjectForm(){editingProjectId=null;$('#projectTitle').value='';$('#projectCategory').value='work';$('#projectProgress').value='0';$('#projectDue').value='';$('#projectNext').value='';$('#projectSaveBtn').textContent='Projeyi Ekle';$('#projectCancelEdit').classList.add('hidden')}
async function patchTask(id,body){await api('/rest/v1/yea_tasks?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...body,updated_at:new Date().toISOString()})});await refreshData()}
async function patchProject(id,body){await api('/rest/v1/yea_projects?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...body,updated_at:new Date().toISOString()})});await refreshData()}
function makeBackup(){const data={format:'YEA-SUITE-BACKUP',version:'0.6',exported_at:new Date().toISOString(),tasks,drafts,projects,radiology};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='YEA_Suite_Yedek_'+todayISO()+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportRadCsv(){const rows=radRows();if(!rows.length){showMsg('#appMsg','Bu ay için dışa aktarılacak radyoloji verisi yok.');return}const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const lines=[['Ay','Birim','Hasta','İstem','Kesinti Günü','Not'].map(esc).join(';'),...rows.map(r=>[selectedRadMonth(),r.unit,r.patient_count,r.request_count,r.outage_days,r.note||''].map(esc).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='YEA_Radyoloji_'+selectedRadMonth()+'.csv';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function summaryToday(){const overdue=tasks.filter(t=>isOverdue(t));const today=tasks.filter(t=>t.status!=='done'&&isToday(t));const high=tasks.filter(t=>t.status!=='done'&&Number(t.priority)===1);const dueProjects=projects.filter(p=>p.status==='active'&&p.due_date).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date))).slice(0,5);const rad=radTotals(currentMonth());let out=`BUGÜNÜN YEA ÖZETİ\n\nAçık görev: ${tasks.filter(t=>t.status!=='done').length}\nBugün bitmesi gereken: ${today.length}\nGeciken: ${overdue.length}\nYüksek öncelik: ${high.length}\nAktif proje: ${projects.filter(p=>p.status==='active').length}\n\n`;if(overdue.length)out+='Önce gecikenler:\n'+overdue.slice(0,5).map(t=>'• '+t.title).join('\n')+'\n\n';if(today.length)out+='Bugün:\n'+today.slice(0,6).map(t=>'• '+t.title).join('\n')+'\n\n';if(dueProjects.length)out+='Yaklaşan projeler:\n'+dueProjects.map(p=>`• ${p.title} — %${p.progress}${p.next_action?' — '+p.next_action:''}`).join('\n')+'\n\n';out+=`Radyoloji ${currentMonth()}: ${rad.requests.toLocaleString('tr-TR')} istem, ${rad.patients.toLocaleString('tr-TR')} hasta, ${rad.rows.length}/8 birim dolu.`;$('#summaryResult').textContent=out}
function summaryPriority(){const open=tasks.filter(t=>t.status!=='done').sort((a,b)=>Number(a.priority)-Number(b.priority));const active=projects.filter(p=>p.status==='active').sort((a,b)=>Number(a.progress)-Number(b.progress));let out='ÖNCELİK LİSTESİ\n\n';if(open.length)out+='Görevler:\n'+open.slice(0,8).map((t,i)=>`${i+1}. [${priorityName(t.priority)}] ${t.title}${t.due_at?' — '+fmtDate(t.due_at):''}`).join('\n')+'\n\n';if(active.length)out+='Projeler:\n'+active.slice(0,6).map((p,i)=>`${i+1}. ${p.title} — %${p.progress}${p.next_action?' — Sonraki: '+p.next_action:''}`).join('\n');if(!open.length&&!active.length)out+='Açık görev veya aktif proje yok.';$('#summaryResult').textContent=out}
function summaryRadiology(){const m=selectedRadMonth();const t=radTotals(m),prev=radTotals(prevMonth(m));let out=`RADYOLOJİ ÖZETİ — ${m}\n\nHasta: ${t.patients.toLocaleString('tr-TR')}\nİstem: ${t.requests.toLocaleString('tr-TR')}\nKesinti günü toplamı: ${t.outage.toLocaleString('tr-TR')}\nVeri girilen birim: ${t.rows.length}/8\n\n`;if(t.rows.length)out+='Birimler:\n'+t.rows.map(r=>`• ${r.unit}: ${Number(r.patient_count).toLocaleString('tr-TR')} hasta / ${Number(r.request_count).toLocaleString('tr-TR')} istem${Number(r.outage_days)?' / '+r.outage_days+' gün kesinti':''}`).join('\n');if(prev.rows.length){const diff=t.requests-prev.requests;out+=`\n\nÖnceki aya göre istem farkı: ${diff>=0?'+':''}${diff.toLocaleString('tr-TR')}.`}$('#summaryResult').textContent=out}
$('#authForm').addEventListener('submit',e=>{e.preventDefault();sign('in')});
$('#signUp').addEventListener('click',()=>sign('up'));
$('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)goto(b.dataset.tab)});
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)goto(g.dataset.go)});
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#taskTitle').value.trim();if(!title)return;try{await api('/rest/v1/yea_tasks',{method:'POST',body:JSON.stringify({user_id:session.user.id,title,priority:Number($('#taskPriority').value),due_at:$('#taskDue').value?new Date($('#taskDue').value).toISOString():null,notes:$('#taskNotes').value.trim()||null})});e.target.reset();$('#taskPriority').value='2';await refreshData()}catch(err){showMsg('#appMsg',err.message)}});
$('#taskList').addEventListener('click',async e=>{try{const toggle=e.target.closest('[data-task-toggle]');if(toggle){const t=tasks.find(x=>x.id===toggle.dataset.taskToggle);if(t)await patchTask(t.id,{status:t.status==='done'?'open':'done'});return}const arch=e.target.closest('[data-task-archive]');if(arch)await patchTask(arch.dataset.taskArchive,{status:'archived'})}catch(err){showMsg('#appMsg',err.message)}});
$('#applyTemplate').addEventListener('click',()=>{const t=templates[$('#templateSelect').value]||templates.free;if(t.title)$('#draftTitle').value=t.title;if(t.body)$('#draftBody').value=t.body;$('#draftBytes').textContent=enc.encode($('#draftBody').value).byteLength.toLocaleString('tr-TR')});
$('#draftBody').addEventListener('input',()=>$('#draftBytes').textContent=enc.encode($('#draftBody').value).byteLength.toLocaleString('tr-TR'));
$('#draftForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#draftTitle').value.trim(),content=$('#draftBody').value;const bytes=enc.encode(content).byteLength;if(bytes>102400){showMsg('#appMsg','Belge taslağı 100 KB sınırını aşıyor.');return}try{if(editingDraftId)await api('/rest/v1/yea_document_drafts?id=eq.'+encodeURIComponent(editingDraftId),{method:'PATCH',body:JSON.stringify({title,content,document_type:$('#templateSelect').value,updated_at:new Date().toISOString()})});else await api('/rest/v1/yea_document_drafts',{method:'POST',body:JSON.stringify({user_id:session.user.id,title,document_type:$('#templateSelect').value,content})});resetDraftForm();await refreshData()}catch(err){showMsg('#appMsg',err.message)}});
$('#draftCancelEdit').addEventListener('click',resetDraftForm);
$('#draftList').addEventListener('click',async e=>{try{const ed=e.target.closest('[data-draft-edit]');if(ed){const d=drafts.find(x=>x.id===ed.dataset.draftEdit);if(!d)return;editingDraftId=d.id;$('#draftTitle').value=d.title;$('#draftBody').value=d.content||'';$('#templateSelect').value=['free','tutanak','ustyazi','sartname','faaliyet'].includes(d.document_type)?d.document_type:'free';$('#draftBytes').textContent=enc.encode($('#draftBody').value).byteLength.toLocaleString('tr-TR');$('#draftSaveBtn').textContent='Değişiklikleri Kaydet';$('#draftCancelEdit').classList.remove('hidden');window.scrollTo({top:$('#draftForm').offsetTop-20,behavior:'smooth'});return}const del=e.target.closest('[data-draft-delete]');if(del&&confirm('Bu taslak silinsin mi?')){await api('/rest/v1/yea_document_drafts?id=eq.'+encodeURIComponent(del.dataset.draftDelete),{method:'DELETE'});await refreshData()}}catch(err){showMsg('#appMsg',err.message)}});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const payload={title:$('#projectTitle').value.trim(),category:$('#projectCategory').value,progress:Number($('#projectProgress').value||0),due_date:$('#projectDue').value||null,next_action:$('#projectNext').value.trim()||null,updated_at:new Date().toISOString()};if(!payload.title)return;try{if(editingProjectId)await api('/rest/v1/yea_projects?id=eq.'+encodeURIComponent(editingProjectId),{method:'PATCH',body:JSON.stringify(payload)});else await api('/rest/v1/yea_projects',{method:'POST',body:JSON.stringify({...payload,user_id:session.user.id})});resetProjectForm();await refreshData()}catch(err){showMsg('#appMsg',err.message)}});
$('#projectCancelEdit').addEventListener('click',resetProjectForm);
$('#projectList').addEventListener('click',async e=>{try{const idAttr=name=>e.target.closest('['+name+']');let b=idAttr('data-project-plus');if(b){const p=projects.find(x=>x.id===b.dataset.projectPlus);if(p)await patchProject(p.id,{progress:Math.min(100,Number(p.progress||0)+10),status:Number(p.progress||0)+10>=100?'done':p.status});return}b=idAttr('data-project-toggle');if(b){const p=projects.find(x=>x.id===b.dataset.projectToggle);if(p)await patchProject(p.id,{status:p.status==='paused'?'active':'paused'});return}b=idAttr('data-project-done');if(b){await patchProject(b.dataset.projectDone,{status:'done',progress:100});return}b=idAttr('data-project-edit');if(b){const p=projects.find(x=>x.id===b.dataset.projectEdit);if(!p)return;editingProjectId=p.id;$('#projectTitle').value=p.title;$('#projectCategory').value=p.category;$('#projectProgress').value=p.progress;$('#projectDue').value=p.due_date||'';$('#projectNext').value=p.next_action||'';$('#projectSaveBtn').textContent='Değişiklikleri Kaydet';$('#projectCancelEdit').classList.remove('hidden');window.scrollTo({top:$('#projectForm').offsetTop-20,behavior:'smooth'});return}b=idAttr('data-project-archive');if(b)await patchProject(b.dataset.projectArchive,{status:'archived'})}catch(err){showMsg('#appMsg',err.message)}});
$('#radViewMonth').addEventListener('change',renderRadiology);
$('#radiologyForm').addEventListener('submit',async e=>{e.preventDefault();const month=selectedRadMonth();const payload={user_id:session.user.id,period:monthDate(month),unit:$('#radUnit').value,patient_count:Number($('#radPatient').value||0),request_count:Number($('#radRequest').value||0),outage_days:Number($('#radOutageInput').value||0),note:$('#radNote').value.trim()||null,updated_at:new Date().toISOString()};try{await api('/rest/v1/yea_radiology_metrics?on_conflict=user_id,period,unit',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});$('#radPatient').value='0';$('#radRequest').value='0';$('#radOutageInput').value='0';$('#radNote').value='';await refreshData();goto('radiology')}catch(err){showMsg('#appMsg',err.message)}});
$('#radiologyList').addEventListener('click',async e=>{try{const load=e.target.closest('[data-rad-load]');if(load){const r=radiology.find(x=>x.id===load.dataset.radLoad);if(!r)return;$('#radUnit').value=r.unit;$('#radPatient').value=r.patient_count;$('#radRequest').value=r.request_count;$('#radOutageInput').value=r.outage_days;$('#radNote').value=r.note||'';window.scrollTo({top:$('#radiologyForm').offsetTop-20,behavior:'smooth'});return}const del=e.target.closest('[data-rad-delete]');if(del&&confirm('Bu aylık birim kaydı silinsin mi?')){await api('/rest/v1/yea_radiology_metrics?id=eq.'+encodeURIComponent(del.dataset.radDelete),{method:'DELETE'});await refreshData();goto('radiology')}}catch(err){showMsg('#appMsg',err.message)}});
$('#exportRadCsv').addEventListener('click',exportRadCsv);
$('#summaryToday').addEventListener('click',summaryToday);$('#summaryPriority').addEventListener('click',summaryPriority);$('#summaryRadiology').addEventListener('click',summaryRadiology);
$('#exportBackup').addEventListener('click',makeBackup);$('#exportBackupSettings').addEventListener('click',makeBackup);
$('#logout').addEventListener('click',async()=>{try{if(session)await fetch(SUPA+'/auth/v1/logout',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}})}catch{}saveSession(null);location.reload()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
(async()=>{if(await ensureSession())await enterApp()})();
