'use strict';
const SUPA='https://bjieodqaujiqhnfxqgei.supabase.co';
const KEY='sb_publishable_W9B0WfrlpEh-MnjNEuzECw_3-a5dCPT';
const STORE='yea_suite_session_v1';
const RAD_UNITS=['Poliklinik Röntgen','Acil Röntgen','BT','Skopi','Portable','Mamografi','DEXA','USG'];
let session=null,tasks=[],drafts=[],projects=[],radiology=[],finance=[],vehicles=[],editingDraftId=null,editingProjectId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], enc=new TextEncoder();
const fmtMoney=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n||0));
function showMsg(where,text){const e=$(where);if(!e)return;if(!text){e.classList.add('hidden');e.textContent='';return}e.textContent=text;e.classList.remove('hidden')}
function saveSession(s){session=s;if(s)localStorage.setItem(STORE,JSON.stringify(s));else localStorage.removeItem(STORE)}
function loadSession(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function todayISO(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function currentMonth(){return todayISO().slice(0,7)}
function monthDate(m){return m+'-01'}
function prevMonth(m){const [y,mo]=m.split('-').map(Number),d=new Date(y,mo-2,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function fmtDate(v){if(!v)return 'Tarih yok';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('tr-TR',{dateStyle:'short',timeStyle:String(v).includes('T')?'short':undefined})}
function bytesLabel(b){b=Number(b||0);return b<1024?b+' B':b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(2)+' MB'}
function priorityName(p){return Number(p)===1?'Yüksek':Number(p)===3?'Düşük':'Normal'}
function projectStatusName(s){return ({active:'Aktif',paused:'Beklemede',done:'Tamamlandı',archived:'Arşiv'})[s]||s}
function categoryName(c){return ({work:'İş',personal:'Kişisel',software:'Yazılım',vehicle:'Araç',education:'Eğitim',other:'Diğer'})[c]||c}
function finCat(c){return ({home:'Ev',vehicle:'Araç',food:'Yeme-İçme',bill:'Fatura',health:'Sağlık',education:'Eğitim',salary:'Maaş/Gelir',other:'Diğer'})[c]||c}
function vehType(t){return ({maintenance:'Bakım',repair:'Onarım',bodywork:'Kaporta/Kozmetik',inspection:'Muayene',insurance:'Sigorta',fuel:'Yakıt',other:'Diğer'})[t]||t}
async function authFetch(path,opts={}){return fetch(SUPA+path,{...opts,headers:{apikey:KEY,'Content-Type':'application/json',...(opts.headers||{})}})}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await authFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){saveSession(null);return false}const d=await r.json();saveSession({...d,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)});return true}
async function ensureSession(){session=loadSession();if(!session)return false;const expires=Number(session.expires_at||0);if(expires&&expires<Math.floor(Date.now()/1000)+60)return refreshSession();return true}
async function api(path,opts={}){if(!session)throw new Error('Oturum yok.');const make=()=>{const headers={apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',...(opts.headers||{})};if(!headers.Prefer&&!headers.prefer)headers.Prefer='return=representation';return fetch(SUPA+path,{...opts,headers})};let r=await make();if(r.status===401&&await refreshSession())r=await make();if(!r.ok){let m='İşlem başarısız.';try{const j=await r.json();m=j.message||j.error_description||j.error||j.hint||m}catch{}throw new Error(m)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function sign(mode){showMsg('#authMsg','');const email=$('#email').value.trim(),password=$('#password').value;if(password.length<8){showMsg('#authMsg','Şifre en az 8 karakter olmalı.');return}const path=mode==='in'?'/auth/v1/token?grant_type=password':'/auth/v1/signup',r=await authFetch(path,{method:'POST',body:JSON.stringify({email,password})}),d=await r.json().catch(()=>({}));if(!r.ok){showMsg('#authMsg',d.error_description||d.msg||d.message||'Giriş başarısız.');return}if(mode==='up'&&!d.access_token){showMsg('#authMsg','Hesap oluşturuldu. E-posta doğrulaması açıksa gelen kutunu kontrol et.');return}saveSession({...d,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)});await enterApp()}
async function enterApp(){session=loadSession();$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');if(!$('#radViewMonth').value)$('#radViewMonth').value=currentMonth();if(!$('#financeMonth').value)$('#financeMonth').value=currentMonth();$('#finDate').value=todayISO();$('#vehDate').value=todayISO();await refreshData()}
function isOverdue(t){return t.status!=='done'&&t.due_at&&new Date(t.due_at)<new Date()}
function isToday(t){if(!t.due_at)return false;const d=new Date(t.due_at),n=new Date();return d.toDateString()===n.toDateString()}
function renderTasks(){const el=$('#taskList');el.innerHTML=tasks.length?tasks.map(t=>`<article class="taskItem"><div class="itemTitle ${t.status==='done'?'done':''}">${escapeHtml(t.title)}</div><div class="itemMeta"><span class="badge ${Number(t.priority)===1?'high':Number(t.priority)===3?'low':''}">${priorityName(t.priority)}</span>${t.due_at?`<span class="badge ${isOverdue(t)?'overdue':''}">${isOverdue(t)?'Gecikti • ':''}${fmtDate(t.due_at)}</span>`:''}</div>${t.notes?`<div class="noteLine">${escapeHtml(t.notes)}</div>`:''}<div class="itemActions"><button data-task-toggle="${t.id}">${t.status==='done'?'Geri Aç':'Tamamla'}</button><button data-task-archive="${t.id}">Arşivle</button></div></article>`).join(''):'<div class="empty">Henüz görev yok.</div>'}
function renderDrafts(){const el=$('#draftList');el.innerHTML=drafts.length?drafts.map(d=>`<article class="draft"><div class="itemTitle">${escapeHtml(d.title)}</div><div class="itemMeta"><span>${escapeHtml(d.document_type||'other')}</span><span>${fmtDate(d.updated_at)}</span></div><div class="itemActions"><button data-draft-edit="${d.id}">Düzenle</button><button data-draft-delete="${d.id}">Sil</button></div></article>`).join(''):'<div class="empty">Henüz belge taslağı yok.</div>'}
function renderProjects(){const v=projects.filter(p=>p.status!=='archived'),el=$('#projectList');el.innerHTML=v.length?v.map(p=>`<article class="projectItem"><div class="itemTitle ${p.status==='done'?'done':''}">${escapeHtml(p.title)}</div><div class="itemMeta"><span class="badge">${projectStatusName(p.status)}</span><span>${categoryName(p.category)}</span>${p.due_date?`<span>${p.due_date}</span>`:''}<span>%${Number(p.progress||0)}</span></div><div class="progress"><span style="width:${Math.min(100,Math.max(0,Number(p.progress||0)))}%"></span></div>${p.next_action?`<div class="projectNext"><b>Sonraki adım:</b> ${escapeHtml(p.next_action)}</div>`:''}<div class="itemActions"><button data-project-plus="${p.id}">+10%</button><button data-project-toggle="${p.id}">${p.status==='paused'?'Devam Et':'Beklet'}</button><button data-project-done="${p.id}">Tamamla</button><button data-project-edit="${p.id}">Düzenle</button><button data-project-archive="${p.id}">Arşivle</button></div></article>`).join(''):'<div class="empty">Henüz proje yok.</div>'}
function radRows(month=$('#radViewMonth').value||currentMonth()){return radiology.filter(r=>String(r.period).slice(0,7)===month).sort((a,b)=>RAD_UNITS.indexOf(a.unit)-RAD_UNITS.indexOf(b.unit))}
function radTotals(month=$('#radViewMonth').value||currentMonth()){const rows=radRows(month);return {rows,patients:rows.reduce((s,r)=>s+Number(r.patient_count||0),0),requests:rows.reduce((s,r)=>s+Number(r.request_count||0),0),outage:rows.reduce((s,r)=>s+Number(r.outage_days||0),0)}}
function renderRadiology(){const t=radTotals();$('#radPatients').textContent=t.patients.toLocaleString('tr-TR');$('#radRequests').textContent=t.requests.toLocaleString('tr-TR');$('#radOutage').textContent=t.outage.toLocaleString('tr-TR');$('#radFilled').textContent=t.rows.length+'/8';const prev=radTotals(prevMonth($('#radViewMonth').value||currentMonth()));$('#radTrend').textContent=prev.rows.length?`Önceki aya göre istem farkı: ${(t.requests-prev.requests)>=0?'+':''}${(t.requests-prev.requests).toLocaleString('tr-TR')}.`:'Önceki ay verisi yok.';$('#radiologyList').innerHTML=t.rows.length?t.rows.map(r=>`<article class="radItem"><div class="radRow"><div class="itemTitle">${escapeHtml(r.unit)}</div><div class="radValue">Hasta<br><b>${Number(r.patient_count||0).toLocaleString('tr-TR')}</b></div><div class="radValue">İstem<br><b>${Number(r.request_count||0).toLocaleString('tr-TR')}</b></div><div class="radValue">Kesinti<br><b>${Number(r.outage_days||0)} gün</b></div></div>${r.note?`<div class="noteLine">${escapeHtml(r.note)}</div>`:''}<div class="itemActions"><button data-rad-load="${r.id}">Forma Al</button><button data-rad-delete="${r.id}">Sil</button></div></article>`).join(''):'<div class="empty">Bu ay için veri yok.</div>'}
function financeRows(){const m=$('#financeMonth').value||currentMonth();return finance.filter(x=>String(x.entry_date).slice(0,7)===m)}
function financeTotals(month=currentMonth()){const rows=finance.filter(x=>String(x.entry_date).slice(0,7)===month),income=rows.filter(x=>x.entry_type==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=rows.filter(x=>x.entry_type==='expense').reduce((s,x)=>s+Number(x.amount||0),0);return {rows,income,expense,balance:income-expense}}
function renderFinance(){const t=financeTotals($('#financeMonth').value||currentMonth());$('#finIncome').textContent=fmtMoney(t.income);$('#finExpense').textContent=fmtMoney(t.expense);$('#finBalance').textContent=fmtMoney(t.balance);$('#finCount').textContent=t.rows.length;$('#financeList').innerHTML=t.rows.length?t.rows.sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date))).map(x=>`<article class="financeItem"><div class="itemTop"><div><div class="itemTitle">${finCat(x.category)}</div><div class="itemMeta"><span>${x.entry_date}</span><span>${escapeHtml(x.payment_method)}</span></div></div><div class="amount ${x.entry_type==='income'?'moneyIncome':'moneyExpense'}">${x.entry_type==='income'?'+':'-'}${fmtMoney(x.amount)}</div></div>${x.note?`<div class="noteLine">${escapeHtml(x.note)}</div>`:''}<div class="itemActions"><button data-fin-delete="${x.id}">Sil</button></div></article>`).join(''):'<div class="empty">Bu ay için finans kaydı yok.</div>'}
function renderVehicle(){const open=vehicles.filter(v=>['open','planned'].includes(v.status)),cost=vehicles.reduce((s,v)=>s+Number(v.cost||0),0),now=new Date(),limit=new Date(Date.now()+30*86400000),soon=vehicles.filter(v=>v.next_due_date&&new Date(v.next_due_date+'T23:59:59')>=now&&new Date(v.next_due_date+'T23:59:59')<=limit);$('#vehCount').textContent=vehicles.length;$('#vehOpen').textContent=open.length;$('#vehCost').textContent=fmtMoney(cost);$('#vehSoon').textContent=soon.length;$('#vehicleList').innerHTML=vehicles.length?vehicles.map(v=>`<article class="vehicleItem"><div class="itemTop"><div><div class="itemTitle ${v.status==='done'?'done':''}">${escapeHtml(v.title)}</div><div class="itemMeta"><span>${vehType(v.record_type)}</span><span>${v.record_date}</span>${v.odometer?`<span>${Number(v.odometer).toLocaleString('tr-TR')} km</span>`:''}<span>${v.status}</span></div></div><div class="amount">${fmtMoney(v.cost)}</div></div>${v.next_due_date||v.next_due_km?`<div class="projectNext"><b>Sonraki:</b> ${v.next_due_date||'-'} ${v.next_due_km?'• '+Number(v.next_due_km).toLocaleString('tr-TR')+' km':''}</div>`:''}${v.note?`<div class="noteLine">${escapeHtml(v.note)}</div>`:''}<div class="itemActions"><button data-veh-toggle="${v.id}">${v.status==='done'?'Geri Aç':'Tamamla'}</button><button data-veh-archive="${v.id}">Arşivle</button></div></article>`).join(''):'<div class="empty">Henüz araç kaydı yok.</div>'}
function renderHome(){const f=financeTotals(currentMonth());$('#openCount').textContent=tasks.filter(t=>t.status!=='done').length;$('#todayCount').textContent=tasks.filter(t=>t.status!=='done'&&isToday(t)).length;$('#projectCount').textContent=projects.filter(p=>p.status==='active').length;$('#monthRequestCount').textContent=radTotals(currentMonth()).requests.toLocaleString('tr-TR');$('#monthBalance').textContent=fmtMoney(f.balance);$('#vehicleOpenCount').textContent=vehicles.filter(v=>['open','planned'].includes(v.status)).length}
function renderAll(){renderTasks();renderDrafts();renderProjects();renderRadiology();renderFinance();renderVehicle();renderHome()}
async function refreshData(){try{showMsg('#appMsg','');const [t,d,p,r,f,v,u]=await Promise.all([api('/rest/v1/yea_tasks?select=id,title,notes,status,due_at,priority,created_at,updated_at&status=neq.archived&order=priority.asc,due_at.asc.nullslast,created_at.desc&limit=150'),api('/rest/v1/yea_document_drafts?select=id,title,document_type,content,updated_at&order=updated_at.desc&limit=120'),api('/rest/v1/yea_projects?select=id,title,category,status,progress,next_action,due_date,updated_at&order=updated_at.desc&limit=120'),api('/rest/v1/yea_radiology_metrics?select=id,period,unit,patient_count,request_count,outage_days,note,updated_at&order=period.desc,unit.asc&limit=240'),api('/rest/v1/yea_finance_entries?select=id,entry_date,entry_type,category,amount,payment_method,note,updated_at&order=entry_date.desc,created_at.desc&limit=500'),api('/rest/v1/yea_vehicle_records?select=id,record_date,record_type,title,odometer,cost,next_due_date,next_due_km,status,note,updated_at&status=neq.archived&order=record_date.desc,created_at.desc&limit=300'),api('/rest/v1/rpc/yea_my_usage_v3',{method:'POST',body:'{}'})]);tasks=t||[];drafts=d||[];projects=p||[];radiology=r||[];finance=f||[];vehicles=v||[];renderAll();const row=Array.isArray(u)?u[0]:u||{};$('#usageRecords').textContent=`${Number(row.task_count||0)} görev • ${Number(row.draft_count||0)} taslak • ${Number(row.project_count||0)} proje • ${Number(row.radiology_count||0)} radyoloji • ${Number(row.finance_count||0)} finans • ${Number(row.vehicle_count||0)} araç`;$('#usageBytes').textContent=bytesLabel(row.logical_bytes)}catch(e){showMsg('#appMsg',e.message||String(e))}}
function goto(tab){$$('[data-page]').forEach(e=>e.classList.toggle('hidden',e.dataset.page!==tab));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='radiology')renderRadiology();if(tab==='finance')renderFinance();if(tab==='vehicle')renderVehicle();window.scrollTo({top:0,behavior:'smooth'})}
const templates={free:{title:'',body:''},tutanak:{title:'Tutanak',body:'TUTANAK\n\nTarih: '+todayISO()+'\nYer: \nKonu: \n\nOlay / Tespit:\n\n\nYapılan işlem:\n\n\nİşbu tutanak tarafımızca düzenlenerek imza altına alınmıştır.\n\nİmza:'},ustyazi:{title:'Üst Yazı Taslağı',body:'Konu: \n\nİLGİ: \n\nAçıklama:\n\n\nGereğini bilgilerinize arz ederim.\n'},sartname:{title:'Teknik Şartname Taslağı',body:'TEKNİK ŞARTNAME\n\n1. Amaç ve kapsam\n\n2. Teknik özellikler\n\n3. Kullanım ve uyumluluk şartları\n\n4. Teslimat / kabul kriterleri\n\n5. Garanti ve servis şartları\n'},faaliyet:{title:'Faaliyet Notu',body:'Dönem: \nBirim: \n\nYapılan faaliyetler:\n- \n\nSayısal veriler:\n- \n\nSorunlar / riskler:\n- \n\nSonraki dönem planı:\n- '}};
function resetDraftForm(){editingDraftId=null;$('#draftTitle').value='';$('#draftBody').value='';$('#draftBytes').textContent='0';$('#draftSaveBtn').textContent='Taslağı Kaydet';$('#draftCancelEdit').classList.add('hidden')}
function resetProjectForm(){editingProjectId=null;$('#projectTitle').value='';$('#projectCategory').value='work';$('#projectProgress').value='0';$('#projectDue').value='';$('#projectNext').value='';$('#projectSaveBtn').textContent='Projeyi Ekle';$('#projectCancelEdit').classList.add('hidden')}
async function patchTask(id,body){await api('/rest/v1/yea_tasks?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...body,updated_at:new Date().toISOString()})});await refreshData()}
async function patchProject(id,body){await api('/rest/v1/yea_projects?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...body,updated_at:new Date().toISOString()})});await refreshData()}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportRadCsv(){const rows=radRows(),csv=['Birim,Hasta,İstem,Kesinti Günü,Not',...rows.map(r=>[r.unit,r.patient_count,r.request_count,r.outage_days,(r.note||'').replaceAll('"','""')].map(v=>'"'+String(v)+'"').join(','))].join('\n');download('YEA_Radyoloji_'+($('#radViewMonth').value||currentMonth())+'.csv','\ufeff'+csv,'text/csv;charset=utf-8')}
function exportFinanceCsv(){const rows=financeRows(),csv=['Tarih,Tip,Kategori,Tutar,Ödeme,Not',...rows.map(r=>[r.entry_date,r.entry_type,finCat(r.category),r.amount,r.payment_method,(r.note||'').replaceAll('"','""')].map(v=>'"'+String(v)+'"').join(','))].join('\n');download('YEA_Finans_'+($('#financeMonth').value||currentMonth())+'.csv','\ufeff'+csv,'text/csv;charset=utf-8')}
function makeBackup(){download('YEA_Suite_Yedek_'+todayISO()+'.json',JSON.stringify({version:'0.7',exported_at:new Date().toISOString(),tasks,drafts,projects,radiology,finance,vehicles},null,2))}
function summaryToday(){const due=tasks.filter(t=>t.status!=='done'&&isToday(t)),over=tasks.filter(isOverdue),active=projects.filter(p=>p.status==='active').slice(0,5);$('#summaryResult').textContent=`Bugün ${due.length} görev var. ${over.length} görev gecikmiş.\n\n${due.map(t=>'• '+t.title).join('\n')||'Bugüne tarihli görev yok.'}\n\nAktif projeler:\n${active.map(p=>'• '+p.title+' — %'+p.progress+(p.next_action?' — '+p.next_action:'')).join('\n')||'Aktif proje yok.'}`}
function summaryPriority(){const high=tasks.filter(t=>t.status!=='done'&&Number(t.priority)===1);$('#summaryResult').textContent=high.length?'Yüksek öncelikli işler:\n'+high.map((t,i)=>(i+1)+'. '+t.title+(t.due_at?' — '+fmtDate(t.due_at):'')).join('\n'):'Yüksek öncelikli açık görev yok.'}
function summaryRadiology(){const t=radTotals(currentMonth()),p=radTotals(prevMonth(currentMonth()));$('#summaryResult').textContent=`${currentMonth()} radyoloji özeti\nHasta: ${t.patients.toLocaleString('tr-TR')}\nİstem: ${t.requests.toLocaleString('tr-TR')}\nKesinti: ${t.outage} gün\nDolu birim: ${t.rows.length}/8${p.rows.length?'\nÖnceki aya göre istem farkı: '+(t.requests-p.requests>=0?'+':'')+(t.requests-p.requests).toLocaleString('tr-TR'):''}`}
function summaryFinance(){const t=financeTotals(currentMonth()),top=finance.filter(x=>x.entry_type==='expense'&&String(x.entry_date).slice(0,7)===currentMonth()).sort((a,b)=>Number(b.amount)-Number(a.amount)).slice(0,5);$('#summaryResult').textContent=`${currentMonth()} finans özeti\nGelir: ${fmtMoney(t.income)}\nGider: ${fmtMoney(t.expense)}\nBakiye: ${fmtMoney(t.balance)}\n\nEn yüksek giderler:\n${top.map(x=>'• '+finCat(x.category)+' — '+fmtMoney(x.amount)+(x.note?' — '+x.note:'')).join('\n')||'Gider kaydı yok.'}`}
function summaryVehicle(){const open=vehicles.filter(v=>['open','planned'].includes(v.status)),now=new Date(),lim=new Date(Date.now()+30*86400000),soon=vehicles.filter(v=>v.next_due_date&&new Date(v.next_due_date+'T23:59:59')>=now&&new Date(v.next_due_date+'T23:59:59')<=lim);$('#summaryResult').textContent=`Araç özeti\nAçık/planlı iş: ${open.length}\nToplam kayıtlı masraf: ${fmtMoney(vehicles.reduce((s,v)=>s+Number(v.cost||0),0))}\n30 gün içinde yaklaşan: ${soon.length}\n\n${open.slice(0,8).map(v=>'• '+v.title+(v.next_due_date?' — '+v.next_due_date:'')).join('\n')||'Açık araç işi yok.'}`}
$('#authForm').addEventListener('submit',e=>{e.preventDefault();sign('in')});$('#signUp').addEventListener('click',()=>sign('up'));$('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)goto(b.dataset.tab)});document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)goto(g.dataset.go)});
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_tasks',{method:'POST',body:JSON.stringify({user_id:session.user.id,title:$('#taskTitle').value.trim(),priority:Number($('#taskPriority').value),due_at:$('#taskDue').value?new Date($('#taskDue').value).toISOString():null,notes:$('#taskNotes').value.trim()||null})});e.target.reset();$('#taskPriority').value='2';await refreshData()}catch(err){showMsg('#appMsg',err.message)}});$('#taskList').addEventListener('click',async e=>{try{const t=e.target.closest('[data-task-toggle]');if(t){const x=tasks.find(a=>a.id===t.dataset.taskToggle);if(x)await patchTask(x.id,{status:x.status==='done'?'open':'done'});return}const a=e.target.closest('[data-task-archive]');if(a)await patchTask(a.dataset.taskArchive,{status:'archived'})}catch(err){showMsg('#appMsg',err.message)}});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const payload={title:$('#projectTitle').value.trim(),category:$('#projectCategory').value,progress:Number($('#projectProgress').value||0),due_date:$('#projectDue').value||null,next_action:$('#projectNext').value.trim()||null,updated_at:new Date().toISOString()};try{if(editingProjectId)await api('/rest/v1/yea_projects?id=eq.'+encodeURIComponent(editingProjectId),{method:'PATCH',body:JSON.stringify(payload)});else await api('/rest/v1/yea_projects',{method:'POST',body:JSON.stringify({...payload,user_id:session.user.id,status:'active'})});resetProjectForm();await refreshData()}catch(err){showMsg('#appMsg',err.message)}});$('#projectCancelEdit').addEventListener('click',resetProjectForm);$('#projectList').addEventListener('click',async e=>{try{let b=e.target.closest('[data-project-plus]');if(b){const p=projects.find(x=>x.id===b.dataset.projectPlus);if(p)await patchProject(p.id,{progress:Math.min(100,Number(p.progress||0)+10),status:Number(p.progress||0)+10>=100?'done':p.status});return}b=e.target.closest('[data-project-toggle]');if(b){const p=projects.find(x=>x.id===b.dataset.projectToggle);if(p)await patchProject(p.id,{status:p.status==='paused'?'active':'paused'});return}b=e.target.closest('[data-project-done]');if(b){await patchProject(b.dataset.projectDone,{status:'done',progress:100});return}b=e.target.closest('[data-project-edit]');if(b){const p=projects.find(x=>x.id===b.dataset.projectEdit);if(!p)return;editingProjectId=p.id;$('#projectTitle').value=p.title;$('#projectCategory').value=p.category;$('#projectProgress').value=p.progress;$('#projectDue').value=p.due_date||'';$('#projectNext').value=p.next_action||'';$('#projectSaveBtn').textContent='Değişiklikleri Kaydet';$('#projectCancelEdit').classList.remove('hidden');return}b=e.target.closest('[data-project-archive]');if(b)await patchProject(b.dataset.projectArchive,{status:'archived'})}catch(err){showMsg('#appMsg',err.message)}});
$('#radViewMonth').addEventListener('change',renderRadiology);$('#radiologyForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_radiology_metrics?on_conflict=user_id,period,unit',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:session.user.id,period:monthDate($('#radViewMonth').value||currentMonth()),unit:$('#radUnit').value,patient_count:Number($('#radPatient').value||0),request_count:Number($('#radRequest').value||0),outage_days:Number($('#radOutageInput').value||0),note:$('#radNote').value.trim()||null,updated_at:new Date().toISOString()})});$('#radPatient').value='0';$('#radRequest').value='0';$('#radOutageInput').value='0';$('#radNote').value='';await refreshData();goto('radiology')}catch(err){showMsg('#appMsg',err.message)}});$('#radiologyList').addEventListener('click',async e=>{try{const l=e.target.closest('[data-rad-load]');if(l){const r=radiology.find(x=>x.id===l.dataset.radLoad);if(r){$('#radUnit').value=r.unit;$('#radPatient').value=r.patient_count;$('#radRequest').value=r.request_count;$('#radOutageInput').value=r.outage_days;$('#radNote').value=r.note||''}return}const d=e.target.closest('[data-rad-delete]');if(d&&confirm('Bu kayıt silinsin mi?')){await api('/rest/v1/yea_radiology_metrics?id=eq.'+encodeURIComponent(d.dataset.radDelete),{method:'DELETE'});await refreshData()}}catch(err){showMsg('#appMsg',err.message)}});$('#exportRadCsv').addEventListener('click',exportRadCsv);
$('#financeMonth').addEventListener('change',renderFinance);$('#financeForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_finance_entries',{method:'POST',body:JSON.stringify({user_id:session.user.id,entry_date:$('#finDate').value,entry_type:$('#finType').value,category:$('#finCategory').value,amount:Number($('#finAmount').value||0),payment_method:$('#finMethod').value,note:$('#finNote').value.trim()||null})});$('#finAmount').value='';$('#finNote').value='';await refreshData();goto('finance')}catch(err){showMsg('#appMsg',err.message)}});$('#financeList').addEventListener('click',async e=>{const d=e.target.closest('[data-fin-delete]');if(d&&confirm('Bu finans kaydı silinsin mi?'))try{await api('/rest/v1/yea_finance_entries?id=eq.'+encodeURIComponent(d.dataset.finDelete),{method:'DELETE'});await refreshData()}catch(err){showMsg('#appMsg',err.message)}});$('#exportFinanceCsv').addEventListener('click',exportFinanceCsv);
$('#vehicleForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_vehicle_records',{method:'POST',body:JSON.stringify({user_id:session.user.id,record_date:$('#vehDate').value,record_type:$('#vehType').value,title:$('#vehTitle').value.trim(),odometer:$('#vehKm').value?Number($('#vehKm').value):null,cost:Number($('#vehCostInput').value||0),next_due_date:$('#vehNextDate').value||null,next_due_km:$('#vehNextKm').value?Number($('#vehNextKm').value):null,status:$('#vehStatus').value,note:$('#vehNote').value.trim()||null})});e.target.reset();$('#vehDate').value=todayISO();$('#vehStatus').value='open';await refreshData();goto('vehicle')}catch(err){showMsg('#appMsg',err.message)}});$('#vehicleList').addEventListener('click',async e=>{try{const t=e.target.closest('[data-veh-toggle]');if(t){const v=vehicles.find(x=>x.id===t.dataset.vehToggle);if(v){await api('/rest/v1/yea_vehicle_records?id=eq.'+encodeURIComponent(v.id),{method:'PATCH',body:JSON.stringify({status:v.status==='done'?'open':'done',updated_at:new Date().toISOString()})});await refreshData()}return}const a=e.target.closest('[data-veh-archive]');if(a){await api('/rest/v1/yea_vehicle_records?id=eq.'+encodeURIComponent(a.dataset.vehArchive),{method:'PATCH',body:JSON.stringify({status:'archived',updated_at:new Date().toISOString()})});await refreshData()}}catch(err){showMsg('#appMsg',err.message)}});
$('#applyTemplate').addEventListener('click',()=>{const t=templates[$('#templateSelect').value]||templates.free;if(t.title)$('#draftTitle').value=t.title;if(t.body)$('#draftBody').value=t.body;$('#draftBytes').textContent=enc.encode($('#draftBody').value).byteLength.toLocaleString('tr-TR')});$('#draftBody').addEventListener('input',()=>$('#draftBytes').textContent=enc.encode($('#draftBody').value).byteLength.toLocaleString('tr-TR'));$('#draftForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#draftTitle').value.trim(),content=$('#draftBody').value;if(enc.encode(content).byteLength>102400){showMsg('#appMsg','Belge taslağı 100 KB sınırını aşıyor.');return}try{if(editingDraftId)await api('/rest/v1/yea_document_drafts?id=eq.'+encodeURIComponent(editingDraftId),{method:'PATCH',body:JSON.stringify({title,content,document_type:$('#templateSelect').value,updated_at:new Date().toISOString()})});else await api('/rest/v1/yea_document_drafts',{method:'POST',body:JSON.stringify({user_id:session.user.id,title,document_type:$('#templateSelect').value,content})});resetDraftForm();await refreshData()}catch(err){showMsg('#appMsg',err.message)}});$('#draftCancelEdit').addEventListener('click',resetDraftForm);$('#draftList').addEventListener('click',async e=>{try{const ed=e.target.closest('[data-draft-edit]');if(ed){const d=drafts.find(x=>x.id===ed.dataset.draftEdit);if(d){editingDraftId=d.id;$('#draftTitle').value=d.title;$('#draftBody').value=d.content||'';$('#templateSelect').value=['free','tutanak','ustyazi','sartname','faaliyet'].includes(d.document_type)?d.document_type:'free';$('#draftSaveBtn').textContent='Değişiklikleri Kaydet';$('#draftCancelEdit').classList.remove('hidden')}return}const del=e.target.closest('[data-draft-delete]');if(del&&confirm('Bu taslak silinsin mi?')){await api('/rest/v1/yea_document_drafts?id=eq.'+encodeURIComponent(del.dataset.draftDelete),{method:'DELETE'});await refreshData()}}catch(err){showMsg('#appMsg',err.message)}});
$('#summaryToday').addEventListener('click',summaryToday);$('#summaryPriority').addEventListener('click',summaryPriority);$('#summaryRadiology').addEventListener('click',summaryRadiology);$('#summaryFinance').addEventListener('click',summaryFinance);$('#summaryVehicle').addEventListener('click',summaryVehicle);$('#exportBackup').addEventListener('click',makeBackup);$('#exportBackupSettings').addEventListener('click',makeBackup);$('#logout').addEventListener('click',async()=>{try{if(session)await fetch(SUPA+'/auth/v1/logout',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}})}catch{}saveSession(null);location.reload()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));(async()=>{if(await ensureSession())await enterApp()})();
