'use strict';
const V12_RECENT='yea_v12_recent_modules';
const V12_HOME='yea_v12_home_widgets';
const V12_STATS='yea_v12_show_stats';
let v12WeekOffset=0;
const v12ModuleNames={today:'Bugün',calendar:'Takvim',week:'Hafta',tasks:'Görevler',recurring:'Tekrarlayan',projects:'Projeler',radiology:'Radyoloji',finance:'Finans',vehicle:'Araç',docs:'Belgeler',summary:'Özetler',assistant:'YEA Asistanı',decision:'Karar Merkezi',settings:'Ayarlar'};
const v12HomeModules=['today','calendar','tasks','projects','radiology','finance','vehicle','docs','assistant','decision','rpys','backup'];
function v12Json(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function v12Set(key,val){try{localStorage.setItem(key,JSON.stringify(val))}catch{}}
function v12DateLocal(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function v12Monday(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
function v12AddDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function v12Short(d){return d.toLocaleDateString('tr-TR',{day:'2-digit',month:'short'})}
function v12Full(d){return d.toLocaleDateString('tr-TR',{weekday:'long',day:'2-digit',month:'long'})}
function v12InRange(value,start,end){if(!value)return false;const d=new Date(value);return !Number.isNaN(d.getTime())&&d>=start&&d<end}
function v12RecordRecent(tab){if(!tab||tab==='home'||tab==='settings')return;let a=v12Json(V12_RECENT,[]).filter(x=>x.tab!==tab);a.unshift({tab,at:Date.now()});a=a.slice(0,8);v12Set(V12_RECENT,a);v12RenderRecent()}
function v12RenderRecent(){const host=$('#v12RecentModules');if(!host)return;const a=v12Json(V12_RECENT,[]).slice(0,5);host.innerHTML=a.length?a.map(x=>`<button type="button" data-v12-recent="${escapeHtml(x.tab)}">${escapeHtml(v12ModuleNames[x.tab]||x.tab)}</button>`).join(''):'<span>Henüz kullanım yok.</span>'}
const v12BaseGoto=goto;
goto=function(tab){v12BaseGoto(tab);v12RecordRecent(tab);if(tab==='week')v12RenderWeek()};
$('#v12RecentModules')?.addEventListener('click',e=>{const b=e.target.closest('[data-v12-recent]');if(b)goto(b.dataset.v12Recent)});
function v12CardKey(card){const go=card.querySelector('[data-go]')?.dataset.go;if(go)return go;const a=card.querySelector('a[href*="2nyunuss-coder.github.io"]');if(a)return'rpys';if(card.querySelector('#exportBackup')||String(card.textContent||'').toLocaleUpperCase('tr-TR').includes('TAM YEDEK'))return'backup';return''}
function v12CardMap(){const map={};document.querySelectorAll('[data-page="home"] .grid article.card').forEach(c=>{const k=v12CardKey(c);if(k)map[k]=c});return map}
function v12Prefs(){const p=v12Json(V12_HOME,null);return p&&typeof p==='object'?p:Object.fromEntries(v12HomeModules.map(k=>[k,true]))}
function v12ApplyHome(){const prefs=v12Prefs(),map=v12CardMap();for(const [k,c] of Object.entries(map))c.classList.toggle('v12HiddenCard',prefs[k]===false);const stats=$('[data-page="home"] .stats');if(stats)stats.classList.toggle('hidden',localStorage.getItem(V12_STATS)==='0')}
function v12RenderWidgetChoices(){const host=$('#v12WidgetChoices');if(!host)return;const prefs=v12Prefs(),labels={today:'Bugün',calendar:'Takvim',tasks:'Görevler',projects:'Projeler',radiology:'Radyoloji',finance:'Finans',vehicle:'Araç',docs:'Belgeler',assistant:'YEA Asistanı',decision:'Karar Merkezi',rpys:'RPYS bağlantısı',backup:'Tam Yedek'};host.innerHTML=v12HomeModules.map(k=>`<label><input type="checkbox" data-v12-widget="${k}" ${prefs[k]!==false?'checked':''}/> ${labels[k]||k}</label>`).join('');$('#v12ShowStats').checked=localStorage.getItem(V12_STATS)!=='0'}
$('#v12WidgetChoices')?.addEventListener('change',e=>{const x=e.target.closest('[data-v12-widget]');if(!x)return;const p=v12Prefs();p[x.dataset.v12Widget]=x.checked;v12Set(V12_HOME,p);v12ApplyHome()});
$('#v12ShowStats')?.addEventListener('change',e=>{localStorage.setItem(V12_STATS,e.target.checked?'1':'0');v12ApplyHome()});
$('#v12ResetHome')?.addEventListener('click',()=>{localStorage.removeItem(V12_HOME);localStorage.removeItem(V12_STATS);v12RenderWidgetChoices();v12ApplyHome()});
$('#v12SortFrequent')?.addEventListener('click',()=>{const grid=$('[data-page="home"] .grid'),map=v12CardMap(),recent=v12Json(V12_RECENT,[]).map(x=>x.tab);if(!grid)return;const order=[...new Set([...recent,'today','calendar','tasks','projects','radiology','finance','vehicle','docs','assistant','decision','rpys','backup'])];order.forEach(k=>{if(map[k])grid.appendChild(map[k])});showMsg('#appMsg','Ana ekran sık kullanılanlara göre sıralandı.');setTimeout(()=>showMsg('#appMsg',''),1500)});
function v12WeekBounds(){const start=v12AddDays(v12Monday(),v12WeekOffset*7),end=v12AddDays(start,7);start.setHours(0,0,0,0);end.setHours(0,0,0,0);return{start,end}}
function v12DayEvents(d){const ds=v12DateLocal(d),rows=[];tasks.filter(t=>t.status!=='archived'&&t.due_at&&v12DateLocal(new Date(t.due_at))===ds).forEach(t=>rows.push({kind:'Görev',icon:'●',title:t.title,done:t.status==='done'}));projects.filter(p=>p.status!=='archived'&&p.due_date===ds).forEach(p=>rows.push({kind:'Proje',icon:'◆',title:p.title,done:p.status==='done'}));vehicles.filter(v=>v.status!=='archived'&&v.next_due_date===ds).forEach(v=>rows.push({kind:'Araç',icon:'▲',title:v.title,done:v.status==='done'}));recurring.filter(r=>recMatches(r,new Date(ds+'T12:00:00'))).forEach(r=>rows.push({kind:'Tekrar',icon:'↻',title:r.title,done:false}));return rows}
function v12WeekText(){const {start,end}=v12WeekBounds(),doneTasks=tasks.filter(t=>t.status==='done'&&v12InRange(t.updated_at,start,end)),expense=finance.filter(f=>f.entry_type==='expense'&&String(f.entry_date)>=v12DateLocal(start)&&String(f.entry_date)<v12DateLocal(end)),income=finance.filter(f=>f.entry_type==='income'&&String(f.entry_date)>=v12DateLocal(start)&&String(f.entry_date)<v12DateLocal(end)),doneProjects=projects.filter(p=>p.status==='done'&&v12InRange(p.updated_at,start,end)),doneVehicles=vehicles.filter(v=>v.status==='done'&&v12InRange(v.updated_at,start,end)),spent=expense.reduce((s,x)=>s+Number(x.amount||0),0),earned=income.reduce((s,x)=>s+Number(x.amount||0),0),openWeek=tasks.filter(t=>t.status!=='done'&&t.due_at&&v12InRange(t.due_at,start,end));let lines=[`HAFTALIK YEA RAPORU • ${v12Short(start)} – ${v12Short(v12AddDays(end,-1))}`,'',`✓ Tamamlanan görev: ${doneTasks.length}`,`○ Haftada kalan açık görev: ${openWeek.length}`,`◆ Tamamlanan proje: ${doneProjects.length}`,`▲ Tamamlanan araç işi: ${doneVehicles.length}`,`💸 Gider: ${fmtMoney(spent)}`,`💰 Gelir: ${fmtMoney(earned)}`,`↔ Net: ${fmtMoney(earned-spent)}`];const top=typeof v11PlanCandidates==='function'?v11PlanCandidates().slice(0,3):[];if(top.length){lines.push('','SONRAKİ ODAK');top.forEach((x,i)=>lines.push(`${i+1}. ${x.kind}: ${x.title}`))}if(doneTasks.length){lines.push('','TAMAMLANANLAR');doneTasks.slice(0,8).forEach(x=>lines.push('• '+x.title))}return lines.join('\n')}
function v12RenderWeek(){const host=$('#v12WeekGrid');if(!host)return;const {start,end}=v12WeekBounds();$('#v12WeekTitle').textContent=`${v12Short(start)} – ${v12Short(v12AddDays(end,-1))}`;let html='';for(let i=0;i<7;i++){const d=v12AddDays(start,i),ev=v12DayEvents(d),today=v12DateLocal(d)===v12DateLocal(new Date());html+=`<article class="v12WeekDay ${today?'today':''}"><div class="v12WeekDayHead"><b>${escapeHtml(v12Full(d))}</b><span>${ev.length} kayıt</span></div><div class="v12WeekEvents">${ev.length?ev.slice(0,10).map(x=>`<div class="v12WeekEvent ${x.done?'done':''}"><span>${x.icon}</span><div><small>${x.kind}</small><b>${escapeHtml(x.title)}</b></div></div>`).join(''):'<span class="tiny">Planlı kayıt yok.</span>'}</div><button type="button" data-v12-day-add="${v12DateLocal(d)}">+ Bu güne görev</button></article>`}host.innerHTML=html;$('#v12WeekReport').textContent=v12WeekText()}
$('#v12PrevWeek')?.addEventListener('click',()=>{v12WeekOffset--;v12RenderWeek()});$('#v12NextWeek')?.addEventListener('click',()=>{v12WeekOffset++;v12RenderWeek()});$('#v12ThisWeek')?.addEventListener('click',()=>{v12WeekOffset=0;v12RenderWeek()});
$('#v12WeekGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-v12-day-add]');if(!b)return;v12OpenQuick('task');$('#v12TaskDue').value=b.dataset.v12DayAdd+'T09:00'});
$('#v12CopyWeek')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(v12WeekText());$('#v12CopyWeek').textContent='Kopyalandı';setTimeout(()=>$('#v12CopyWeek').textContent='Raporu Kopyala',1200)}catch{showMsg('#appMsg','Kopyalama kullanılamadı.')}});
function v12QuickTab(kind){document.querySelectorAll('[data-v12-qtab]').forEach(b=>b.classList.toggle('active',b.dataset.v12Qtab===kind));document.querySelectorAll('[data-v12-qform]').forEach(f=>f.classList.toggle('hidden',f.dataset.v12Qform!==kind));$('#v12QuickSub').textContent=({task:'Görev hızlı kaydı',expense:'Gider hızlı kaydı',project:'Proje hızlı kaydı',vehicle:'Araç hızlı kaydı'})[kind]||''}
function v12OpenQuick(kind='task'){const m=$('#v12QuickModal');m.classList.remove('hidden');v12QuickTab(kind);$('#v12ExpenseDate').value=$('#v12ExpenseDate').value||todayISO();$('#v12VehicleDate').value=$('#v12VehicleDate').value||todayISO();setTimeout(()=>{const f=m.querySelector(`[data-v12-qform="${kind}"] input`);f?.focus()},30)}
function v12CloseQuick(){$('#v12QuickModal').classList.add('hidden');$('#v12QuickMsg').textContent=''}
$('#v12Fab')?.addEventListener('click',()=>v12OpenQuick('task'));$('#v12OpenQuick')?.addEventListener('click',()=>v12OpenQuick('task'));document.querySelectorAll('[data-v12-quick]').forEach(b=>b.addEventListener('click',()=>v12OpenQuick(b.dataset.v12Quick)));$('#v12QuickClose')?.addEventListener('click',v12CloseQuick);$('#v12QuickModal')?.addEventListener('click',e=>{if(e.target.id==='v12QuickModal')v12CloseQuick()});document.querySelectorAll('[data-v12-qtab]').forEach(b=>b.addEventListener('click',()=>v12QuickTab(b.dataset.v12Qtab)));
function v12QuickOk(text){$('#v12QuickMsg').textContent=text;setTimeout(()=>{$('#v12QuickMsg').textContent='';v12CloseQuick()},650)}
$('#v12QuickTask')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_tasks',{method:'POST',body:JSON.stringify({user_id:session.user.id,title:$('#v12TaskTitle').value.trim(),notes:$('#v12TaskNote').value.trim()||null,priority:Number($('#v12TaskPriority').value),due_at:$('#v12TaskDue').value?new Date($('#v12TaskDue').value).toISOString():null})});e.target.reset();$('#v12TaskPriority').value='2';await refreshData();v12QuickOk('Görev eklendi ✓')}catch(err){$('#v12QuickMsg').textContent=err.message}});
$('#v12QuickExpense')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_finance_entries',{method:'POST',body:JSON.stringify({user_id:session.user.id,entry_date:$('#v12ExpenseDate').value,entry_type:'expense',category:$('#v12ExpenseCat').value,amount:Number($('#v12ExpenseAmount').value||0),payment_method:'other',note:$('#v12ExpenseNote').value.trim()||null})});e.target.reset();$('#v12ExpenseDate').value=todayISO();await refreshData();v12QuickOk('Gider eklendi ✓')}catch(err){$('#v12QuickMsg').textContent=err.message}});
$('#v12QuickProject')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_projects',{method:'POST',body:JSON.stringify({user_id:session.user.id,title:$('#v12ProjectTitle').value.trim(),category:'other',status:'active',progress:0,next_action:$('#v12ProjectNext').value.trim()||null,due_date:$('#v12ProjectDue').value||null})});e.target.reset();await refreshData();v12QuickOk('Proje eklendi ✓')}catch(err){$('#v12QuickMsg').textContent=err.message}});
$('#v12QuickVehicle')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/rest/v1/yea_vehicle_records',{method:'POST',body:JSON.stringify({user_id:session.user.id,record_date:$('#v12VehicleDate').value,record_type:$('#v12VehicleType').value,title:$('#v12VehicleTitle').value.trim(),cost:Number($('#v12VehicleCost').value||0),next_due_date:$('#v12VehicleNext').value||null,status:'open',note:$('#v12VehicleNote').value.trim()||null})});e.target.reset();$('#v12VehicleDate').value=todayISO();await refreshData();v12QuickOk('Araç kaydı eklendi ✓')}catch(err){$('#v12QuickMsg').textContent=err.message}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#v12QuickModal')?.classList.contains('hidden'))v12CloseQuick();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();goto('search');setTimeout(()=>$('#globalSearchInput')?.focus(),50)}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();v12OpenQuick('task')}});
const v12BaseRefresh=refreshData;
refreshData=async function(){await v12BaseRefresh();v12RenderWeek();v12ApplyHome()};
v12RenderRecent();v12RenderWidgetChoices();v12ApplyHome();v12RenderWeek();
