'use strict';
(()=>{
const LS_ITEMS='yea_v13_desktop_items',LS_START='yea_v13_desktop_startup';
const $13=s=>document.querySelector(s),$$13=s=>[...document.querySelectorAll(s)];
const esc13=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid13=()=>crypto.randomUUID?crypto.randomUUID():'i'+Date.now()+Math.random().toString(36).slice(2);
let ctxItemId=null,pdfDoc13=null,pdfName13='belge.pdf',pdfUrl13=null,pdfBusy13=false;
function defaultItems(){return[{id:'app-rpys',type:'url',name:'RPYS',target:'https://2nyunuss-coder.github.io/',icon:'🏥',folderId:null},{id:'app-today',type:'app',name:'Bugün',target:'today',icon:'☀️',folderId:null},{id:'app-tasks',type:'app',name:'Görevler',target:'tasks',icon:'✅',folderId:null},{id:'app-calendar',type:'app',name:'Takvim',target:'calendar',icon:'📅',folderId:null},{id:'app-pdf',type:'app',name:'PDF Editör',target:'pdf',icon:'📕',folderId:null},{id:'app-docs',type:'app',name:'Belgeler',target:'docs',icon:'📄',folderId:null},{id:'app-finance',type:'app',name:'Finans',target:'finance',icon:'💰',folderId:null},{id:'app-vehicle',type:'app',name:'Araç',target:'vehicle',icon:'🚗',folderId:null}]}
function loadItems(){try{let a=JSON.parse(localStorage.getItem(LS_ITEMS)||'null');return Array.isArray(a)&&a.length?a:defaultItems()}catch{return defaultItems()}}
function saveItems(a){localStorage.setItem(LS_ITEMS,JSON.stringify(a));renderDesktop()}
function setItems(a){saveItems(a)}
function iconFor(t){return t==='folder'?'📁':t==='url'?'🌐':t==='path'?'📌':t==='fileHandle'?'📎':t==='dirHandle'?'🗂':'⬜'}
function itemBy(id){return loadItems().find(x=>x.id===id)}
function appOpen(id){try{goto(id)}catch{}closeStart()}
window.v13AppOpen=appOpen;
function renderDesktop(){const host=$13('#v13DesktopGrid');if(!host)return;const items=loadItems().filter(x=>!x.folderId);host.innerHTML=items.map((x,i)=>`<button class="v13DeskIcon" draggable="true" data-id="${esc13(x.id)}" data-pos="${i}" title="${esc13(x.target||x.name)}"><span>${esc13(x.icon||iconFor(x.type))}</span><b>${esc13(x.name)}</b></button>`).join('');host.querySelectorAll('.v13DeskIcon').forEach(b=>{b.ondblclick=()=>openItem(b.dataset.id);b.onclick=()=>{host.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};b.oncontextmenu=e=>{e.preventDefault();ctxItemId=b.dataset.id;showContext(e.clientX,e.clientY)};b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.id);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain'),to=b.dataset.id;if(from&&to&&from!==to)reorderItems(from,to)}})}
function reorderItems(from,to){let a=loadItems(),i=a.findIndex(x=>x.id===from),j=a.findIndex(x=>x.id===to);if(i<0||j<0)return;const[v]=a.splice(i,1);a.splice(j,0,v);setItems(a)}
function modal(title,html){$13('#v13DeskModalTitle').textContent=title;$13('#v13DeskModalBody').innerHTML=html;$13('#v13DeskModal').classList.remove('hidden')}
function closeModal(){$13('#v13DeskModal').classList.add('hidden')}
$13('#v13DeskModalClose')?.addEventListener('click',closeModal);$13('#v13DeskModal')?.addEventListener('click',e=>{if(e.target.id==='v13DeskModal')closeModal()});
function newFolder(parent=null){modal('Yeni Klasör',`<form id="v13FolderForm"><label>Klasör adı<input id="v13FolderName" maxlength="80" placeholder="Yeni klasör" required /></label><div class="formActions"><button>Oluştur</button></div></form><hr><button id="v13CreateRealDir" type="button" class="ghost">🗂 Bilgisayarda Gerçek Klasör Oluştur</button><p class="tiny">Gerçek klasör oluşturma Chrome/Edge gibi destekleyen tarayıcılarda çalışır ve senden klasör izni ister.</p>`);$13('#v13FolderForm').onsubmit=e=>{e.preventDefault();let n=$13('#v13FolderName').value.trim();if(!n)return;let a=loadItems();a.push({id:uid13(),type:'folder',name:n,target:'',icon:'📁',folderId:parent});saveItems(a);closeModal()};$13('#v13CreateRealDir').onclick=createRealDirectory}
function newShortcut(parent=null,edit=null){const val=edit||{};modal(edit?'Kısayolu Düzenle':'Yeni Kısayol',`<form id="v13ShortcutForm"><label>Ad<input id="v13ShortcutName" maxlength="80" value="${esc13(val.name||'')}" placeholder="Kısayol adı" required /></label><div class="formGrid two"><label>Tür<select id="v13ShortcutType"><option value="url" ${val.type==='url'?'selected':''}>Web adresi (URL)</option><option value="path" ${val.type==='path'?'selected':''}>Windows dosya/klasör yolu</option><option value="app" ${val.type==='app'?'selected':''}>YEA modülü</option></select></label><label>Simge<input id="v13ShortcutIcon" maxlength="8" value="${esc13(val.icon||'🔗')}" /></label></div><label>Adres / Yol / Modül<input id="v13ShortcutTarget" value="${esc13(val.target||'')}" placeholder="https://... veya C:\\Klasör\\Dosya.pdf veya tasks" required /></label><div class="formActions"><button>${edit?'Kaydet':'Kısayol Oluştur'}</button></div></form><p class="tiny">https:// bağlantıları doğrudan açılır. Windows yolu tarayıcı tarafından engellenirse YEA yolu panoya kopyalar. Gerçek dosya/klasör bağlantısı için Masaüstündeki “Dosya Bağla / Klasör Bağla” düğmelerini kullan.</p>`);$13('#v13ShortcutForm').onsubmit=e=>{e.preventDefault();let a=loadItems(),obj={id:edit?.id||uid13(),type:$13('#v13ShortcutType').value,name:$13('#v13ShortcutName').value.trim(),target:$13('#v13ShortcutTarget').value.trim(),icon:$13('#v13ShortcutIcon').value.trim()||'🔗',folderId:edit?.folderId??parent};if(edit)a=a.map(x=>x.id===edit.id?obj:x);else a.push(obj);saveItems(a);closeModal()}}
async function openItem(id){const x=itemBy(id);if(!x)return;if(x.type==='app')return appOpen(x.target);if(x.type==='url')return window.open(x.target,'_blank','noopener,noreferrer');if(x.type==='folder')return openVirtualFolder(x);if(x.type==='fileHandle')return openHandleFile(x);if(x.type==='dirHandle')return openHandleDir(x);if(x.type==='path')return openPath(x.target)}
async function openPath(path){let p=String(path||'').trim();if(!p)return;let href=p;if(/^[a-zA-Z]:\\/.test(p))href='file:///'+p.replace(/\\/g,'/');try{const w=window.open(href,'_blank');if(w)return}catch{}try{await navigator.clipboard.writeText(p);alert('Tarayıcı bu yerel yolu doğrudan açmaya izin vermedi. Yol panoya kopyalandı:\n'+p)}catch{alert('Yerel yol:\n'+p)}}
function openVirtualFolder(folder){const children=loadItems().filter(x=>x.folderId===folder.id);modal('📁 '+folder.name,`<div class="v13FolderBar"><button id="v13FolderAddShortcut" type="button">＋ Kısayol</button><button id="v13FolderAddFolder" type="button" class="ghost">📁 Alt Klasör</button></div><div class="v13FolderGrid">${children.length?children.map(x=>`<button data-v13-folder-item="${esc13(x.id)}"><span>${esc13(x.icon||iconFor(x.type))}</span><b>${esc13(x.name)}</b></button>`).join(''):'<p class="tiny">Klasör boş.</p>'}</div>`);$13('#v13FolderAddShortcut').onclick=()=>newShortcut(folder.id);$13('#v13FolderAddFolder').onclick=()=>newFolder(folder.id);$$13('[data-v13-folder-item]').forEach(b=>b.ondblclick=()=>openItem(b.dataset.v13FolderItem))}
function showContext(x,y){const c=$13('#v13Context');c.style.left=Math.min(x,innerWidth-180)+'px';c.style.top=Math.min(y,innerHeight-150)+'px';c.classList.remove('hidden')}
function hideContext(){$13('#v13Context')?.classList.add('hidden')}
document.addEventListener('click',e=>{if(!e.target.closest('#v13Context'))hideContext()});$13('#v13Context')?.addEventListener('click',e=>{const a=e.target.closest('[data-v13-ctx]');if(!a||!ctxItemId)return;const x=itemBy(ctxItemId);hideContext();if(a.dataset.v13Ctx==='open')openItem(ctxItemId);if(a.dataset.v13Ctx==='rename')newShortcut(x?.folderId??null,x);if(a.dataset.v13Ctx==='delete'&&x&&confirm(x.name+' silinsin mi?'))setItems(loadItems().filter(i=>i.id!==x.id&&i.folderId!==x.id))});
async function dbHandles(){return new Promise((res,rej)=>{const r=indexedDB.open('yea_v13_handles',1);r.onupgradeneeded=()=>r.result.createObjectStore('h');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putHandle(id,h){const d=await dbHandles();return new Promise((res,rej)=>{const tx=d.transaction('h','readwrite');tx.objectStore('h').put(h,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getHandle(id){const d=await dbHandles();return new Promise((res,rej)=>{const r=d.transaction('h').objectStore('h').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function ensurePermission(h,mode='read'){if(!h)return false;const o={mode};if((await h.queryPermission?.(o))==='granted')return true;return (await h.requestPermission?.(o))==='granted'}
async function linkFile(){if(!window.showOpenFilePicker)return alert('Bu tarayıcı kalıcı dosya bağlantısını desteklemiyor. Windows Chrome/Edge ile deneyebilirsin.');try{const[h]=await showOpenFilePicker();const id=uid13();await putHandle(id,h);let a=loadItems();a.push({id,type:'fileHandle',name:h.name,target:'',icon:h.name.toLowerCase().endsWith('.pdf')?'📕':'📎',folderId:null});saveItems(a)}catch(e){if(e.name!=='AbortError')alert(e.message)}}
async function linkDir(){if(!window.showDirectoryPicker)return alert('Bu tarayıcı klasör bağlantısını desteklemiyor. Windows Chrome/Edge ile deneyebilirsin.');try{const h=await showDirectoryPicker();const id=uid13();await putHandle(id,h);let a=loadItems();a.push({id,type:'dirHandle',name:h.name,target:'',icon:'🗂',folderId:null});saveItems(a)}catch(e){if(e.name!=='AbortError')alert(e.message)}}
async function openHandleFile(x){const h=await getHandle(x.id);if(!await ensurePermission(h))return alert('Dosya izni verilmedi.');const f=await h.getFile();if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){appOpen('pdf');await loadPdfFile(f);return}const u=URL.createObjectURL(f);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function openHandleDir(x){const h=await getHandle(x.id);if(!await ensurePermission(h))return alert('Klasör izni verilmedi.');let rows=[];for await(const[name,ch]of h.entries())rows.push({name,kind:ch.kind});modal('🗂 '+x.name,`<div class="v13FolderGrid">${rows.slice(0,200).map(r=>`<div class="v13RealEntry"><span>${r.kind==='directory'?'📁':'📄'}</span><b>${esc13(r.name)}</b></div>`).join('')||'<p class="tiny">Klasör boş.</p>'}</div><p class="tiny">İlk 200 öğe gösterilir.</p>`)}
async function createRealDirectory(){if(!window.showDirectoryPicker)return alert('Bu tarayıcı gerçek klasör oluşturmayı desteklemiyor.');try{const parent=await showDirectoryPicker({mode:'readwrite'});if(!await ensurePermission(parent,'readwrite'))return;const n=$13('#v13FolderName').value.trim()||'Yeni Klasör';await parent.getDirectoryHandle(n,{create:true});alert('Bilgisayarda klasör oluşturuldu: '+n)}catch(e){if(e.name!=='AbortError')alert(e.message)}}
$13('#v13NewFolder')?.addEventListener('click',()=>newFolder());$13('#v13NewShortcut')?.addEventListener('click',()=>newShortcut());$13('#v13LinkFile')?.addEventListener('click',linkFile);$13('#v13LinkDir')?.addEventListener('click',linkDir);
function toggleStart(){$13('#v13StartMenu').classList.toggle('hidden')}function closeStart(){$13('#v13StartMenu').classList.add('hidden')}
$13('#v13StartBtn')?.addEventListener('click',toggleStart);$$13('[data-v13-open]').forEach(b=>b.addEventListener('click',()=>appOpen(b.dataset.v13Open)));$13('#v13StartRpys')?.addEventListener('click',()=>window.open('https://2nyunuss-coder.github.io/','_blank','noopener,noreferrer'));$13('#v13TaskbarSearch')?.addEventListener('click',()=>appOpen('search'));document.addEventListener('click',e=>{if(!e.target.closest('#v13StartMenu,#v13StartBtn'))closeStart()});
function clock(){const d=new Date();$13('#v13Clock').innerHTML=`<b>${d.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</b><span>${d.toLocaleDateString('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'})}</span>`;$13('#v13DesktopDate').textContent=d.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}clock();setInterval(clock,30000);
const startup=$13('#v13DesktopStartup');if(startup){startup.checked=localStorage.getItem(LS_START)!=='0';startup.onchange=()=>localStorage.setItem(LS_START,startup.checked?'1':'0')}
let didAuto=false;setInterval(()=>{const app=$13('#appView');if(!didAuto&&app&&!app.classList.contains('hidden')){didAuto=true;if(localStorage.getItem(LS_START)!=='0')setTimeout(()=>appOpen('desktop'),180)}},150);
const mmpt=n=>Number(n||0)*72/25.4;
function pdfLib(){if(!window.PDFLib)throw new Error('PDF motoru yüklenemedi. İnternet bağlantısını kontrol et.');return window.PDFLib}
function msgPdf(t){$13('#v13PdfMsg').textContent=t||''}
function currentPageIndex(){if(!pdfDoc13)return 0;return Math.max(0,Math.min(pdfDoc13.getPageCount()-1,Number($13('#v13PdfPageNo').value||1)-1))}
function syncPdfUi(){const n=pdfDoc13?pdfDoc13.getPageCount():0;$13('#v13PdfPageCount').value=n;$13('#v13PdfPageNo').max=Math.max(1,n);$13('#v13PdfPageNo').value=Math.min(Math.max(1,Number($13('#v13PdfPageNo').value||1)),Math.max(1,n));$13('#v13PdfInfo').textContent=pdfDoc13?`${pdfName13} • ${n} sayfa`:'PDF seçilmedi';['#v13PdfSave','#v13PdfAddBlank','#v13PdfPrev','#v13PdfNext','#v13PdfRotateL','#v13PdfRotateR','#v13PdfMoveL','#v13PdfMoveR','#v13PdfDeletePage','#v13PdfAddText','#v13PdfCover'].forEach(s=>{const e=$13(s);if(e)e.disabled=!pdfDoc13||pdfBusy13})}
async function refreshPdfPreview(){if(!pdfDoc13)return;pdfBusy13=true;syncPdfUi();try{const bytes=await pdfDoc13.save();if(pdfUrl13)URL.revokeObjectURL(pdfUrl13);pdfUrl13=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));$13('#v13PdfFrame').src=pdfUrl13+'#page='+$13('#v13PdfPageNo').value;$13('#v13PdfEmpty').classList.add('hidden')}finally{pdfBusy13=false;syncPdfUi()}}
async function loadPdfFile(file){try{pdfName13=file.name||'belge.pdf';pdfDoc13=await pdfLib().PDFDocument.load(await file.arrayBuffer());$13('#v13PdfPageNo').value=1;msgPdf('PDF açıldı. Değişiklikler yalnız cihazında.');await refreshPdfPreview()}catch(e){msgPdf('PDF açılamadı: '+e.message)}}window.loadPdfFile=loadPdfFile;
$13('#v13PdfFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadPdfFile(f)});$13('#v13PdfPageNo')?.addEventListener('change',()=>refreshPdfPreview());$13('#v13PdfPrev')?.addEventListener('click',()=>{if(!pdfDoc13)return;$13('#v13PdfPageNo').value=Math.max(1,Number($13('#v13PdfPageNo').value)-1);refreshPdfPreview()});$13('#v13PdfNext')?.addEventListener('click',()=>{if(!pdfDoc13)return;$13('#v13PdfPageNo').value=Math.min(pdfDoc13.getPageCount(),Number($13('#v13PdfPageNo').value)+1);refreshPdfPreview()});
async function rotatePdf(delta){if(!pdfDoc13)return;const{degrees}=pdfLib(),p=pdfDoc13.getPage(currentPageIndex()),r=p.getRotation().angle||0;p.setRotation(degrees((r+delta+360)%360));await refreshPdfPreview()}$13('#v13PdfRotateL')?.addEventListener('click',()=>rotatePdf(-90));$13('#v13PdfRotateR')?.addEventListener('click',()=>rotatePdf(90));
$13('#v13PdfDeletePage')?.addEventListener('click',async()=>{if(!pdfDoc13)return;if(pdfDoc13.getPageCount()<=1)return msgPdf('Tek sayfalı PDF’de son sayfa silinemez.');if(!confirm('Seçili sayfa silinsin mi?'))return;pdfDoc13.removePage(currentPageIndex());await refreshPdfPreview()});
$13('#v13PdfAddBlank')?.addEventListener('click',async()=>{if(!pdfDoc13)return;pdfDoc13.addPage();$13('#v13PdfPageNo').value=pdfDoc13.getPageCount();await refreshPdfPreview()});
async function reorderPdf(dir){if(!pdfDoc13)return;const n=pdfDoc13.getPageCount(),i=currentPageIndex(),j=i+dir;if(j<0||j>=n)return;const bytes=await pdfDoc13.save(),src=await pdfLib().PDFDocument.load(bytes),out=await pdfLib().PDFDocument.create(),order=[...Array(n).keys()];[order[i],order[j]]=[order[j],order[i]];const pages=await out.copyPages(src,order);pages.forEach(p=>out.addPage(p));pdfDoc13=out;$13('#v13PdfPageNo').value=j+1;await refreshPdfPreview()}$13('#v13PdfMoveL')?.addEventListener('click',()=>reorderPdf(-1));$13('#v13PdfMoveR')?.addEventListener('click',()=>reorderPdf(1));
function colorPdf(){const{rgb}=pdfLib();return $13('#v13PdfColor').value==='red'?rgb(.8,.05,.05):$13('#v13PdfColor').value==='blue'?rgb(.05,.25,.75):rgb(0,0,0)}
$13('#v13PdfAddText')?.addEventListener('click',async()=>{if(!pdfDoc13)return;const text=$13('#v13PdfText').value;if(!text.trim())return msgPdf('Metin yaz.');const p=pdfDoc13.getPage(currentPageIndex()),size=Math.max(6,Number($13('#v13PdfSize').value||12)),x=mmpt($13('#v13PdfX').value),top=mmpt($13('#v13PdfY').value),font=await pdfDoc13.embedFont(pdfLib().StandardFonts.Helvetica);let y=p.getHeight()-top-size;for(const line of text.split(/\n/)){p.drawText(line,{x,y,size,font,color:colorPdf()});y-=size*1.25}msgPdf('Metin eklendi.');await refreshPdfPreview()});
$13('#v13PdfCover')?.addEventListener('click',async()=>{if(!pdfDoc13)return;const{rgb}=pdfLib(),p=pdfDoc13.getPage(currentPageIndex()),x=mmpt($13('#v13PdfX').value),w=mmpt($13('#v13PdfCoverW').value),h=mmpt($13('#v13PdfCoverH').value),top=mmpt($13('#v13PdfY').value),y=p.getHeight()-top-h;p.drawRectangle({x,y,width:w,height:h,color:rgb(1,1,1),borderColor:rgb(1,1,1)});msgPdf('Alan beyazla kapatıldı. İstersen şimdi aynı konuma yeni metin ekle.');await refreshPdfPreview()});
$13('#v13PdfMergeFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(!pdfDoc13)return msgPdf('Önce ana PDF’yi aç.');try{const src=await pdfLib().PDFDocument.load(await f.arrayBuffer()),idx=src.getPageIndices(),pages=await pdfDoc13.copyPages(src,idx);pages.forEach(p=>pdfDoc13.addPage(p));msgPdf(`${f.name} birleştirildi.`);await refreshPdfPreview()}catch(err){msgPdf('Birleştirme başarısız: '+err.message)}finally{e.target.value=''}});
$13('#v13PdfSave')?.addEventListener('click',async()=>{if(!pdfDoc13)return;const bytes=await pdfDoc13.save(),u=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=pdfName13.replace(/\.pdf$/i,'')+'_YEA.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);msgPdf('Düzenlenmiş PDF cihazına kaydedildi.')});
renderDesktop();syncPdfUi();
})();
