'use strict';
(()=>{
const LS_ITEMS='yea_v13_desktop_items',LS_TRASH='yea_v14_trash',LS_WALL='yea_v14_wallpaper',LS_WALL_IMG='yea_v14_wallpaper_image';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function loadItems(){try{const a=JSON.parse(localStorage.getItem(LS_ITEMS)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function saveItems(a){localStorage.setItem(LS_ITEMS,JSON.stringify(a));renderExplorer();augmentDesktop()}
function loadTrash(){try{const a=JSON.parse(localStorage.getItem(LS_TRASH)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function saveTrash(a){localStorage.setItem(LS_TRASH,JSON.stringify(a));renderTrash();renderExplorer();augmentDesktop()}
function icon(x){return x.icon||(x.type==='folder'?'📁':x.type==='url'?'🌐':x.type==='path'?'📌':x.type==='fileHandle'?'📎':x.type==='dirHandle'?'🗂':'⬜')}
function addSystemIcons(){const g=$('#v13DesktopGrid');if(!g)return;if(!g.querySelector('[data-v14-system="files"]'))g.insertAdjacentHTML('beforeend','<button class="v13DeskIcon v14SystemIcon" data-v14-system="files"><span>🗃</span><b>Dosyalar</b></button><button class="v13DeskIcon v14SystemIcon" data-v14-system="trash"><span>🗑</span><b>Çöp Kutusu</b><em id="v14TrashBadge"></em></button>');const n=loadTrash().length,b=$('#v14TrashBadge');if(b){b.textContent=n?String(n):'';b.classList.toggle('hidden',!n)}}
function augmentDesktop(){setTimeout(addSystemIcons,20)}
new MutationObserver(()=>augmentDesktop()).observe($('#v13DesktopGrid')||document.body,{childList:true});
$('#v13DesktopGrid')?.addEventListener('dblclick',e=>{const b=e.target.closest('[data-v14-system]');if(!b)return;e.stopImmediatePropagation();if(b.dataset.v14System==='files')window.v13AppOpen('files');else openTrash()},true);
function moveToTrash(id){const items=loadItems(),x=items.find(i=>i.id===id);if(!x)return;const descendants=[];const collect=pid=>items.filter(i=>i.folderId===pid).forEach(c=>{descendants.push(c);if(c.type==='folder')collect(c.id)});if(x.type==='folder')collect(x.id);saveTrash([...loadTrash(),{...x,deletedAt:new Date().toISOString()},...descendants.map(d=>({...d,deletedAt:new Date().toISOString()}))]);const ids=new Set([x.id,...descendants.map(d=>d.id)]);saveItems(items.filter(i=>!ids.has(i.id)))}
$('#v13Context')?.addEventListener('click',e=>{const b=e.target.closest('[data-v13-ctx="delete"]');if(!b)return;const selected=$('#v13DesktopGrid .v13DeskIcon.selected');const id=selected?.dataset.id;if(!id)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const x=loadItems().find(i=>i.id===id);if(x&&confirm(x.name+' Çöp Kutusuna taşınsın mı?'))moveToTrash(id)},true);
let currentLoc='desktop';
function treeFolders(){const all=loadItems().filter(x=>x.type==='folder');const roots=all.filter(x=>!x.folderId);function row(f,depth){const children=all.filter(x=>x.folderId===f.id);return `<button data-v14-folder="${esc(f.id)}" style="padding-left:${10+depth*14}px">📁 ${esc(f.name)}</button>${children.map(c=>row(c,depth+1)).join('')}`}return roots.map(r=>row(r,0)).join('')}
function itemsForLoc(){const all=loadItems();if(currentLoc==='desktop')return all.filter(x=>!x.folderId);if(currentLoc==='all')return all;if(currentLoc==='trash')return loadTrash();return all.filter(x=>x.folderId===currentLoc)}
function renderExplorer(){const tree=$('#v14FolderTree'),grid=$('#v14FileGrid');if(!tree||!grid)return;tree.innerHTML=treeFolders();$$('[data-v14-location]').forEach(b=>b.classList.toggle('active',b.dataset.v14Location===currentLoc));$$('[data-v14-folder]').forEach(b=>b.classList.toggle('active',b.dataset.v14Folder===currentLoc));const all=loadItems(),folder=all.find(x=>x.id===currentLoc);$('#v14ExplorerTitle').textContent=currentLoc==='desktop'?'Masaüstü':currentLoc==='all'?'Tüm Öğeler':currentLoc==='trash'?'Çöp Kutusu':folder?.name||'Klasör';const rows=itemsForLoc();$('#v14ExplorerCount').textContent=rows.length+' öğe';grid.innerHTML=rows.length?rows.map(x=>`<button class="v14FileItem" data-v14-item="${esc(x.id)}"><span>${esc(icon(x))}</span><b>${esc(x.name)}</b><small>${esc(x.type||'')}</small></button>`).join(''):'<div class="v14Empty">Bu konum boş.</div>'}
function openExplorerItem(id){if(currentLoc==='trash')return;const x=loadItems().find(i=>i.id===id);if(!x)return;if(x.type==='folder'){currentLoc=x.id;renderExplorer();return}if(x.type==='app')return window.v13AppOpen(x.target);if(x.type==='url')return window.open(x.target,'_blank','noopener,noreferrer');if(x.type==='path'){navigator.clipboard?.writeText(x.target);alert('Yerel yol panoya kopyalandı:\n'+x.target);return}if(x.type==='fileHandle'||x.type==='dirHandle')alert('Bu bağlantıyı Masaüstündeki simgesinden açabilirsin. Dosya izni tarayıcı tarafından yönetilir.')}
$('#v14FileGrid')?.addEventListener('dblclick',e=>{const b=e.target.closest('[data-v14-item]');if(b)openExplorerItem(b.dataset.v14Item)});
$('#v14FolderTree')?.addEventListener('click',e=>{const b=e.target.closest('[data-v14-folder]');if(b){currentLoc=b.dataset.v14Folder;renderExplorer()}});
$$('[data-v14-location]').forEach(b=>b.addEventListener('click',()=>{currentLoc=b.dataset.v14Location;renderExplorer()}));
$('#v14FileRefresh')?.addEventListener('click',renderExplorer);$('#v14FileNewFolder')?.addEventListener('click',()=>$('#v13NewFolder')?.click());$('#v14FileAddShortcut')?.addEventListener('click',()=>$('#v13NewShortcut')?.click());
function openTrash(){renderTrash();const w=$('#v14TrashWindow');w.classList.remove('hidden');bringFront(w)}
function renderTrash(){const h=$('#v14TrashList');if(!h)return;const t=loadTrash();h.innerHTML=t.length?t.map(x=>`<div class="v14TrashRow"><span>${esc(icon(x))}</span><div><b>${esc(x.name)}</b><small>${x.deletedAt?new Date(x.deletedAt).toLocaleString('tr-TR'):''}</small></div><button data-v14-restore="${esc(x.id)}">Geri Yükle</button><button class="danger" data-v14-purge="${esc(x.id)}">Sil</button></div>`).join(''):'<div class="v14Empty">Çöp Kutusu boş.</div>'}
$('#v14TrashList')?.addEventListener('click',e=>{let b=e.target.closest('[data-v14-restore]');if(b){const id=b.dataset.v14Restore,t=loadTrash(),x=t.find(i=>i.id===id);if(x){const copy={...x};delete copy.deletedAt;saveItems([...loadItems(),copy]);saveTrash(t.filter(i=>i.id!==id))}return}b=e.target.closest('[data-v14-purge]');if(b&&confirm('Kalıcı olarak silinsin mi?'))saveTrash(loadTrash().filter(i=>i.id!==b.dataset.v14Purge))});
$('#v14TrashEmpty')?.addEventListener('click',()=>{if(loadTrash().length&&confirm('Çöp Kutusundaki her şey kalıcı olarak silinsin mi?'))saveTrash([])});$('#v14TaskbarTrash')?.addEventListener('click',openTrash);$('#v14StartTrash')?.addEventListener('click',openTrash);$('#v14TaskbarFiles')?.addEventListener('click',()=>window.v13AppOpen('files'));$('#v14StartFiles')?.addEventListener('click',()=>window.v13AppOpen('files'));
let z=500;
function bringFront(w){w.style.zIndex=String(++z);w.classList.add('active');$$('.v14Window').filter(x=>x!==w).forEach(x=>x.classList.remove('active'))}
function wireWindow(w){if(w.dataset.v14Wired)return;w.dataset.v14Wired='1';let drag=null;const bar=w.querySelector('.v14WinBar');bar?.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;bringFront(w);drag={x:e.clientX,y:e.clientY,l:w.offsetLeft,t:w.offsetTop};bar.setPointerCapture(e.pointerId)});bar?.addEventListener('pointermove',e=>{if(!drag||w.classList.contains('max'))return;w.style.left=Math.max(0,drag.l+e.clientX-drag.x)+'px';w.style.top=Math.max(0,drag.t+e.clientY-drag.y)+'px'});bar?.addEventListener('pointerup',()=>drag=null);w.addEventListener('pointerdown',()=>bringFront(w));const r=w.querySelector('.v14Resize');let rs=null;r?.addEventListener('pointerdown',e=>{bringFront(w);rs={x:e.clientX,y:e.clientY,w:w.offsetWidth,h:w.offsetHeight};r.setPointerCapture(e.pointerId);e.stopPropagation()});r?.addEventListener('pointermove',e=>{if(!rs||w.classList.contains('max'))return;w.style.width=Math.max(320,rs.w+e.clientX-rs.x)+'px';w.style.height=Math.max(220,rs.h+e.clientY-rs.y)+'px'});r?.addEventListener('pointerup',()=>rs=null)}
$$('.v14Window').forEach(w=>wireWindow(w));document.addEventListener('click',e=>{let b=e.target.closest('[data-v14-close]');if(b){$(`[data-v14-window="${CSS.escape(b.dataset.v14Close)}"]`)?.classList.add('hidden');return}b=e.target.closest('[data-v14-min]');if(b){$(`[data-v14-window="${CSS.escape(b.dataset.v14Min)}"]`)?.classList.add('hidden');return}b=e.target.closest('[data-v14-max]');if(b)$(`[data-v14-window="${CSS.escape(b.dataset.v14Max)}"]`)?.classList.toggle('max')});
function applyWallpaper(){const d=$('#v13Desktop'),mode=localStorage.getItem(LS_WALL)||'blue';if(!d)return;d.dataset.wall=mode;if(mode==='image'){const img=localStorage.getItem(LS_WALL_IMG);d.style.backgroundImage=img?`linear-gradient(rgba(0,0,0,.08),rgba(0,0,0,.08)),url(${img})`:''}else d.style.backgroundImage=''}
const wall=$('#v14Wallpaper');if(wall){wall.value=localStorage.getItem(LS_WALL)||'blue';wall.onchange=()=>{localStorage.setItem(LS_WALL,wall.value);applyWallpaper()}}$('#v14WallpaperFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){alert('Görsel 1 MB sınırını aşıyor. Daha küçük bir görsel seç.');e.target.value='';return}const r=new FileReader();r.onload=()=>{localStorage.setItem(LS_WALL_IMG,String(r.result));localStorage.setItem(LS_WALL,'image');if(wall)wall.value='image';applyWallpaper()};r.readAsDataURL(f)});applyWallpaper();
let pdf14=null,pickMode='text';
function pdfjs(){if(!window.pdfjsLib)throw new Error('PDF önizleme motoru yüklenemedi.');window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';return window.pdfjsLib}
async function capturePdfFile(file){try{const bytes=await file.arrayBuffer();pdf14=await pdfjs().getDocument({data:bytes.slice(0)}).promise;await renderPickPage()}catch(e){console.warn('YEA V14 PDF canvas',e)}}
$('#v13PdfFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)capturePdfFile(f)},true);
async function renderPickPage(){const wrap=$('#v14PdfCanvasWrap'),canvas=$('#v14PdfCanvas');if(!pdf14||!wrap||!canvas)return;let no=Math.max(1,Number($('#v13PdfPageNo')?.value||1));if(no>pdf14.numPages){wrap.classList.add('hidden');return}const p=await pdf14.getPage(no),vp=p.getViewport({scale:1.35}),ctx=canvas.getContext('2d');canvas.width=Math.floor(vp.width);canvas.height=Math.floor(vp.height);await p.render({canvasContext:ctx,viewport:vp}).promise;wrap.classList.remove('hidden');$('#v13PdfFrame')?.classList.add('v14FrameDim');$('#v13PdfEmpty')?.classList.add('hidden')}
$('#v14PdfRenderPick')?.addEventListener('click',renderPickPage);$('#v13PdfPageNo')?.addEventListener('change',renderPickPage);$('#v13PdfPrev')?.addEventListener('click',()=>setTimeout(renderPickPage,80));$('#v13PdfNext')?.addEventListener('click',()=>setTimeout(renderPickPage,80));$('#v14PickText')?.addEventListener('click',()=>{pickMode='text';$('#v14PickText').classList.add('active');$('#v14PickCover').classList.remove('active')});$('#v14PickCover')?.addEventListener('click',()=>{pickMode='cover';$('#v14PickCover').classList.add('active');$('#v14PickText').classList.remove('active')});
$('#v14PdfCanvas')?.addEventListener('click',e=>{const c=e.currentTarget,r=c.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*c.width,py=(e.clientY-r.top)/r.height*c.height;const pageNo=Math.max(1,Number($('#v13PdfPageNo')?.value||1));if(!pdf14||pageNo>pdf14.numPages)return;pdf14.getPage(pageNo).then(p=>{const vp=p.getViewport({scale:1.35}),xmm=px/vp.width*(p.view[2]-p.view[0])*25.4/72,ymm=py/vp.height*(p.view[3]-p.view[1])*25.4/72;$('#v13PdfX').value=xmm.toFixed(1);$('#v13PdfY').value=ymm.toFixed(1);const m=$('#v14PdfPickMark');m.style.left=(e.clientX-r.left)+'px';m.style.top=(e.clientY-r.top)+'px';m.classList.remove('hidden');if(pickMode==='cover')$('#v13PdfCoverW')?.focus();else $('#v13PdfText')?.focus();const msg=$('#v13PdfMsg');if(msg)msg.textContent=`Konum seçildi: soldan ${xmm.toFixed(1)} mm, üstten ${ymm.toFixed(1)} mm.`})});
renderExplorer();renderTrash();augmentDesktop();
})();
