'use strict';
(()=>{
const ITEMS='yea_v13_desktop_items',NOTES='yea_v15_notes',CLIP='yea_v15_clipboard';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'v15-'+Date.now()+Math.random().toString(36).slice(2);
const loadItems=()=>{try{const a=JSON.parse(localStorage.getItem(ITEMS)||'[]');return Array.isArray(a)?a:[]}catch{return[]}};
const saveItems=a=>{localStorage.setItem(ITEMS,JSON.stringify(a));document.dispatchEvent(new CustomEvent('yea-v15-items'));setTimeout(()=>$('#v14FileRefresh')?.click(),20)};
function bring(w){w?.classList.remove('hidden');if(w){w.style.zIndex=String(900+Date.now()%10000);}}
function wireExtraWindow(w){if(!w||w.dataset.v15wired)return;w.dataset.v15wired='1';let d=null,rs=null;const bar=w.querySelector('.v14WinBar'),r=w.querySelector('.v14Resize');
 bar?.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;d={x:e.clientX,y:e.clientY,l:w.offsetLeft,t:w.offsetTop};bar.setPointerCapture(e.pointerId);bring(w)});
 bar?.addEventListener('pointermove',e=>{if(!d||w.classList.contains('max'))return;w.style.left=Math.max(0,d.l+e.clientX-d.x)+'px';w.style.top=Math.max(0,d.t+e.clientY-d.y)+'px'});
 bar?.addEventListener('pointerup',()=>d=null);
 r?.addEventListener('pointerdown',e=>{rs={x:e.clientX,y:e.clientY,w:w.offsetWidth,h:w.offsetHeight};r.setPointerCapture(e.pointerId);e.stopPropagation()});
 r?.addEventListener('pointermove',e=>{if(!rs||w.classList.contains('max'))return;w.style.width=Math.max(320,rs.w+e.clientX-rs.x)+'px';w.style.height=Math.max(250,rs.h+e.clientY-rs.y)+'px'});
 r?.addEventListener('pointerup',()=>rs=null);
}
wireExtraWindow($('#v15NotepadWindow'));wireExtraWindow($('#v15CalcWindow'));

let activeNote=null;
const loadNotes=()=>{try{const a=JSON.parse(localStorage.getItem(NOTES)||'[]');return Array.isArray(a)?a:[]}catch{return[]}};
const saveNotes=a=>localStorage.setItem(NOTES,JSON.stringify(a));
function renderNoteSelect(){
 const a=loadNotes(),s=$('#v15NoteSelect');if(!s)return;
 s.innerHTML=a.length?a.map(n=>`<option value="${esc(n.id)}">${esc(n.title||'Adsız Not')}</option>`).join(''):'<option value="">Not yok</option>';
 if(activeNote&&a.some(n=>n.id===activeNote))s.value=activeNote;
 if($('#v15NotePreview'))$('#v15NotePreview').innerHTML=a.length?a.slice().sort((x,y)=>String(y.updatedAt).localeCompare(String(x.updatedAt))).slice(0,6).map(n=>`<button data-v15-note="${esc(n.id)}"><b>${esc(n.title||'Adsız Not')}</b><span>${esc((n.text||'').slice(0,100))}</span></button>`).join(''):'<span>Henüz not yok.</span>';
}
function loadNote(id){const n=loadNotes().find(x=>x.id===id);if(!n)return;activeNote=n.id;$('#v15NoteTitle').value=n.title||'';$('#v15NoteText').value=n.text||'';$('#v15NoteStatus').textContent='Yüklendi';updateCount();renderNoteSelect()}
function newNote(){activeNote=null;$('#v15NoteTitle').value='';$('#v15NoteText').value='';$('#v15NoteStatus').textContent='Yeni not';updateCount();$('#v15NoteTitle').focus()}
function saveNote(){const title=$('#v15NoteTitle').value.trim()||'Adsız Not',text=$('#v15NoteText').value;let a=loadNotes(),now=new Date().toISOString();if(activeNote)a=a.map(n=>n.id===activeNote?{...n,title,text,updatedAt:now}:n);else{activeNote=uid();a.push({id:activeNote,title,text,createdAt:now,updatedAt:now})}saveNotes(a);$('#v15NoteStatus').textContent='Kaydedildi '+new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});renderNoteSelect()}
function deleteNote(){if(!activeNote)return;if(!confirm('Bu not silinsin mi?'))return;saveNotes(loadNotes().filter(n=>n.id!==activeNote));newNote();renderNoteSelect()}
function downloadNote(){const text=$('#v15NoteText').value,title=($('#v15NoteTitle').value.trim()||'not').replace(/[\\/:*?"<>|]+/g,'-');const b=new Blob([text],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=title+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function updateCount(){$('#v15NoteCount').textContent=($('#v15NoteText')?.value.length||0)+' karakter'}
function openNotepad(){bring($('#v15NotepadWindow'));renderNoteSelect();if(activeNote)loadNote(activeNote)}
$('#v15OpenNotepadWindow')?.addEventListener('click',openNotepad);$('#v15StartNotepad')?.addEventListener('click',openNotepad);$('#v15TaskNotepad')?.addEventListener('click',openNotepad);
$('#v15NoteNew')?.addEventListener('click',newNote);$('#v15NoteSave')?.addEventListener('click',saveNote);$('#v15NoteDelete')?.addEventListener('click',deleteNote);$('#v15NoteDownload')?.addEventListener('click',downloadNote);$('#v15NoteSelect')?.addEventListener('change',e=>loadNote(e.target.value));$('#v15NoteText')?.addEventListener('input',()=>{$('#v15NoteStatus').textContent='Değiştirildi';updateCount()});$('#v15NoteTitle')?.addEventListener('input',()=>$('#v15NoteStatus').textContent='Değiştirildi');
$('#v15NotePreview')?.addEventListener('click',e=>{const b=e.target.closest('[data-v15-note]');if(b){openNotepad();loadNote(b.dataset.v15Note)}});renderNoteSelect();

function tokenize(src){let s=String(src||'').replace(/,/g,'.').replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/\s+/g,''),out=[],i=0;while(i<s.length){const c=s[i];if(/[0-9.]/.test(c)){let j=i+1;while(j<s.length&&/[0-9.]/.test(s[j]))j++;const n=s.slice(i,j);if((n.match(/\./g)||[]).length>1)throw Error('Geçersiz sayı');out.push(Number(n));i=j;continue}if('+-*/()'.includes(c)){out.push(c);i++;continue}throw Error('Geçersiz karakter')}return out}
function calcSafe(src){const t=tokenize(src),vals=[],ops=[];const prec=o=>o==='+'||o==='-'?1:o==='*'||o==='/'?2:0;const apply=()=>{const o=ops.pop(),b=vals.pop(),a=vals.pop();if(a===undefined||b===undefined)throw Error('Eksik işlem');if(o==='+')vals.push(a+b);if(o==='-')vals.push(a-b);if(o==='*')vals.push(a*b);if(o==='/'){if(b===0)throw Error('Sıfıra bölünemez');vals.push(a/b)}};let prev='start';for(const x of t){if(typeof x==='number'){vals.push(x);prev='num';continue}if(x==='('){ops.push(x);prev='(';continue}if(x===')'){while(ops.length&&ops.at(-1)!=='(')apply();if(ops.pop()!=='(')throw Error('Parantez hatası');prev=')';continue}if((x==='+'||x==='-')&&(prev==='start'||prev==='('||prev==='op'))vals.push(0);while(ops.length&&ops.at(-1)!=='('&&prec(ops.at(-1))>=prec(x))apply();ops.push(x);prev='op'}while(ops.length){if(ops.at(-1)==='(')throw Error('Parantez hatası');apply()}if(vals.length!==1||!Number.isFinite(vals[0]))throw Error('Hesaplanamadı');return vals[0]}
function openCalc(){bring($('#v15CalcWindow'));$('#v15CalcDisplay').focus()}
function runCalc(){const d=$('#v15CalcDisplay'),expr=d.value;try{const r=calcSafe(expr);$('#v15CalcHistory').textContent=expr+' =';d.value=String(Math.round((r+Number.EPSILON)*1e12)/1e12)}catch(e){$('#v15CalcHistory').textContent=e.message}}
$('#v15StartCalc')?.addEventListener('click',openCalc);$('#v15TaskCalc')?.addEventListener('click',openCalc);$('#v15OpenCalcWindow')?.addEventListener('click',openCalc);
$('#v15CalcKeys')?.addEventListener('click',e=>{const b=e.target.closest('[data-calc]');if(!b)return;const k=b.dataset.calc,d=$('#v15CalcDisplay');if(k==='clear'){d.value='';$('#v15CalcHistory').textContent='';return}if(k==='=')return runCalc();if(k==='percent'){if(d.value)d.value='('+d.value+')/100';return}d.value+=k;d.focus()});$('#v15CalcDisplay')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runCalc()}});if($('#v15CalcInline'))$('#v15CalcInline').innerHTML='<span>Başlat menüsünden veya görev çubuğundan Hesap Makinesini pencere olarak açabilirsin.</span>';

let fileCtxId=null;
function showAt(el,x,y){el.style.left=Math.min(x,innerWidth-210)+'px';el.style.top=Math.min(y,innerHeight-260)+'px';el.classList.remove('hidden')}
$('#v13Desktop')?.addEventListener('contextmenu',e=>{if(e.target.closest('.v13DeskIcon,#v13Context'))return;e.preventDefault();showAt($('#v15DesktopContext'),e.clientX,e.clientY)});
document.addEventListener('click',e=>{if(!e.target.closest('#v15DesktopContext'))$('#v15DesktopContext')?.classList.add('hidden');if(!e.target.closest('#v15FileContext'))$('#v15FileContext')?.classList.add('hidden')});
$('#v15DesktopContext')?.addEventListener('click',e=>{const b=e.target.closest('[data-v15-dctx]');if(!b)return;$('#v15DesktopContext').classList.add('hidden');const a=b.dataset.v15Dctx;if(a==='folder')$('#v13NewFolder')?.click();if(a==='shortcut')$('#v13NewShortcut')?.click();if(a==='note')openNotepad();if(a==='refresh')location.reload();if(a==='wallpaper')window.v13AppOpen('settings');if(a==='paste')pasteInto(null)});

function getClip(){try{return JSON.parse(localStorage.getItem(CLIP)||'null')}catch{return null}}function setClip(v){v?localStorage.setItem(CLIP,JSON.stringify(v)):localStorage.removeItem(CLIP)}
function descendants(items,id){const ids=[];const walk=p=>items.filter(x=>x.folderId===p).forEach(c=>{ids.push(c.id);if(c.type==='folder')walk(c.id)});walk(id);return ids}
function cloneSubtree(rootId,targetFolder){const items=loadItems(),root=items.find(x=>x.id===rootId);if(!root)return;const map=new Map(),toClone=[rootId,...descendants(items,rootId)];toClone.forEach(old=>map.set(old,uid()));const copies=toClone.map(old=>{const x=items.find(i=>i.id===old),parent=old===rootId?targetFolder:(map.get(x.folderId)||targetFolder);return {...x,id:map.get(old),folderId:parent,name:old===rootId?x.name+' - Kopya':x.name,type:(x.type==='fileHandle'||x.type==='dirHandle')?'path':x.type,target:(x.type==='fileHandle'||x.type==='dirHandle')?'Bağlantı kopyası için asıl simgeyi kullan':x.target}});saveItems([...items,...copies])}
function pasteInto(folderId){const c=getClip();if(!c)return alert('Panoda YEA öğesi yok.');let items=loadItems(),x=items.find(i=>i.id===c.id);if(!x)return setClip(null);if(c.mode==='copy')cloneSubtree(c.id,folderId);else{if(folderId===x.id||descendants(items,x.id).includes(folderId))return alert('Klasör kendi altına taşınamaz.');x.folderId=folderId;saveItems(items.map(i=>i.id===x.id?x:i));setClip(null)}}
$('#v14FileGrid')?.addEventListener('contextmenu',e=>{const b=e.target.closest('[data-v14-item]');if(!b)return;e.preventDefault();fileCtxId=b.dataset.v14Item;showAt($('#v15FileContext'),e.clientX,e.clientY)});
$('#v15FileContext')?.addEventListener('click',e=>{const b=e.target.closest('[data-v15-fctx]');if(!b||!fileCtxId)return;const a=b.dataset.v15Fctx,x=loadItems().find(i=>i.id===fileCtxId);$('#v15FileContext').classList.add('hidden');if(!x)return;if(a==='open')bypassOpen(x);if(a==='copy')setClip({mode:'copy',id:x.id});if(a==='cut')setClip({mode:'cut',id:x.id});if(a==='rename'){const n=prompt('Yeni ad',x.name);if(n?.trim())saveItems(loadItems().map(i=>i.id===x.id?{...i,name:n.trim()}:i))}if(a==='trash'){const del=$('#v13DesktopGrid [data-id="'+CSS.escape(x.id)+'"]');if(del){del.click();$('#v13Context [data-v13-ctx="delete"]')?.click()}else alert('Çöp Kutusuna taşımak için öğeyi Masaüstünden sağ tıklayabilirsin.')}});
function bypassOpen(x){if(x.type==='app')return window.v13AppOpen(x.target);if(x.type==='url')return window.open(x.target,'_blank','noopener,noreferrer');if(x.type==='folder'){const btn=$('#v14FolderTree [data-v14-folder="'+CSS.escape(x.id)+'"]');btn?.click();return}if(x.type==='path'){navigator.clipboard?.writeText(x.target);alert('Yol panoya kopyalandı.');return}alert('Bağlı gerçek dosya/klasörü Masaüstündeki simgesinden aç.')}

$('#v13DesktopGrid')?.addEventListener('drop',e=>{const target=e.target.closest('.v13DeskIcon[data-id]');if(!target)return;const items=loadItems(),dest=items.find(x=>x.id===target.dataset.id);if(dest?.type!=='folder')return;const from=e.dataTransfer?.getData('text/plain');if(!from||from===dest.id)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(descendants(items,from).includes(dest.id))return;saveItems(items.map(x=>x.id===from?{...x,folderId:dest.id}:x))},true);
$('#v14FileGrid')?.addEventListener('dragstart',e=>{const b=e.target.closest('[data-v14-item]');if(b)e.dataTransfer.setData('text/x-yea-item',b.dataset.v14Item)});$('#v14FileGrid')?.addEventListener('dragover',e=>{if(e.target.closest('[data-v14-item]'))e.preventDefault()});$('#v14FileGrid')?.addEventListener('drop',e=>{const b=e.target.closest('[data-v14-item]');if(!b)return;const items=loadItems(),dest=items.find(x=>x.id===b.dataset.v14Item),from=e.dataTransfer.getData('text/x-yea-item');if(dest?.type==='folder'&&from&&from!==dest.id){e.preventDefault();if(descendants(items,from).includes(dest.id))return;saveItems(items.map(x=>x.id===from?{...x,folderId:dest.id}:x))}});new MutationObserver(()=>$$('#v14FileGrid [data-v14-item]').forEach(b=>b.draggable=true)).observe($('#v14FileGrid')||document.body,{childList:true,subtree:true});

async function handleDroppedFiles(e){const list=[...e.dataTransfer.items].filter(i=>i.kind==='file');if(!list.length)return;$('#v15DropHint')?.classList.add('hidden');for(const it of list){try{if(it.getAsFileSystemHandle){const h=await it.getAsFileSystemHandle();if(h){const id=uid();await storeHandle(id,h);const isDir=h.kind==='directory';saveItems([...loadItems(),{id,type:isDir?'dirHandle':'fileHandle',name:h.name,target:'',icon:isDir?'🗂':h.name.toLowerCase().endsWith('.pdf')?'📕':'📎',folderId:null}]);continue}}const f=it.getAsFile();if(f){if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){window.v13AppOpen('pdf');const input=$('#v13PdfFile');const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}else alert(f.name+' açıldı fakat bu tarayıcı kalıcı masaüstü bağlantısını desteklemiyor. Windows Chrome/Edge kullanabilirsin.')}}catch(err){console.warn(err)}}}
async function storeHandle(id,h){return new Promise((res,rej)=>{const r=indexedDB.open('yea_v13_handles',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('h'))r.result.createObjectStore('h')};r.onsuccess=()=>{const tx=r.result.transaction('h','readwrite');tx.objectStore('h').put(h,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)};r.onerror=()=>rej(r.error)})}
const desk=$('#v13Desktop');desk?.addEventListener('dragenter',e=>{if([...e.dataTransfer.types].includes('Files'))$('#v15DropHint')?.classList.remove('hidden')});desk?.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault()});desk?.addEventListener('dragleave',e=>{if(!desk.contains(e.relatedTarget))$('#v15DropHint')?.classList.add('hidden')});desk?.addEventListener('drop',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();handleDroppedFiles(e)}});

document.addEventListener('keydown',e=>{const tag=(e.target.tagName||'').toLowerCase();if(tag==='input'||tag==='textarea')return;if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='n'){e.preventDefault();openNotepad();newNote()}if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='c'){e.preventDefault();openCalc()}});document.addEventListener('yea-v15-items',()=>setTimeout(()=>$('#v14FileRefresh')?.click(),20));
})();
