'use strict';
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const BUDGET='yea_v16_budget',MUTE='yea_v16_notify_mute';
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
const now=()=>new Date(),days=(a,b)=>Math.ceil((b-a)/86400000);
function readBudget(){try{return {...{limit:0,warn:80},...JSON.parse(localStorage.getItem(BUDGET)||'{}')}}catch{return {limit:0,warn:80}}}
function monthKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function expenseThisMonth(){const m=monthKey();return (typeof finance!=='undefined'?finance:[]).filter(x=>x.entry_type==='expense'&&String(x.entry_date).slice(0,7)===m).reduce((s,x)=>s+Number(x.amount||0),0)}
function renderBudget(){const b=readBudget(),spent=expenseThisMonth(),left=b.limit-spent,pct=b.limit>0?spent/b.limit*100:0;$('#v16BudgetLimit').textContent=b.limit?money(b.limit):'Hedef yok';$('#v16BudgetSpent').textContent=money(spent);$('#v16BudgetLeft').textContent=b.limit?money(left):'—';$('#v16BudgetPct').textContent=b.limit?Math.round(pct)+'%':'—';const fill=$('#v16BudgetBarFill');if(fill){fill.style.width=Math.min(100,pct)+'%';fill.dataset.level=pct>=100?'over':pct>=b.warn?'warn':'ok'}const hint=$('#v16BudgetHint');if(hint)hint.textContent=!b.limit?'Bir bütçe hedefi belirleyince YEA harcamaları otomatik izler.':pct>=100?'⚠️ Aylık bütçe aşıldı.':pct>=b.warn?'⚠️ Bütçe uyarı eşiğine ulaştın.':'Bütçe plan dahilinde görünüyor.'}
function openBudget(){const b=readBudget();$('#v16BudgetInput').value=b.limit||'';$('#v16BudgetWarn').value=String(b.warn||80);$('#v16BudgetModal').classList.remove('hidden')}
$('#v16BudgetEdit')?.addEventListener('click',openBudget);$('#v16BudgetClose')?.addEventListener('click',()=>$('#v16BudgetModal').classList.add('hidden'));$('#v16BudgetModal')?.addEventListener('click',e=>{if(e.target.id==='v16BudgetModal')e.currentTarget.classList.add('hidden')});$('#v16BudgetForm')?.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem(BUDGET,JSON.stringify({limit:Number($('#v16BudgetInput').value||0),warn:Number($('#v16BudgetWarn').value||80)}));$('#v16BudgetModal').classList.add('hidden');renderBudget();refreshNotifications()});
function vehicleCounters(){const list=typeof vehicles!=='undefined'?vehicles:[],odo=Math.max(0,...list.map(v=>Number(v.odometer||0))),today=now();const rows=list.filter(v=>v.status!=='archived'&&(v.next_due_date||v.next_due_km)).map(v=>{const dateLeft=v.next_due_date?days(today,new Date(v.next_due_date+'T23:59:59')):null,kmLeft=v.next_due_km?Number(v.next_due_km)-odo:null;return {...v,dateLeft,kmLeft}}).sort((a,b)=>Math.min(a.dateLeft??99999,(a.kmLeft??999999)/50)-Math.min(b.dateLeft??99999,(b.kmLeft??999999)/50));return {odo,rows}}
function renderVehicleCounters(){
  const h=$('#v16VehicleCounterGrid');if(!h)return;
  const {odo,rows}=vehicleCounters(),show=rows.slice(0,6);
  const first=`<div class="v16Counter"><span>Son görülen km</span><b>${odo?odo.toLocaleString('tr-TR')+' km':'Kayıt yok'}</b></div>`;
  const rest=show.length?show.map(v=>{
    const urgent=(v.dateLeft!=null&&v.dateLeft<=30)||(v.kmLeft!=null&&v.kmLeft<=1000);
    const dateText=v.dateLeft!=null?(v.dateLeft<0?Math.abs(v.dateLeft)+' gün geçti':v.dateLeft+' gün'):'';
    const kmText=v.kmLeft!=null?(v.kmLeft<0?Math.abs(v.kmLeft).toLocaleString('tr-TR')+' km geçti':v.kmLeft.toLocaleString('tr-TR')+' km'):'';
    return `<div class="v16Counter ${urgent?'urgent':''}"><span>${escapeSafe(v.title||'Araç işi')}</span><b>${dateText}${dateText&&kmText?' • ':''}${kmText}</b></div>`;
  }).join(''):'<div class="v16Counter"><span>Yaklaşan bakım</span><b>Kayıt yok</b></div>';
  h.innerHTML=first+rest;
}
function escapeSafe(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function notificationItems(){const out=[],today=now(),m=monthKey();const taskList=typeof tasks!=='undefined'?tasks:[];taskList.filter(t=>t.status!=='done'&&t.due_at).forEach(t=>{const d=new Date(t.due_at),left=days(today,d);if(d<today&&d.toDateString()!==today.toDateString())out.push({level:'high',icon:'⏰',title:'Geciken görev',text:t.title,open:'tasks'});else if(left<=1)out.push({level:'med',icon:'✅',title:'Bugünün görevi',text:t.title,open:'tasks'})});const projs=typeof projects!=='undefined'?projects:[];projs.filter(p=>p.status==='active'&&p.due_date).forEach(p=>{const left=days(today,new Date(p.due_date+'T23:59:59'));if(left<=7)out.push({level:left<0?'high':'med',icon:'📁',title:left<0?'Proje tarihi geçti':'Proje tarihi yaklaşıyor',text:`${p.title} • ${left<0?Math.abs(left)+' gün geçti':left+' gün'}`,open:'projects'})});const vc=vehicleCounters();vc.rows.filter(v=>(v.dateLeft!=null&&v.dateLeft<=30)||(v.kmLeft!=null&&v.kmLeft<=1000)).slice(0,4).forEach(v=>out.push({level:(v.dateLeft!=null&&v.dateLeft<0)||(v.kmLeft!=null&&v.kmLeft<0)?'high':'med',icon:'🚗',title:'Araç işi yaklaşıyor',text:v.title,open:'vehicle'}));const rad=typeof radiology!=='undefined'?radiology:[],units=new Set(rad.filter(r=>String(r.period).slice(0,7)===m).map(r=>r.unit));if(units.size<8)out.push({level:'med',icon:'📊',title:'Radyoloji verisi eksik',text:`Bu ay ${8-units.size} birim henüz girilmemiş.`,open:'radiology'});const b=readBudget(),spent=expenseThisMonth(),pct=b.limit?spent/b.limit*100:0;if(b.limit&&pct>=b.warn)out.push({level:pct>=100?'high':'med',icon:'💰',title:pct>=100?'Bütçe aşıldı':'Bütçe uyarısı',text:`Aylık hedefin %${Math.round(pct)} kullanıldı.`,open:'finance'});return out.slice(0,20)}
function isMuted(){return localStorage.getItem(MUTE)===new Date().toISOString().slice(0,10)}
function refreshNotifications(){const items=isMuted()?[]:notificationItems(),list=$('#v16NotifyList'),badge=$('#v16NotifyBadge');if(list)list.innerHTML=items.length?items.map(n=>`<button class="v16NotifyItem ${n.level}" data-open="${n.open}"><span>${n.icon}</span><div><b>${escapeSafe(n.title)}</b><p>${escapeSafe(n.text)}</p></div><em>›</em></button>`).join(''):'<div class="v16NotifyEmpty">🎉 Şu an önemli bir uyarı yok.</div>';if(badge){badge.textContent=items.length?String(items.length):'';badge.classList.toggle('hidden',!items.length)}renderDailyBrief()}
function openNotify(){refreshNotifications();const w=$('#v16NotifyWindow');w.classList.remove('hidden');w.style.zIndex=String(1200+Date.now()%10000)}
$('#v16NotifyBtn')?.addEventListener('click',openNotify);$('#v16StartNotify')?.addEventListener('click',openNotify);$('#v16NotifyRefresh')?.addEventListener('click',refreshNotifications);$('#v16NotifyMuteToday')?.addEventListener('click',()=>{localStorage.setItem(MUTE,new Date().toISOString().slice(0,10));refreshNotifications()});$('#v16NotifyList')?.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b){window.v13AppOpen(b.dataset.open);$('#v16NotifyWindow').classList.add('hidden')}});
const commands=[['Masaüstü','🖥','desktop'],['Bugün','☀️','today'],['Görevler','✅','tasks'],['Takvim','📅','calendar'],['Projeler','📁','projects'],['Radyoloji','📊','radiology'],['Finans','💰','finance'],['Araç','🚗','vehicle'],['PDF Editör','📕','pdf'],['Belgeler','📄','docs'],['Dosya Yöneticisi','🗃','files'],['Not Defteri','📝','notepad'],['Hesap Makinesi','🧮','calculator'],['Ayarlar','⚙️','settings'],['Bildirim Merkezi','🔔','__notify'],['Bütçe hedefini ayarla','🎯','__budget']];
function commandOpen(){const c=$('#v16Command');c.classList.remove('hidden');$('#v16CommandInput').value='';renderCommands('');setTimeout(()=>$('#v16CommandInput').focus(),10)}
function commandClose(){$('#v16Command').classList.add('hidden')}
function renderCommands(q){q=String(q||'').trim().toLocaleLowerCase('tr-TR');const rows=commands.filter(x=>!q||x[0].toLocaleLowerCase('tr-TR').includes(q)).slice(0,10);$('#v16CommandList').innerHTML=rows.map((x,i)=>`<button data-cmd="${x[2]}" class="${i===0?'active':''}"><span>${x[1]}</span><b>${x[0]}</b></button>`).join('')||'<div class="v16CommandEmpty">Sonuç yok.</div>'}
function runCommand(id){commandClose();if(id==='__notify')return openNotify();if(id==='__budget')return openBudget();if(id==='notepad')return $('#v15TaskNotepad')?.click();if(id==='calculator')return $('#v15TaskCalc')?.click();window.v13AppOpen(id)}
$('#v16CommandBtn')?.addEventListener('click',commandOpen);$('#v16StartCommand')?.addEventListener('click',commandOpen);$('#v16Command')?.addEventListener('click',e=>{if(e.target.id==='v16Command')commandClose();const b=e.target.closest('[data-cmd]');if(b)runCommand(b.dataset.cmd)});$('#v16CommandInput')?.addEventListener('input',e=>renderCommands(e.target.value));$('#v16CommandInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){const b=$('#v16CommandList [data-cmd]');if(b)runCommand(b.dataset.cmd)}if(e.key==='Escape')commandClose()});document.addEventListener('keydown',e=>{if(e.altKey&&e.code==='Space'){e.preventDefault();commandOpen()}else if(e.key==='Escape'&&!$('#v16Command')?.classList.contains('hidden'))commandClose()});
function renderDailyBrief(){const h=$('#v16BriefCards'),focus=$('#v16BriefFocus');if(!h||!focus)return;$('#v16BriefDate').textContent=new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'});const notices=notificationItems(),openTasks=(typeof tasks!=='undefined'?tasks:[]).filter(t=>t.status!=='done'),overdue=openTasks.filter(t=>t.due_at&&new Date(t.due_at)<new Date()),activeProjects=(typeof projects!=='undefined'?projects:[]).filter(p=>p.status==='active'),spent=expenseThisMonth(),b=readBudget(),vc=vehicleCounters();h.innerHTML=`<div><span>Açık görev</span><b>${openTasks.length}</b><small>${overdue.length} geciken</small></div><div><span>Aktif proje</span><b>${activeProjects.length}</b><small>${activeProjects.filter(p=>!p.next_action).length} sonraki adımı eksik</small></div><div><span>Bu ay gider</span><b>${money(spent)}</b><small>${b.limit?'Bütçenin %'+Math.round(spent/b.limit*100):'Bütçe hedefi yok'}</small></div><div><span>Yaklaşan araç işi</span><b>${vc.rows.filter(v=>(v.dateLeft!=null&&v.dateLeft<=30)||(v.kmLeft!=null&&v.kmLeft<=1000)).length}</b><small>${vc.odo?vc.odo.toLocaleString('tr-TR')+' km':'km kaydı yok'}</small></div>`;const top=notices.slice(0,3);focus.innerHTML=top.length?`<b>Bugün önce bunlara odaklan:</b>${top.map((n,i)=>`<button data-open="${n.open}"><span>${i+1}</span><div><strong>${escapeSafe(n.title)}</strong><small>${escapeSafe(n.text)}</small></div></button>`).join('')}`:'<b>Bugünün kritik işi görünmüyor.</b><p>Takvim veya projelerden yeni bir hedef seçebilirsin.</p>'}
$('#v16BriefFocus')?.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)window.v13AppOpen(b.dataset.open)});$('#v16BriefRefresh')?.addEventListener('click',()=>{renderBudget();renderVehicleCounters();refreshNotifications()});
function refreshAll16(){renderBudget();renderVehicleCounters();refreshNotifications()}
setTimeout(refreshAll16,500);setInterval(refreshAll16,60000);document.addEventListener('click',e=>{if(e.target.closest('#finAdd,#financeList,#vehAdd,#vehicleList,#taskList,#projectList'))setTimeout(refreshAll16,500)});
})();
